### ISSUE TITLE
Problem with libstdc++.so.6 bundled with steam-runtime 2014-04-15

### ISSUE THREAD

**Issue by jsa1983** [ValveSoftware/steam-runtime#13]
After a graphics drivers and llvm update (mesa git 2014.04.26, compiled with llvm 3.5; llvm 3.5 svn 207303) I have experienced the following problem:

libGL error: dlopen /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/radeonsi_dri.so failed (${ORIGIN}/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/radeonsi_dri.so failed (/usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version`GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/swrast_dri.so failed (${ORIGIN}/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
ExecCommandLine: "/home/jose/.local/share/Steam/ubuntu12_32/steam"
System startup time: 8,15 seconds
libGL error: dlopen /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/radeonsi_dri.so failed (${ORIGIN}/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/radeonsi_dri.so failed (/usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: dlopen /usr/lib/i386-linux-gnu/dri/swrast_dri.so failed (/home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version`GLIBCXX_3.4.18' not found (required by /usr/lib/i386-linux-gnu/libLLVM-3.5.0.so.1))
libGL error: dlopen ${ORIGIN}/dri/swrast_dri.so failed (${ORIGIN}/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: dlopen /usr/lib/dri/swrast_dri.so failed (/usr/lib/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Running Steam on ubuntu 14.04 64-bit

However the command strings /home/jose/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6 | grep GLIB did show version 3.4.18.

Removing the libstdc++.so.6 libstdc++.so.6.0.16 files solved the issue and now steam starts with direct GPU acceleration.

**Comment by dequis** [comment]
Can this be reopened? Still had to remove libstdc++.so after the last update.

**Comment by mikefaille** [comment]
I used Steam regularly with Fedora 19/20/21 and I never saw this issue.
Maybe, it's only a Ubuntu/(Debian ?) case.
Oh, and, I'm a Steam beta tester.

**Comment by dequis** [comment]
The [arch linux wiki](https://wiki.archlinux.org/index.php/steam#Steam_runtime_issues) suggests it's something specific to the radeon open source driver.

**Comment by sylware** [comment]
On Tue, Jan 20, 2015 at 08:46:37AM -0800, dx wrote:
> The [arch linux 
> wiki](https://wiki.archlinux.org/index.php/steam#Steam_runtime_issues)
> suggests it's something specific to the radeon open source driver.

libgcc and libstdc++ are a mess (the usual c++ ABI kludge and gcc being "more
than a machine code generator").

Valve and games should statically link libgcc and libstdc++ into their runtime
to avoid many conflicts and more. For instance libstdc++ provides *GCC* c++
ABI, which is *GCC* only, then coupling games and steam runtime with gcc only
and that forever. Asking another c++ compiler to follow GCC c++ ABI is asking
for troubles, it's insane, period. The only reasonable binary interface is ELF
with basic C symbols (even the versioned symbols may bring to you a nice set of
troubles).

... or *ALL* gnu/linux distros should statically link libgcc and libstdc++ in
their graphic and sound stack:x11 libs, 3D libs, alsalib (pulseaudio interface
is not reasonnable, better stick with alsa and let pulseaudio do audio software
mixing as an alsalib module).

-- 
Sylvain

**Comment by dequis** [comment]
@sylware just curious, do you work at valve?

**Comment by mikefaille** [comment]
I don't think main gnu/linux distro will statically link libgcc and libstdc++.

**Comment by weirddan455** [comment]
@sylware The problem is even IF Valve were to statically link libsdtc++ they still have third-party games to support.  There's no way to get ALL the third-party devlopers to recompile their already released games just for this.  Also, nearly all Linux distributions frown on statically linking their system libraries.  That's not the answer either.

IMO the best solution is to simply remove libstdc++ from steam-runtime and let it use the system library there.  libstdc++ is designed to be forward-compatible.  I quote: https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html

"Extending existing, stable ABIs. Versioning gives subsequent releases of library binaries the ability to add new symbols and add functionality, all the while retaining compatibility with the previous releases in the series. Thus, program binaries linked with the initial release of a library binary will still run correctly if the library binary is replaced by carefully-managed subsequent library binaries. This is called forward compatibility.

The reverse (backwards compatibility) is not true. It is not possible to take program binaries linked with the latest version of a library binary in a release series (with additional symbols added), substitute in the initial release of the library binary, and remain link compatible. "

Therefore the only problem should be with systems that have a libstdc++ that's too outdated so perhaps Valve could write a script that places that library in steam-runtime only if the system version is too old.

I personally haven't had any problems using my system's libstdc++ and I'm on Arch Linux with gcc-libs 4.9.2 which you claim to be terrible (works just fine for me and I've not read reports from other Arch users about breakage there.)

**Comment by sylware** [comment]
On Wed, Jan 21, 2015 at 03:32:39AM -0800, weirddan455 wrote:
> @sylware The problem is even IF Valve were to statically link libsdtc++ they still have third-party games to support.  There's no way to get ALL the third-party devlopers to recompile their already released games just for this.  Also, nearly all Linux distributions frown on statically linking their system libraries.  That's not the answer either.
> 
> IMO the best solution is to simply remove libstdc++ from steam-runtime and let it use the system library there.  libstdc++ is designed to be forward-compatible.  I quote: https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
> 
> "Extending existing, stable ABIs. Versioning gives subsequent releases of library binaries the ability to add new symbols and add functionality, all the while retaining compatibility with the previous releases in the series. Thus, program binaries linked with the initial release of a library binary will still run correctly if the library binary is replaced by carefully-managed subsequent library binaries. This is called forward compatibility.
> 
> The reverse (backwards compatibility) is not true. It is not possible to take program binaries linked with the latest version of a library binary in a release series (with additional symbols added), substitute in the initial release of the library binary, and remain link compatible. "
> 
> Therefore the only problem should be with systems that have a libstdc++ that's too outdated so perhaps Valve could write a script that places that library in steam-runtime only if the system version is too old.
> 
> I personally haven't had any problems using my system's libstdc++ and I'm on Arch Linux with gcc-libs 4.9.2 which you claim to be terrible (works just fine for me and I've not read reports from other Arch users about breakage there.)

There is a difference between theory and reality. The theory will always be
beautifull, but the reality=tons a troubles (usually proportional of the
complexity of the components and the time frame of support).

There are 2 pbs: the c++ ABI kludge/mess (any c++ compiler), and the gcc
specific libgcc mess. Removing libstdc++ would mean that the runtime is hard
dependent an gcc c++ ABI, same thing for libgcc. Ground experience and common
sense dictates that the most important target for a binary runtime is to depend
on as few as possible interfaces which should be as simple as possible to
maximize its chances to run on "any distro".

For the game "industry", that minimal set of distro interfaces would be:
  - ELF loader with a minimal linux syscalls abstraction layer
    (usually a subset of libc "standard")
  - ELF x11/GL libs (display/3D and keyboard/mouse)
  - ELF libalsa
    (sound, actually I don't know if it can handle dynamic plug/unplug of
     microphone properly though).
  - linux device nodes for pad/joystick, usually /dev/input/jsX.
    (Do not rely on ELF libudev, as this component does exist in many "flavors"
     now which, on paper, do work together, and in reality not really, use direct
     uevent netlink/sysfs linux interface avoiding to use any information
     enrichment provided by a system udev)
    
Everything "above" should be packaged and shipped with the binary runtime. That
means statically linked to avoid symbol conflicts with the ELF dependency graph
of those libs (or manually load ELF libs with manual symbol resolving). For
instance Mesa (most of GL libs out there), pulls libstdc++ because of llvm. I'm
currently testing steam with a fedora rawhide gcc 4.9.2, steam runtime libgcc
and libstdc++ do not work and do conflict. I'll soon use a custom minimal
distro based on above interfaces. The proper course of action with such a mess,
is to avoid conflicts with static linking or manual ELF loading: gcc
interfaces (c++ ABI and libgcc) are a kludgy/brain damaged mess, do not rely on
their "theorical" stability. Even ELF with symbol versionning is troublesome...

my 2 c,

-- 
Sylvain

**Comment by sylware** [comment]
On Tue, Jan 20, 2015 at 11:52:35AM -0800, dx wrote:
> @sylware just curious, do you work at valve?

Nope. I'm unemployed and closing to homelessness. Then no conflict of interest here.
Only the will to make things work with the minimal global technical cost.

-- 
Sylvain

**Comment by sylware** [comment]
On Tue, Jan 20, 2015 at 12:17:00PM -0800, mikefaille wrote:
> I don't think main gnu/linux distro will statically link libgcc and libstdc++.

Wrong, I say *ALL* linux distros... ;) (irony)

-- 
Sylvain

**Comment by chrisjamesberg** [comment]
Still having this problem running Trusty on second Gen chromebook pixel. Deleting all these files doesn't solve my problem.

**Comment by chrisjamesberg** [comment]
This is the error I'm getting after deleting all those files.
ERROR: ld.so: object '/home/chrisberg/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by devurandom** [comment]
@chrisjamesberg I would say that your problem is that Steams is trying to load a 32-bit library (gameoverlayrenderer.so) into a 64-bit program.

**Comment by mdiluz** [comment]
@chrisjamesberg @devurandom that message is seen in all steam games as steam puts both the 32bit and 64bit overlay in LD_PRELOAD, one will always fail. I wouldn't consider it an error, it's an unfortunate side effect.

**Comment by at46** [comment]
You can use "LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam" as a workaround for this problem. It allows you to start steam with the system lib without deleting the integrated one. Works great for me on Ubuntu 64bit 14.04 with HWE from utopic and free radeon driver. Source: https://wirejungle.wordpress.com/2015/01/09/how-to-fix-broken-steam-linux-client-with-radeon-graphics-driver-workaround/

**Comment by sharkwouter** [comment]
Why has this issue been closed? I've encountered this on Debian Jessie, Arch Linux, Ubuntu 14.10+, OpenSUSE 13.2, Fedora 21 and SteamOS Brewmaster.

**Comment by sylware** [comment]
On Sat, Jun 27, 2015 at 03:50:09PM -0700, Wouter Wijsman wrote:
> Why has this issue been closed? I've encountered this on Debian Jessie, Arch Linux, Ubuntu 14.10+, OpenSUSE 13.2, Fedora 21 and SteamOS Brewmaster.

The steamruntime provided to game devs should provide a static libstdc++ and a static libgcc.

c++ ABI and libgcc are troubles, always.

**Comment by agilob** [comment]
same here on 64bits ArchLinux with L4D2. The issue appeared out of nowhere and it happens after several seconds up to a few minutes of game. None of available solutions helped.

**Comment by RobLoach** [comment]
Just ran into this again, and @pinumbernumber's fix at https://github.com/ValveSoftware/steam-runtime/issues/13#issuecomment-60326157 fixed it.

**Comment by devurandom** [comment]
Following script fixes it on Gentoo/Linux:
```bash
#!/bin/bash

gcc_lib32dir=$(gcc-config --get-lib-path | cut -d: -f2)

export LD_PRELOAD=${gcc_lib32dir}/libstdc++.so

exec ~/.steam/steam/steam.sh
```

**Comment by rekotc** [comment]
I'm currently having the same problem trying to load steam, I've already deleted all the offending libraries from /.local/share/Steam/ubuntu12_32/steam-runtime/, but i still get the following error:

    /home/rekotc/.local/share/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
    /home/rekotc/.local/share/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
    Running Steam on debian  64-bit
    /home/rekotc/.local/share/Steam/steam.sh: riga 161: VERSION_ID: variabile non assegnata
    STEAM_RUNTIME is enabled automatically
    Installing breakpad exception handler for appid(steam)/version(0)
    libGL: OpenDriver: trying /usr/lib32/dri/tls/r600_dri.so
    libGL: OpenDriver: trying /usr/lib32/dri/r600_dri.so
    libGL: dlopen /usr/lib32/dri/r600_dri.so failed (/usr/lib32/dri/r600_dri.so: impossibile aprire il file oggetto condiviso: File o directory non esistente)
    libGL: OpenDriver: trying /usr/lib64/dri/tls/r600_dri.so
    libGL: OpenDriver: trying /usr/lib64/dri/r600_dri.so
    libGL: dlopen /usr/lib64/dri/r600_dri.so failed (/usr/lib64/dri/r600_dri.so: classe ELF errata: ELFCLASS64)
    libGL error: unable to load driver: r600_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: r600
    libGL: OpenDriver: trying /usr/lib32/dri/tls/swrast_dri.so
    libGL: OpenDriver: trying /usr/lib32/dri/swrast_dri.so
    libGL: dlopen /usr/lib32/dri/swrast_dri.so failed (/usr/lib32/dri/swrast_dri.so: impossibile aprire il file oggetto condiviso: File o directory non esistente)
    libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
    libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
    libGL: dlopen /usr/lib64/dri/swrast_dri.so failed (/usr/lib64/dri/swrast_dri.so: classe ELF errata: ELFCLASS64)
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast

I'd like to be able to use LD_PRELOAD to force the use of my system libraries, I'm just not sure of which libraries i have to include, could you help me out?

I'm currently using an up to date Debian Stretch system (64bit)

**Comment by Oxalin** [comment]
@rekotc According to your log, it seems you are missing the 32bit libraries (mesa / drm) or the path to where they are installed is not propagated correctly. On the other hand, the 64bit libraries are found, but they can't be used by Steam (which is running as a 32bit application).

Steam looks for the 32bit libraries to be able to run, while your games may run in 32 or 64bit. Both set of libraries must be installed.

**Comment by rekotc** [comment]
@Oxalin yes, you were right, the path wasnt' detected correcly, just in case somebody else has a similar problem, the needed package for debian is libgl1-mesa-dri:i386, this package will install the drivers r600_dri.so and swrast_dri.so in usr/lib/i386-linux-gnu/dri, but steam searches for them in /usr/lib32/dri/, so i had to add a symbolic link to these 2 files:

    sudo ln -s /usr/lib/i386-linux-gnu/dri/r600_dri.so /usr/lib32/dri/r600_dri.so

and the same thing for the swrast_dri.so driver.

After that i deleted all the occurrences of the 32bit libstdc++.so.6 libraries, since steam provides an older version of those and i didnt' need them, and after that the client started successfully! :)

thanks

**Comment by etonbears** [comment]
The whole point about the Steam Runtime is that is provides a known target for games to be compiled against, even if that target varies from game to game.

Somehow Steam needs to provide each game with its expected target, as well as ensuring that Steam itself also runs within the environment a distribution makes available.

I don't think that randomly removing libraries or pre-loading is going to help much, as even if it fixes the Steam client it is likely to make some games fail.

For example, Ubuntu distributions are moving to version 4.2 kernels and version 3.6 LLVM for the 15.10 release which causes Steam to fail as described in this bug if using the radeon driver.

You can fix it with LD_PRELOAD , but then games like CivV get the wrong ABI and crash/burn horribly. Like this...

>ERROR: ld.so: object '/home/roger/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>ERROR: ld.so: object '/home/roger/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>/media/roger/512GB_Data_Disk/SteamLibraryLinux/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv120__si_class_type_infoE' has different size in shared object, consider re-linking
>/media/roger/512GB_Data_Disk/SteamLibraryLinux/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv117__class_type_infoE' has different size in shared object, consider re-linking
>/media/roger/512GB_Data_Disk/SteamLibraryLinux/steamapps/common/Sid Meier's Civilization V/./Civ5XP: Symbol `_ZTVN10__cxxabiv121__vmi_class_type_infoE' has different size in shared object, consider re-linking
>Segmentation fault (core dumped)

You can run Civ V outside of the Steam environment but not surprisingly, as the binary is then even further from the comfort zone of its compile environment, a whole load of other failures occur ( although at least it doesn't SEGFAULT ).

With the way Linux userland is structured and the rapid iteration of library versions, it's not clear to me if it is even plausible to consider this to be a "problem" that Valve can "fix".

**Comment by mmstick** [comment]
@etonbears The issue is actually very simple to solve, and much of what you state is a problem isn't actually a problem at all. All we need is for Steam to not try to force mesa to use their copy of GCC libs. Games can use whatever version of GCC libs they want, but never should an application force your graphics driver to use a different lib than the system lib. I suspect that closed source drivers get around this because they are compiled statically, and hence Steam cannot interfere with it's built-in libraries.

GCC itself isn't even much of a problem because these libraries are very much forward compatible. The only time you need to worry about an ABI bump is between major releases, like from GCC 3 to GCC 4, or GCC4 to GCC5. Valve could even just provide GCC libs as soon as they are released just to keep open source graphics drivers happy.

In any case, I have absolutely no issues running any games on my Gentoo systems with the radeonsi drivers after following the Arch Wiki's guide on fixing the Steam runtime, and that's with Mesa 11 compiled against LLVM 3.7 with GCC 5.2.

    find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -print -delete

**Comment by sylware** [comment]
On Wed, Oct 28, 2015 at 02:59:24AM -0700, Michael Murphy wrote:
> @etonbears The issue is actually very simple to solve, and much of what you
> state is a problem isn't actually a problem at all. All we need is for Steam
> to not try to force mesa to use their copy of GCC libs. Games can use
> whatever version of GCC libs they want, but never should an application force
> your graphics driver to use a different lib than the system lib. I suspect
> that closed source drivers get around this because they are compiled
> statically, and hence Steam cannot interfere with it's built-in libraries.

Valve must modify its runtime: static libgcc and static libstdc++, namely only
*.a, no *.so for those. Basic ELF support and that's it (care not to depend on
crazy complex ELF sections).

On Wed, Oct 28, 2015 at 02:59:24AM -0700, Michael Murphy wrote:
> GCC itself isn't even much of a problem because these libraries are very much
> forward compatible. The only time you need to worry about an ABI bump is
> between major releases, like from GCC 3 to GCC 4, or GCC4 to GCC5. Valve
> could even just provide GCC libs as soon as they are released just to keep
> open source graphics drivers happy.

c++ ABI is hell on earth... nothing new here. gcc 4.7 is the last "clean" gcc, the
others are to be avoided, or bootstraped with gcc4.7 since it's the last gcc
C-compilable.

**Comment by etonbears** [comment]
@mmstick 
It's not a "problem" but you do "solve" it? My understanding of the English language obviously needs some attention.

You have taken the path of removing libraries from the Steam Runtime, and that works for your games. I'm very happy for you. I suspect it will cause problems for some other games you don't have because you have altered the test environment; forward compatibility is rarely perfect.

These sorts of work-around solutions are fine for individuals that understand the workings of operating systems, but the average Steam gamer trying to use Linux will not. Take a look at some of the Steam fora if you want an indication of how little grasp most of them have of technology.

Undoubtedly everything will continue to work well on SteamOS, but it would be helpful if it also worked well on Ubuntu ( and by extension its derivatives ) since it is the distribution Valve recommend.

**Comment by mmstick** [comment]
@etonbears It's better to have some games work than none at all without the fix.

**Comment by battlesnake** [comment]
Agree with @mmstick , having just dealt with this bug myself.  Mostly working games > all broken games.

**Comment by sylware** [comment]
On Tue, Nov 03, 2015 at 04:29:26PM -0800, Mark K Cowan wrote:
> Agree with @mmstick , having just dealt with this bug myself.  Mostly working games > all broken games.  

This is not a bug: c++ ABI and libgcc are broken by design. c++ is broken in
itself anyway (I think Linus T. is right and more) and a shared libgcc *in gcc* is such
a bad idea. libgcc should be external to gcc project with a stable ELF ABI.
gcc should have stayed reasonably bootstrapable using plain C that you cannot anymore on
ARM64 (no ARM64 backend in gcc 4.7, the last "plain C boostrapable" gcc).

The real "fix": eat the bullet-->steam sdk with static libstdc++ and static
libgcc, stick to "simple" ELF sections... then ask the game devs to recompile
(ouch ouch ouch!)

Real culprit: the "open source" guys with proper resources to work properly on
compilers (mainly google and intel I guess).

**Comment by battlesnake** [comment]
@sylware:

`This is not a bug`

I beg to differ:

Games working before LD_PRELOAD hack: `0`
Games working after LD_PRELOAD hack: `at least 5, none broken so far`

**Comment by sylware** [comment]
On Wed, Nov 04, 2015 at 03:01:34AM -0800, Mark K Cowan wrote:
> @sylware:
> 
> `This is not a bug`
> 
> I beg to differ:
> 
> Games working before LD_PRELOAD hack: `0`
> Games working after LD_PRELOAD hack: `at least 5, none broken so far`

'broken by design' is way worse than a bug.

**Comment by battlesnake** [comment]
> 'broken by design' is way worse than a bug.

@sylware: That goes for the steam client too.

**Comment by sylware** [comment]
On Wed, Nov 04, 2015 at 03:52:28AM -0800, Mark K Cowan wrote:
> > 'broken by design' is way worse than a bug.
> 
> @sylware: That goes for the steam client too.

Well, as I said, the real culprits are the "open source" guys who have the
proper resources to work on gcc. My guess they are corporate salary men and
they try to perform developer lock-in by open source complexity.

**Comment by battlesnake** [comment]
> My guess they are corporate salary men and they try to perform developer lock-in by open source complexity.

Jet fuel can't melt steel beams! :trollface:

**Comment by mmstick** [comment]
@sylware There's nothing wrong with the 'open source' guys because this issue has been discussed plenty of times about how easy it is to solve this if Valve would do it. Valve needs to stop trying to override system libraries, especially libstdc++ and libgcc, because this breaks Mesa and DRI unless they are built statically. VMWare solved this exact problem just by putting each library into its own directory and only adding the necessary directories to $LD_LIBRARY_PATH.

The other option is telling everyone to go back and recompile their games with those two libraries being compiled statically into the game itself. I don't even see why Valve is shipping these two libraries in their runtime anyway because that in itself is a terrible idea unless you are are wanting to issue security updates to your C++ runtimes regularly, which Valve doesn't seem to be doing at all with their frozen runtimes, which defeats the purpose entirely.

http://patchwork.freedesktop.org/patch/44437/

**Comment by sylware** [comment]
I was talking about the "open source" guys from gcc, not all of them. I'm one
of the other open source guys, and as one of them, I would try never to
become hard dependent on gcc, ever ever ever ever (Their c++ move killed them
in my heart).

Common sense and sanity dictate binary software needs minimal simple stable
system ABI over time (i.e. no c++ toolchain dependent ABI) and everything
"above" this ABI should be "packaged" into the binaries to avoid, as much as
possible, bad interferences with the system. Share libs are a fail to "package"
nasty libs like ultra complex ABI and toolchain dependent libstdc++ and
toolchain dependent libgcc with 0 interference. Then in the SDK, just make them
static and we are done... till the next interference.

The minimal simple ABI for games should be something like that:
 - sound: SDL2->libpulse (ouch... since pulse ABI is a moving target) and
   libasound (way more ABI stable but missing out of the box software mixer)
   shared libs.
 - GFX/3D: SDL2 on vulkan/(egl/glx/wayland?)opengl/d3d libs (opengl'S' are a
   bloody ABI mess... lot of hope in vulkan...)
 - application system ABI(ELF): "libdl" to load the previous system libs with
   their system dependencies in game processes.

Everything else should be static. Even SDL2, and I would even consider the ELF
loader as static, to sort of "freeze" ELF.

**Comment by mmstick** [comment]
Can we please at least have the steam.desktop application patched so that it says

```
Exec=env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1' /usr/bin/steam %U
```

Instead of

```
Exec=/usr/bin/steam %U
```

Even better is to just have a very simple, very convenient few lines of code in the Steam launch script to execute this one little `LD_PRELOAD` line when open source drivers are detected. This is still a serious problem in 2016.

**Comment by sylware** [comment]
On Sat, Apr 02, 2016 at 10:53:47AM -0700, Michael Murphy wrote:
> Can we please at least have the steam.desktop application patched so that it says
> 
> ```
> Exec=env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1' /usr/bin/steam %U

It's deeper than that. You will have troubles with X libs pulling c++ stuff
from mesa (last time I checked, namely a long time ago).

The real issue is c++ and libgcc in themself: the c++ ABI is just compiler
specific (and an insane nightmare) and libgcc_s is weird.

Steam SDK should contain static libstdc++ and static libgcc in order to
minimize the side-effects with the various gnu/linux based OSes out there.
(that seems the real fix to this issue).

Don't forget that interop moto is to keep interfaces hardcore simple, thus
basic ELF ABI.

-- 
Sylvain

**Comment by DoctorJellyface** [comment]
But can you override `LD_PRELOAD` as @mmstick said if the user force disables the runtime with `STEAM_RUNTIME=0`? I think it would be the best solution/work-around right now and would stop users having to apply all these crazy [hacks](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Work_arounds).

**Comment by mmstick** [comment]
Recent changes to the Steam runtime now requires a new LD_PRELOAD hack, due to an issue with *libgpg-error*.

```
env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam %U
```

**Comment by mmstick** [comment]
@DoctorJellyface The fix would actually be much easier than this. Just apply a few lines of shell to the steam.sh script and you're good to go. The fix could be as simple as the following:

```sh
if [ "$(glxinfo | grep Mesa) ]; then
    LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@"
else
    exec "$LAUNCHSTEAMDIR/$STEAMBOOTSTRAP" "$@"
fi
```

**Comment by tfhavingfun** [comment]
@mmstick You just provided Valve with the easiest fix. So thanks. Let's hope they listen.

**Comment by evhfiftyone50** [comment]
@tfhavingfun Could you please elaborate where you put the code into steam.sh? The way I have tried it still resulted in the same error. But then again I am quite new to this and probably messed something up.
Thanks!

**Comment by pavlos256** [comment]
@evhfiftyone50 What I did was create a tiny shell script and start steam with it:

```bash
#!/bin/bash
env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam %U
```

**Comment by tfhavingfun** [comment]
@evhfiftyone50 I don't recommend editing steam.sh directly. Instead just create a shell script and use a custom desktop file for Steam with which you can then refer to the shell script. That way you can just click the Steam icon (be it on your Desktop or Dash/Dock) to start it as you would normally do. Here is a video I made demonstrating how to do that: [https://www.youtube.com/watch?v=gdM1S39mjgY](https://www.youtube.com/watch?v=gdM1S39mjgY)

**Comment by HarlemSquirrel** [comment]
I made a desktop file I made by copying the original desktop file and modifying `Name` and  `EXEC` to use  the line from @pavlos256 
```
cp /usr/share/applications/steam.desktop ~/.local/share/applications/steam-preload-libs.desktop.desktop
```

```
Name=Steam (preload libs)
Exec=env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /usr/bin/steam %U
```

I also made it executable and refreshed my GNOME desktop so I could find it and click on it. 
```
chmod +x /home/hs/.local/share/applications/steam-preload-libs.desktop.desktop
```

**Comment by zygimantus** [comment]
In ArchLinux the solution for me was: `rm ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/lib*`

**Comment by Swyter** [comment]
_Arch Linux_ now has a [`steam-native-runtime` meta-package in the _Community/Multilib_ repository](https://www.archlinux.org/packages/multilib/x86_64/steam-native-runtime/) with all the needed Steam dependencies. So this shouldn't be a problem any longer.

> https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Native_runtime

Just install that and launch `steam-native` instead of `steam`.

Boom! You are done, no more deletions.

**Comment by sylware** [comment]
Just updated my custom gnu/linux distro.

32 bits libs are a massive pain to build/setup, since you *must* use a multi-lib gcc.
It's not reasonable to try to split cleanly 32 bits and 64 bits infrastructures.

I do really think, it's time to provide a clean 64 bits client on gnu/linux.
(big picture?)

I can try to help (I'm humble), even though I'm an open source fan and c++
hater (for very good reasons). I'm currently available.

**Comment by jv-p** [comment]
# `pacman -S steam-native-runtime`
(just run it...)

**Comment by LotosikRa** [comment]
@Swyter How to install this kind of package?

**Comment by mikefaille** [comment]
@LotosikRa In wish Linux Distro ?

**Comment by LotosikRa** [comment]
@mikefaille Ubuntu 16.10

**Comment by mikefaille** [comment]
@LotosikRa You don't need this on Ubuntu. You already have "steam native" libs where native platform = Ubuntu/Debian. Just install steam  [using this link](apt://steam)

**Comment by LotosikRa** [comment]
@mikefaille Did You mean that Ubuntu's `steam` package have all what I need? What does 

> Just install steam apt://steam

mean?

**Comment by mikefaille** [comment]
@LotosikRa 
My bad, just check my edited post.

**Comment by mmstick** [comment]
You'll still have the same problem with the steam runtime because Ubuntu is not actually an officially supported platform, even though it is claimed to be officially supported. You will need to apply the same fixes as other distributions to get working drivers in Steam games for Ubuntu 16.10. The same solution for Arch Linux applies to Ubuntu -- deleting the conflicting libs. I'm not aware of any PPAs providing a native runtime for Ubuntu.
