### ISSUE TITLE
Setup script pins older libraries from steam runtime

### ISSUE THREAD

**Issue by pchome** [ValveSoftware/steam-runtime#173]
I have system `/usr/lib/libGLU.so.1.3.1` however `libGLU.so.1.3.08004` "pinned" in `steam-runtime/pinned_libs_*/`.

I don't dived deeply into the setup script logic, but the issue seems [there](https://github.com/ValveSoftware/steam-runtime/blob/master/templates/setup.sh#L109).
> \# This pattern strips leading zeroes, which could otherwise cause bash to interpret the value as binary/octal below

If leading zeroes were stripped, then `1.3.1` and `1.3.8004` was compared. So up to version `1.3.8` will be affected.

_Possible solution could be to append zeroes, if one of compared parts contains less digits than other. E.g. compare `1.3.10000` and `1.3.08004`, which should be `... 10000 -lt 8004 ]]...` after stripping._

**Comment by kisak-valve** [comment]
Hello @pchome, out of mild curiosity, has this behavior caused a functional problem that was worked around by manually unpinning the library?

**Comment by pchome** [comment]
No problems was observed. I keeping this one pinned.
Also there is no other libs in `steam-runtime/` using such version numbering, so only `libGLU.so` currently affected.

**Comment by smcv** [comment]
> I have system `/usr/lib/libGLU.so.1.3.1` however `libGLU.so.1.3.08004` "pinned" in `steam-runtime/pinned_libs_*/`.

Ideally the setup script should use the same order `ldconfig` does, because the longer version numbers on libraries are mainly there so that `ldconfig` will do the right thing.

In this case either `libGLU.so.1.3.1` is older, or the author of libGLU has misunderstood the order that `ldconfig` would use (probably the latter). If I do

```
cp /lib/x86_64-linux-gnu/libz.so.1.2.11 lib/libz.so.1.3.1
cp /lib/x86_64-linux-gnu/libz.so.1.2.11 lib/libz.so.1.3.08004
ldconfig -v -n lib/
```

then `ldconfig` makes `lib/libz.so.1` point to `lib/libz.so.1.3.08004`. So I think `setup.sh` is doing the right thing here, but the Steam Runtime's bundled libGLU is not...

(But libGLU basically hasn't changed for years, so choosing the wrong one is unlikely to have any practical impact.)

**Comment by imaami** [comment]
> _Possible solution could be to append zeroes, if one of compared parts contains less digits than other. E.g. compare `1.3.10000` and `1.3.08004`, which should be `... 10000 -lt 8004 ]]...` after stripping._

This would break pretty much every library version comparison _except_ for a handful of incorrectly versioned libraries, such as libGLU here. Library versions aren't like decimal numbers, e.g., `0.0.9` is less than `0.0.21` because `9` and `21` aren't fractional parts.

If you blindly append zeroes to whichever number has fewer digits, you're simply converting every example to a comparison between fractional parts. `9 < 21` is correct, but `0.9 < 0.21` and `90 < 21` are both false in the exact same way.

If some libraries treat version number separators as if they're decimal points, then there is no arithmetically unambiguous way to sort every possible version string. It's possible to make assumptions, yes, but nothing is going to fix it for good.

What I think would work best is brute force, plain and simple. There's a finite number of libraries in the Steam runtime, ditto for Linux distributions' package archives combined. The number of incorrectly-versioned libraries is likely small, and it's fairly easy to just make a list of all _known_ bad releases. Have this "blacklist" be the very first filter in the version checking function, perhaps followed by some guesswork (e.g., leading zeroes in a library version is more likely to mean fraction rather than octal), and the last stage would be a simple greater-than check with stripped numbers.

Not perfect, but such is life.
