### ISSUE TITLE
runtime xcb libs still misses the dri modifier symbol

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#178]

**Comment by sylware** [comment]
If the steam runtime xcb libs are used instead of the ones from my system, libGL (from my system) which is statically loaded by the steam client will fail to dynamically  link and will "crash".
Could you update the steam runtime xcb libs build in order to include the missing symbols ("modifier" related to dri3)?

**Comment by kisak-valve** [comment]
Hello @sylware, even though the steam runtime variant of libxcb is dated, this isn't a functional issue for all sane distro installs since the library pinning logic was extended to the bootstrapper environment in the 1.0.0.55 steam package.

Given that you're experiencing an issue with this library as a side effect of https://github.com/ValveSoftware/steam-for-linux/issues/5455 and any major distro is no longer affected by default, I don't see any value in investigating this separately from your previous issue report.

Closing as won't fix.

**Comment by sylware** [comment]
So what's the point in distributing it??
