### ISSUE TITLE
gcc -static-libgcc and -static-libstdc++

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#179]

**Comment by sylware** [comment]
the runtime should provide shared libgcc_s and libstdc++ only for legacy games. The game devs, when building for the steam runtime, should be warn to use gcc -static-libgcc and -static-libstdc++.
That to avoid ABI madness between the steam-runtime ones and host ones (if any).

**Comment by TTimo** [comment]
The scout runtime is backwards compatible back to it's initial release and will continue to include to include these libraries.

In order to produce binaries compatible with Steam for Linux, game developers need to compile with the scout SDK (either via docker or chroot). We realize that it is often not the case and developers tend to compile on whatever Linux host they have at hand, we are working on addressing this in the future.

**Comment by sylware** [comment]
Ofc, those libraries have to be around for lecacy support!
I was more focused on devs compiling against the steam runtime: the
-static-libgcc and -static-libstdc++ should be enabled by default.
