### ISSUE TITLE
setup_chroot.sh dpkg error

### ISSUE THREAD

**Issue by noncopyable** [ValveSoftware/steam-runtime#180]
I am on fedora 30 and i am getting these errors running setup_chroot.sh
first i had to comment out the line 39:
 `#sudo -E apt-get install -y debootstrap schroot`

and installed these packages manually, everything was going ok until the last function:
`build_chroot` around:
`schroot --chroot ${CHROOT_NAME} -d /tmp --user root -- "/tmp/${TMPNAME}" --chroot "$@"`

which ended up with the error:
`dpkg: unrecoverable fatal error, aborting:
 syntax error: unknown group 'crontab' in statoverride file
E: Sub-process /usr/bin/dpkg returned an error code (2)`

`cat /var/chroots/steamrt_scout_amd64/var/lib/dpkg/statoverride`
`root crontab 2755 /usr/bin/crontab`

Assuming these scripts are not debian/ubuntu only, what am i doing wrong? :)

Thank you!

**Comment by TTimo** [comment]
It may be easier to get a ready made sysroot image from http://repo.steampowered.com/steamrt-images-scout/snapshots/0.20190913.0/

I think http://repo.steampowered.com/steamrt-images-scout/snapshots/0.20190913.0/com.valvesoftware.SteamRuntime.Sdk-amd64,i386-scout-sysroot.tar.gz would be the one you need.

That way you don't need to build the chroot yourself. It is likely those scripts do require a debian/ubuntu system.

Nowadays we recommend using docker, the `setup_docker.sh` script should be more distribution agnostic. You could also try that.

**Comment by noncopyable** [comment]
Hello @TTimo,

Thanks for the quick reply!

i was just trying setup_docker.sh, and got another dpkg related error:
`dpkg (subprocess): cannot set security execution context for maintainer script: No such file or directory
dpkg: error processing package dpkg (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 dpkg
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Now i am going to try prebuilt images.
Thank you!

**Comment by smcv** [comment]
`schroot` assumes the host system and the container are mostly compatible (and in particular that their `/etc/passwd` and `/etc/group` are broadly compatible), which is OK between different Debian derivatives like Debian, Ubuntu and the Steam Runtime, but becomes a problematic assumption when running a Steam Runtime chroot on a non-Debian-derived host system.

For the chroot setup, I think the medium/long term solution is that we should encourage developers to download a prebuilt sysroot and use a command like:

```
./setup_chroot.sh --tarball /path/to/com.valvesoftware.SteamRuntime.Sdk-amd64,i386-scout-sysroot.tar.gz --amd64
```

or for 32-bit games, download the 32-bit-only sysroot and use

```
./setup_chroot.sh --tarball /path/to/com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz --i386
```

That skips a lot of the steps that could go wrong on developers' arbitrary host systems, because those steps were already done in a known-good environment on our CI infrastructure, so it should be rather more reliable. The process we use to build those sysroots deliberately avoids having files owned by users/groups that don't match the host system.

Similarly, for the Docker container, we should probably be recommending importing that sysroot tarball, instead of reinventing it by converting an Ubuntu 12.04 image - that way there are a lot fewer things that can go wrong, and as a bonus the resulting container will be a "purer" SteamRT environment, with fewer packages from Ubuntu 12.04.

We actually do already publish a simple Dockerfile alongside each sysroot tarball, e.g. <http://repo.steampowered.com/steamrt-images-scout/snapshots/0.20190913.0/com.valvesoftware.SteamRuntime.Sdk-amd64,i386-scout-sysroot.Dockerfile>, but the documentation and scripts aren't fully "joined up" yet.

One important difference between the locally-built schroot environment that we've traditionally recommended, and the prebuilt sysroot, is that the prebuilt one currently has "[merged /usr](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/)". This should be fine for standalone games, but could be awkward if you're building local Debian-format packages to install into it, because the version of debhelper we have in scout is missing some later fixes for dealing with merged-/usr systems. At some point we should either make the sysroot use the traditional "separate /usr" layout, or backport the debhelper fixes (I have a branch somewhere for the latter).

**Comment by smcv** [comment]
> dpkg (subprocess): cannot set security execution context for maintainer script: No such file or directory

I think this is because Fedora uses SELinux, and dpkg detects that SELinux is in use and tries to set up the right SELinux contexts for the files it's installing, but Docker doesn't pass through enough SELinux filesystems for that to actually work.

**Comment by noncopyable** [comment]
Yesterday i was able to compile with prebuilt sysroot images, thanks for the help @TTimo and @smcv
