### ISSUE TITLE
workshop content doens't load with PRESSURE_VESSEL_SHARE_HOME=0

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#217]
Tested with Everlasting Summer.

**Comment by smcv** [comment]
This is hopefully fixed in a newer pressure-vessel version. Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by soredake** [comment]
Works now, thanks!
