### ISSUE TITLE
Useless documentation in inner ubuntu layer

### ISSUE THREAD

**Issue by MatteoRagni** [ValveSoftware/steam-runtime#220]
#### Your system informations

This is not important, is not really an issue.

#### Please describe your issue in as much detail as possible:
 It seems that steam-runtime is using some sort of chrooted ubuntu versions. But inside the directory structure (both for 32 and 64bit versions)  there are a copied version of `/usr/share/doc` and they are useless.

I suggest to remove them in future (it will reduce also update size).

Hope the suggestion will be took in consideration. Thank you.

**Comment by smcv** [comment]
Since the original issue was opened, the size of the documentation was already reduced by 50% by combining the amd64 and i386 parts of the Steam Runtime. Some of the documentation in the Steam Runtime needs to be there for legal reasons (some licenses require the information in the `copyright`, `changelog.gz` and `changelog.Debian.gz` files to be kept) so it can't all go away.

A lot of the rest could probably be removed, but its size is relatively insignificant when compared with games (about 32M, which is for example approximately 1% of Half-Life 2 or 0.1% of The Witcher 3) so it isn't a high priority.

One bit of "low-hanging fruit" would be to remove most of the documentation from `usr/share/doc/nvidia-cg-toolkit` (15M), or remove that developer-facing package entirely (#77).

**Comment by MatteoRagni** [comment]
Thank you for sharing the great news!
