### ISSUE TITLE
Cannot use PRESSURE_VESSEL_WRAP_GUI=1 or STEAM_RUNTIME_CONTAINER_TEST=1 with non steam games

### ISSUE THREAD

**Issue by kadogo** [ValveSoftware/steam-runtime#228]
Hello, 

I tried to use the test dialog with non steam games and the dialog is not displayed.
It's well displayed for the steam games

If i need to make few test let me know.

**Comment by smcv** [comment]
pressure-vessel is unlikely to work with non-Steam games, because the non-Steam game expects to be run on your host system (Ubuntu 18.04 or Debian 10 or whatever else you are using), and the Steam Runtime container doesn't match that environment. In particular, if the non-Steam game is in `/usr`, then it won't exist inside the container.

**Comment by kadogo** [comment]
Hello @smcv 

I'm using Debian 10 but  the games are like "self extractable", I did the test with Dead Cells of GOG (the game itself was in my home).

I think it could be a great feature for later, maybe it could have a kind of way to "link" the game directory so that it can be found in the runtime container?

**Comment by smcv** [comment]
It's a reasonable feature request, but not a high priority right now.

Steam doesn't know much about a non-Steam game (it knows a command-line to run on the host system, but nothing more than that, and certainly not which directory or directories belong to the game) so the UI for making a non-Steam game work in pressure-vessel is probably never going to be particularly graceful.

**Comment by kadogo** [comment]
I tried to buid the steam-runtime manually to see how it worked and when I use the run.sh after I build with `./build-runtime.py --output=$(pwd)/runtime` my game (Dead Cells) work but maybe I'm missing something.

**Comment by smcv** [comment]
The ordinary Steam Runtime (used for the Steam client itself and for Steam games, but not for non-Steam games) is not the same as the experimental container runtime that uses pressure-vessel (SteamLinuxRuntime). There are more details in `doc/` in this repository, or in the video of <https://fosdem.org/2020/schedule/event/containers_steam/>, if you're interested.

**Comment by kadogo** [comment]
Thanks @smcv 

There are no way right now for trying to use pressure-vessel without using the SteamLinuxRuntime directly? Maybe I need to dig a little much further in the SteamLinuxRuntime directory.

**Comment by smcv** [comment]
Using pressure-vessel to run stuff in containers without going via the SteamLinuxRuntime "compatibility tool" in the Steam client UI is possible, but not straightforward, and not supported. If you report any issues, please be very, very specific about what you did, what you expected to happen, and what actually happened.

The source code in https://repo.steampowered.com/steamrt/pool/main/p/pressure-vessel/ has some (brief, technical) documentation in `README.md`. For more details, see the source code itself.

A lot of the code in pressure-vessel, and the things mentioned in `README.md`, is there so that we can experiment with things that could *potentially* happen in future, if they turn out to be reliable - just because something is there, that doesn't mean it will work. Features might change or disappear in a future release, particularly things that aren't easily available through the Steam client UI.

Good luck, and I hope it does something useful for you :-)

**Comment by kadogo** [comment]
Thanks @smcv 

I will dig into it and see if I find something usefull for non steam games, having something predictable would be so better for everyone (dev and players), but what I saw in the `doc/` and the video it's a long way to go.

Thanks to pressure-vessel it's aready step further than what we had before ^^

**Comment by kadogo** [comment]
Hello @smcv 

After few digging I think that the issue is that STEAM_RUNTIME_CONTAINER_TEST is not exported correctly for non steam games and that it's related to https://github.com/ValveSoftware/steam-for-linux/issues/6046

I did a little workaround to that will parse the command and try to export each content that look like "XXX=XXX" in run-in-scout. I don't know if you are interested by it or if it's better to wait until that https://github.com/ValveSoftware/steam-for-linux/issues/6046 is solved correctly.

**Comment by smcv** [comment]
So you can choose to force a non-Steam game to be run under the `SteamLinuxRuntime` compat tool, but you can't set environment variables by setting its launch options to `PRESSURE_VESSEL_WRAP_GUI=1 %command%` because Steam doesn't understand that syntax for non-Steam games?

If that's the case, then that's a Steam client issue, not a pressure-vessel issue.

Workaround: `PRESSURE_VESSEL_WRAP_GUI=1 steam` will launch the test-UI for *every* game that is using the `SteamLinuxRuntime` compat tool.

**Comment by kadogo** [comment]
Exactly, so for now I make the export une run-in-scout but it's clearly not the solution. I will wait until the bug i steam-client is solved.

I think this issue may be closed if it's good for you.

**Comment by smcv** [comment]
> you can choose to force a non-Steam game to be run under the `SteamLinuxRuntime` compat tool, but you can't set environment variables by setting its launch options to `PRESSURE_VESSEL_WRAP_GUI=1 %command%` because Steam doesn't understand that syntax for non-Steam games

This was https://github.com/ValveSoftware/steam-for-linux/issues/6046, and was fixed in the 2022-03-31 version of Steam.

@kisak-valve or @kadogo, please could you close this issue?
