### ISSUE TITLE
life is strange does not run with SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#232]
[log.txt](https://github.com/ValveSoftware/steam-runtime/files/4237175/log.txt)

**Comment by kisak-valve** [comment]
Hello @soredake, please confirm that this issue is with the Steam Linux Runtime compatibility tool. My understanding is that Wayland is not supported by pressure vessel + Scout.

**Comment by soredake** [comment]
Yes, it's issue with SLR tool.

**Comment by smcv** [comment]
> My understanding is that Wayland is not supported by pressure vessel + Scout.

Yes. scout is based on a version of Ubuntu from 2012, and back in 2012 Wayland was not mature at all. Libraries in scout (like SDL) are generally not compiled with Wayland support enabled, because the version of Wayland that's available in scout is too old to be useful.

Without SteamLinuxRuntime/pressure-vessel, you're getting most shared libraries from your host system, which means you might accidentally get native Wayland support, but things also might randomly break over time. The container environment is much more strict about getting as much as possible from the container, so it's a predictable environment, but it's predictably stuck in 2012.

We should maybe force the X11 video driver when running in the container, because nothing else is likely to work in practice.

Does this game work with SDL_VIDEODRIVER=wayland when running without using SteamLinuxRuntime/pressure-vessel?

Does this game work in SteamLinuxRuntime/pressure-vessel without forcing the Wayland video driver? (It does for me, but my system isn't the same as yours.)

**Comment by smcv** [comment]
```
[0221/190300:FATAL:memory_linux.cc(42)] Out of memory, size = 21474836480
```

Something is trying to allocate a nonsense amount of memory (2**32 * 10 bytes). Probably some function returned a negative number to indicate an error, and whatever code was calling it didn't handle the error and just carried on.

**Comment by soredake** [comment]
>Does this game work with SDL_VIDEODRIVER=wayland when running without using SteamLinuxRuntime/pressure-vessel?

Yes.

>Does this game work in SteamLinuxRuntime/pressure-vessel without forcing the Wayland video driver? (It does for me, but my system isn't the same as yours.)

Yes.

**Comment by soredake** [comment]
> ```
> [0221/190300:FATAL:memory_linux.cc(42)] Out of memory, size = 21474836480
> ```
> 
> Something is trying to allocate a nonsense amount of memory (2**32 * 10 bytes). Probably some function returned a negative number to indicate an error, and whatever code was calling it didn't handle the error and just carried on.

can be related https://github.com/ValveSoftware/steam-for-linux/issues/4954

**Comment by smcv** [comment]
> can be related ValveSoftware/steam-for-linux#4954

Yes, it's essentially the same issue. The container runtime is a more strict Steam Runtime environment than the traditional `LD_LIBRARY_PATH` runtime, which means that when it works, it's more predictable (should work the same for more people, and continue to work for longer); but when it doesn't work, a lot of the workarounds and hacks that have traditionally existed aren't available.

**Comment by soredake** [comment]
As of now, game runs with `SDL_VIDEODRIVER=wayland`, so i'll close this.
