### ISSUE TITLE
Torchlight 2 [GOG DRM Free version] missing textures

### ISSUE THREAD

**Issue by 4ifi** [ValveSoftware/steam-runtime#266]
#### Your system information
Steam client version is latest beta
* Steam Runtime Version: 
Latest beta
* Distribution (e.g. Ubuntu 18.04): 
Devuan ceres server x86_64 with manually installed xorg and i3wm and alsa and mesa 3d
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
[system_info.txt](https://github.com/ValveSoftware/steam-runtime/files/4826345/system_info.txt)
https://gist.github.com/4ifi/5d385264f64ca0021cb9d9c6b432a271
* Have you checked for system updates?: [Yes/No]
Yes, I update my system every day and my distribution uses unstable repository
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:

I collected this log before joining beta but beta didn't fix anything and didn't change anything.
[steam_log.txt](https://github.com/ValveSoftware/steam-runtime/files/4826374/steam_log.txt)
https://gist.github.com/4ifi/daedafe4f771ae3bd2119210af8d778f

#### Steps for reproducing this issue:
Missing textures but not missing when in pause menu
Proofs here:
![20200625_002635](https://user-images.githubusercontent.com/12215530/85584964-f45d9980-b682-11ea-9fe2-d73e36147b43.png)
![20200625_002659](https://user-images.githubusercontent.com/12215530/85584979-f6bff380-b682-11ea-9078-6c75c70e9a5c.png)
![20200625_002706](https://user-images.githubusercontent.com/12215530/85584988-f9224d80-b682-11ea-811e-5808f155fba8.png)

**Comment by kisak-valve** [comment]
Hello @4ifi, in general, third party games packaged for another storefront are not intended to be used with the Steam Linux Runtime container. That said, I'm going to tentatively leave this open due to how well you've written this report. Most likely a video driver issue that should be reported to your video driver vendor.

**Comment by smcv** [comment]
As @kisak-valve said, the Steam Linux Runtime is designed for games that were specifically compiled for the Steam Runtime environment. Games that were bought or downloaded elsewhere (such as GOG) are likely to be targeting a different runtime environment.

If you want to launch those games through Steam, use the "Add non-Steam game" option but do not enable the SteamLinuxRuntime compat tool.

**Comment by JohannPopper** [comment]
This problem has nothing to do with Steam. You'll find that running the game as intended on your system -- installed via the GOG mojosetup .sh & running right from your DE's apps menu -- will result in the same problem. This happens on vanilla Fedora 32 for many people, and up till now it was not known that it also occurs on Devuan. Common denominator points could be graphics driver or some other setting in the kernel version you are using. The problem does not occur on any current Ubuntu-based distros AFAIK from reading bug reports. Nobody has figured out the cause, fix, or workaround yet, or if they have, they haven't shared. I made numerous comparisons between Fedora defaults and 'buntu's myself and reconfigured many settings searching for the answer and I failed. Good luck. 

IMHO this thread should be closed here and 4ifi should repost on a Torchlight 2 specific help forum or talk to Linux devs for his graphics card or distro to figure out what distro-specific configuration settings are causing a graphical difference between otherwise version-identical or very similar software stacks (such as was the case between Fedora 32 and Ubuntu 20.04, whether Wayland & Xorg).

**Comment by 4ifi** [comment]
@JohannPopper @smcv It's impossible to run game without steam runtime because my distro uses unstable GCC libraries. I use latest unstable drivers and software because it has more features. And IDK why intel hd graphics has bugs in torchlight 2. Steam runtime helped me to fix games I couldn't run because of ustable latest software. They are plague inc, deponia 3/4. In my opinion steam runtime is a container with prepared libraries which helps to run any linux game on every distribution.

**Comment by 4ifi** [comment]
@JohannPopper @smcv @kisak-valve Fixed by updating linux kernel!!!!
