### ISSUE TITLE
No audio in Metro Last Light Redux (287390)

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-runtime#267]
Steam Runtime Version: 0.20200604.0
Distribution: Fedora 32 (64 bit)
Link to your full system information: https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329/6703e5131451674221d74d71bdd0d9d543275cf3
Have you checked for system updates?: [Yes]
Are you using the Steam Linux Runtime compatibility tool?: [Yes]

**Comment by DanMan** [comment]
Still happening with runtime version 0.20200720.0. This is an excerpt when running Steam from the CLI and launching the game:

> [0723/215036.728647:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
> ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave

**Comment by smcv** [comment]
This might be fixed in pressure-vessel 0.20210317.0 (it soulds like the same issue as part of #371, https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/65). Please could you retry with a current version of the Steam Linux Runtime?

You should find that `SteamLinuxRuntime/VERSIONS.txt` says `pressure-vessel 0.20210317.0` or later (this is already in the main branch, you shouldn't need to opt-in to a beta for this).

**Comment by DanMan** [comment]
`…/steamapps/common/SteamLinuxRuntime/VERSIONS.txt` says

    pressure-vessel 0.20210430.0+srt1       scout   0.20210503.0    # pressure-vessel-bin.tar.gz

and audio appears to work now in both M:LL and W40k:Mechanicus. 👍

**Comment by kisak-valve** [comment]
Thanks for retesting @DanMan, closing as fixed.
