### ISSUE TITLE
Don't Starve Together (322330): No audio

### ISSUE THREAD

**Issue by Newbytee** [ValveSoftware/steam-runtime#277]
#### Your system information

* Steam Runtime Version: 
* Distribution (e.g. Ubuntu 18.04): Fedora 32
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  https://gist.github.com/Newbytee/f8bdebb6701207cd84ce071f6ce17390
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

[pressure-vessel.log](https://github.com/ValveSoftware/steam-runtime/files/5391104/pressure-vessel.log)

To be clear, I do get audio when running the game "normally".

#### Steps for reproducing this issue:

1. Launch Don't Starve Together in Pressure Vessel
2. Ensure that volume is turned up in game
3. Hear no audio anyway

**Comment by smcv** [comment]
Just a guess, but this *might* be fixed in pressure-vessel 0.20210317.0 (it could be the same issue as part of #371, https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/65). Please could you retry with a current version of the Steam Linux Runtime?

You should find that `SteamLinuxRuntime/VERSIONS.txt` says `pressure-vessel 0.20210317.0` or later (this is already in the main branch, you shouldn't need to opt-in to a beta for this).

**Comment by Newbytee** [comment]
Wohoo, it works! Nice job.
