### ISSUE TITLE
Pressure-vessel-launcher socket directory path too long

### ISSUE THREAD

**Issue by brauliobo** [ValveSoftware/steam-runtime#290]
# Compatibility Report
- Name of the game with compatibility issues: LEGO® Batman™ 3: Beyond Gotham
- Steam AppID of the game: 313690

## System Information
- GPU: RX 5500
- Driver/LLVM version: 20.2.1
- Kernel version: 5.9.1
- Proton version: 5.13-1

## I confirm:
- [ X ] that I haven't found an existing compatibility report for this game.
- [ X ] that I have checked whether there are updates for my system available.

## Symptom
Doesn't launch with Proton 5.13-1 but **works with 5.10-9**

## Reproduction
Try to launch game. Running `PROTON_LOG=1 steam` doesn't generate any logs

**Comment by kisak-valve** [comment]
Thanks @brauliobo, let's treat this as a Pressure Vessel issue until there's a stronger indication that the issue is elsewhere.

**Comment by kisak-valve** [comment]
Hello @jpalus, my understanding is that the repo for pressure-vessel-launcher is not currently public, but that doesn't mean you can't take a look at the code. You should be able to take a look in https://repo.steampowered.com/steamrt-images-soldier/snapshots/0.20201022.1/sources/steam-runtime-tools_0.20201022.0.tar.gz for this iteration of the tool set.

**Comment by jpalus** [comment]
@kisak-valve thanks for pointing to source!

I didn't know about this sun_path length limit, boy that's old school. However there is a very creative workaround for this which enables effectively any directory length: https://mail.openvswitch.org/pipermail/ovs-dev/2013-October/276542.html

The trick is to first open directory containing socket, record file descriptor and open socket to `/proc/self/fd/<socket dir fd>/<socket name (uuid)>`. I was convinced that using `/proc` wouldn't fly in pressure-vessel but then after quick grep turns out it already has plenty of uses.

**Comment by smcv** [comment]
> The trick is to first open directory containing socket, record file descriptor and open socket to `/proc/self/fd/<socket dir fd>/<socket name (uuid)>`

I'm honestly surprised that works, but it's an interesting trick.

At the moment, `pressure-vessel` pessimistically assumes that both the name we were asked to use, and the `realpath()` of that name, fit in the `sun_path` length limit. The interactions between symlinks and `sun_path` seem subtle enough that I'd prefer not to rely on them, particularly when we're crossing between processes, between directories, and even between views of the filesystem.

Another possible solution is to ignore `$TMPDIR` for this purpose, and always create the directory in `/tmp`, which makes sure all possible interpretations of its path are short enough (for example this is what `dbus-daemon` has always done). However, that would have to be done in Steam rather than pressure-vessel, because it's actually Steam that creates `$TMPDIR/SteamPVSockets.XXXXXX` now.

Now that we're not using `XDG_RUNTIME_DIR` for this, we can also use shorter names inside the directory without introducing ambiguity about what its purpose is, which will make the length limit less tight.

**Comment by TTimo** [comment]
Next beta (> Oct 28) will hardcode to /tmp in order to keep the paths short.

**Comment by brauliobo** [comment]
Can this be fixed sooner? 5.13 is completely unusable due to this

**Comment by brauliobo** [comment]
this was fixed to me at 5.13-2
