### ISSUE TITLE
Proton versions 5.13 and above (i.e. Proton-5.21-GE-1) won't work

### ISSUE THREAD

**Issue by temp-account-hello** [ValveSoftware/steam-runtime#320]
### **System Information:**
**Steam Runtime Version:** v0.20201124.0-2-g0f9c98f (Scout) | 0.20201203.0 (Soldier)
**Distribution:** Manjaro Xfce 20.2 x64
[**My system information**](https://gist.github.com/temp-account-hello/2f0fd313d05a9ffba1f6a0219fda6afc)
**Checked for system updates:** Yes
**Using the Steam Linux Runtime compatibility tool:** No (I don't think? Unless Proton uses it.)

### **My issue:**
On the current next (also tested with stable initially) build of Proton 5.13 (5.13-4) and even as far back as Proton 5.13-2 or so, all games that I test 5.13 with simply refuse to run. I press "Play" and nothing loads/works, it shows me as in-game for not even a second before I'm shown as just being online again. This happens with Proton-5.21-GE-1 as well, so I assume it's an issue to do with the runtime/vessel as Proton 5.0-10 works. One other strange detail is that when I right-click the icon for Steam in my system/notifications tray, the menu looks as if it comes from Windows 9x, albeit with smooth text (see below).

![menu](https://user-images.githubusercontent.com/17107804/101754920-31500800-3acc-11eb-845d-e94da8138498.png)

[**My pressure-vessel log**](https://gist.github.com/temp-account-hello/12d5dfb7d9d085c195b6d08536d01667)

### **Steps for reproducing this issue:**

**1.** Launch Steam, with default Proton version as 5.13-4
**2.** Attempt to launch Borderlands 3 (or any game), with Proton version forced to Proton-5.21-GE-1
**3.** Game does not open, shown as in-game for <1 second before being shown as online
**4.** Attempt to launch Doom Eternal (or any game), with default Proton version of 5.13-4
**5.** See 3.
**6.** Attempt to launch Deus Ex GOTY (or any game), with Proton version forced to 5.0-10
**7.** Deus Ex works as expected.

**Comment by smcv** [comment]
@kisak-valve, please could you retitle this to something less broad so we don't get users with unrelated issues commenting here? Something like:

```
Proton 5.13 fails to launch on Manjaro: bwrap: No permissions to creating new namespace
```

> Using the Steam Linux Runtime compatibility tool: No (I don't think? Unless Proton uses it.)

You are using the Steam Linux Runtime compatibility tool (pressure-vessel and the soldier runtime). Official binaries for Proton 5.13+, and some unofficial/community builds like 5.21-GE-1, use it to get access to the newer runtime libraries in Steam Runtime 2 'soldier'.

From the log:

```
pressure-vessel-wrap[11230]: Checking for bwrap...
pressure-vessel-wrap[11230]: Cannot run bwrap: wait status 256
pressure-vessel-wrap[11230]: Diagnostic output:
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.

pressure-vessel-wrap[11230]: Exiting with status 1
```

This means the [bubblewrap](https://github.com/containers/bubblewrap) tool isn't working, because your kernel or OS configuration isn't allowing it to work. pressure-vessel and SteamLinuxRuntime rely on this.

If you are using the `linux-hardened` kernel, or another kernel that has Debian's patch adding `/proc/sys/kernel/unprivileged_userns_clone`, then you have two options:

* Install the `bubblewrap-suid` package; or
* Set the `kernel.unprivileged_userns_clone` sysctl to 1

**Comment by smcv** [comment]
Context for the "No permissions to creating new namespace" error:

The requirements for being able to start SteamLinuxRuntime (pressure-vessel) containers are similar to the requirements for being able to run Flatpak apps.

In normal upstream Linux kernels, unprivileged users can create their own "user namespaces" (containers) without needing special permissions or privileges. On these kernels, the `bwrap` tool that is included with pressure-vessel can set up our container. Most modern distributions behave like this, including Fedora, Ubuntu, and Arch Linux with its default kernel.

Some OS distributors are concerned about extra kernel attack surface from user namespaces, and have applied a patch to their kernels so that only `root` can create new user namespaces. The most common version of this patch, originally from Ubuntu and now maintained by Debian, creates a file named `/proc/sys/kernel/unprivileged_userns_clone`. In these distributions, you have to use a setuid-root version of `/usr/bin/bwrap` that is trusted by the OS distributor to act as a privilege boundary, like Debian's `bubblewrap` package or Arch Linux's `bubblewrap-suid` package. The main distribution that does this now is Debian, but Arch Linux's non-default `linux-hardened` kernel behaves the same. Older versions of CentOS/RHEL had similar behaviour, but more recent versions behave like Fedora instead.

I don't know how Manjaro's kernel is configured. I would have expected it to be the same as Arch Linux's default kernel, but from the error you're getting, perhaps that isn't true.

If your OS distribution has a guide for installing Flatpak, you can probably use that to make pressure-vessel work, because pressure-vessel will automatically use the same `bwrap` or `flatpak-bwrap` tool as Flatpak if available.

**Comment by smcv** [comment]
> One other strange detail is that when I right-click the icon for Steam in my system/notifications tray, the menu looks as if it comes from Windows 9x

This is normal(ish). I think Steam uses GTK 2 for that menu. It is nothing to do with containers or pressure-vessel.

**Comment by temp-account-hello** [comment]
Oh, erm. I feel slightly silly now. Installing `bubblewrap-suid` and restarting seemed to work. The kernel I'm using is a modified version of the Xanmod kernel with some Manjaro patches, so it's not the default Manjaro kernel. HOWEVER - I'm slightly confused as to how this issue suddenly popped up, because I hadn't been encountering anything like this prior to last week or so. Nevertheless, I'm super thankful for your help and sorry for wasting time on what feels like such a trivial issue.

btw, I'll change the title to your suggestion just to make things less generic. I guess I'm able to close this now, and hopefully this'll help whoever is also unfortunate enough to suddenly get an issue like this.

**Comment by smcv** [comment]
> hopefully this'll help whoever is also unfortunate enough to suddenly get an issue like this

Sure, that's why I wrote so much text about possible configurations - I wanted to make the answer more generic across distros.

We should ideally make the diagnostic tool try to figure out how user namespaces work on this particular distribution, and give some recommendations.

> a modified version of the Xanmod kernel with some Manjaro patches

There's a limit to what we can do with arbitrarily modified operating systems: if you modify the OS, then making it not break things you're relying on is up to you (even if you don't know yet that you're relying on them).

**Comment by Pistos** [comment]
In case it helps anyone: On Gentoo, I was getting 

`bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.`

but installing bubblewrap (`emerge bubblewrap`) made that error go away.

Now I'm getting the following, but it's a different concern than the original one of this github issue.

```
pressure-vessel-wrap[29587]: E: Cannot run bwrap: wait status 256
pressure-vessel-wrap[29587]: E: Diagnostic output:
bwrap: Failed to make / slave: Invalid argument
```

**Comment by kisak-valve** [comment]
Hello @Pistos, please open a new issue report so that your issue can be tracked properly.

**Comment by Pistos** [comment]
In case it helps anyone else, I solved the

```
bwrap: Failed to make / slave: Invalid argument
```

problem.  Details in https://github.com/ValveSoftware/steam-runtime/issues/465 .
