### ISSUE TITLE
Steam don't work with radeon mesa (open source) driver

### ISSUE THREAD

**Issue by leotada** [ValveSoftware/steam-runtime#34]
I have a AMD Radeon R7 250 and run Fedora 22 Workstation 64bit, and got this error.

$ steam
Running Steam on fedora 22 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1431729692)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by MrSchism** [comment]
They're aware; Steam supports the proprietary drivers (as described at https://github.com/ValveSoftware/steam-for-linux#hardware-and-software-requirements).

**Comment by Ruedii** [comment]
This is the same bug as  Steam for Linux bug #3801

**Comment by alexander255** [comment]
Problem is that never versions of nouveau drivers (and apparently also radeon drivers) seem to require a newer version of `libstdc++6` than what Ubuntu 12.04 LTS (and therefor Steam's runtime) provide.

Try this:

 1. Open the directory `~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu`
 2. Rename the file `libstdc++.so.6.0.18` to something else (such as `libstdc++.so.6.0.18.bak`)
 3. Create a symbolic link with the name `libstdc++.so.6.0.18` to your system's 32-bit `libstdc++.so.6` (located in `/usr/lib/i386-linux-gnu/libstdc++.so.6` in my case)

@ValveSoftware It'd be nice if libstdc++ version could be updated (or be provided by the system). Sooner or later other dynamically-loaded, but system-provided libraries (libVA-backends?) will cause similar issues if their expected symbols and symbol-versions aren't available.

Currently `libc6` is considered to be part of the base system and not bundled with the Steam runtime, maybe the same thing should be done for `libstdc++6`? Hard to imagine a system without that library nowadays (just look at its rdepends!) and thanks to versioned symbols it guarantees backwards-compatibility forever (just like `libc6`).

**Comment by leotada** [comment]
This did works alexander255! Thanks. But now this issue should be fixed in steam-runtime.

**Comment by Zeioth** [comment]
This problem is due to some outdated libraries in the steam folder. While the steam team update the [solution is to erase them](http://askubuntu.com/a/538907/234719) (so steam will take them from the system).

```
rm ~/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6
rm ~/.steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libgcc_s.so.1
rm ~/.steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgcc_s.so.1
rm ~/.steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6
rm ~/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libxcb.so.1
```

**Comment by alexander255** [comment]
@Zeioth That might work too although I'm pretty sure it was problematic for me in some way (cannot remember why)

@ValveSoftware Forget what I said about `libstdc++6` being stone-age compatible:
As you are probably aware GCC 6 recently broke that assumption by changing its post-C++-98 ABI in a spectacular way that will probably continue to cause headaches in the years to come. Too bad :-(

**Comment by Ruedii** [comment]
Would it be possible to change the libraries to have their versioning set
up in a way that they wouldn't override the default for anything not built
specifically for their version, or would doing so cause even more issues?

Also, is there anything that is dependent on the old version of libstdc++?
After all, if there isn't there is no reason it can't be updated to a
back-ported version.

On Sat, Oct 24, 2015 at 3:29 PM, Alexander Schlarb <notifications@github.com

**Comment by alexander255** [comment]
> Would it be possible to change the libraries to have their versioning set
> up in a way that they wouldn't override the default for anything not built
> specifically for their version, or would doing so cause even more issues?

That would not be a problem if the glibc maintainers had taken ABI stability seriously and published `libstdc++.so.7` (since the new version of the library is not backward compatible with `libstdc++.so.6`). Unfortunately they did not and so that does not work properly…

> Also, is there anything that is dependent on the old version of libstdc++?
> After all, if there isn't there is no reason it can't be updated to a back-ported version.

Problem is that Steam is a binary-only software distribution platform. Valve Inc does not have access to any of the sources that would need updating to the latest version of `libstdc++` (except for their own games). Requiring all Steam game developers to recompile their Linux version is not something that is feasible that this point (nor is it something that Valve would be interested in).

**Comment by Ruedii** [comment]
Linux binary programs don't tend to ship with libstdc++ it tends to be backwards compatible (just not forwards compatible).

None of the steam games I have downloaded ship their own libstdc++.  They all either use the version in Steam Runtime or the user's computer.

**Comment by alexander255** [comment]
Yes, but while `libstdc++` *tends* to be binary compatible, this is not the case anymore thanks to the latest GCC5 transition. The latest `libstdc++` is for from compatible from the one from a few months ago.

**Comment by Ruedii** [comment]
This brings up a second question.  Can multiple versions coexist if the
binary is compiled (or told) to look for the right one.
On Nov 4, 2015 8:39 AM, "Alexander Schlarb" <notifications@github.com>
wrote:
>
> Yes, but while libstdc++ tends to be binary compatible, this is not the
case anymore thanks to the latest GCC5 transition. The latest libstdc++ is
for from compatible from the one from a few months ago.

**Comment by directhex** [comment]
For the interested, the actual problem lies with the Linux linker behaviour, combined with the way Mesa is compiled on 99% of distros..

The Steam runtime relies on LD_LIBRARY_PATH mangling, so all the libs in the runtime are used preferentially. The distro foobar_dri.so module (as required for Mesa) tries to load the Steam Runtime version of libstdc++.so.6 rather than the distro version, which fails due to missing symbols in the Steam Runtime copy vs. the copy foobar_dri.so was built against.

Specifically, if Mesa was compiled using GCC 4.9.0 or above and dynamically links against libstdc++, then the problem because Steam Runtime's libstdc++ doesn't export GLIBCXX_3.4.20 (as it's not found in 4.8.3)

The reason the runtime ships libstdc++ is so features from GCC 4.8.3 are available on all supported distros that might have an older version - but because of dynamically-linked Mesa, this issue pops up.

SteamOS works around the issue by statically linking libstdc++ in its Mesa.

**Comment by alexander255** [comment]
> SteamOS works around the issue by statically linking libstdc++ in its Mesa.

So SteamOS basically updates the userland portions of its drivers through Steam runtime updates?

**Comment by directhex** [comment]
> So SteamOS basically updates the userland portions of its drivers through Steam runtime updates?

Er, no.

SteamOS Mesa doesn't use the Steam Runtime version of libstdc++ at all, ever, under any circumstances.

If Mesa uses any libstdc++ that happens to drift past ld.so, then it is going to be fragile, and that's by design. Frankly it's hard to fathom just how stupid a design choice in standard Mesa that is.

**Comment by alexander255** [comment]
Oh, sorry I misread the last sentence Mesa statically links to `libstdc++`. I somehow understood that SteamOS statically links to Mesa (whatever sense that would make…). ;-)

I don't think that Mesa's usage of `libstdc++` is too bad considering that nobody statically links to `libc` either. They're are just considering `libstdc++` to be part of the core environment, while SteamOS considers it to be an "add-on". You'd have the same problems * 10 if Steam runtime decided to include `libc` in its distribution…
Either way: The current situation is fucked up and needs a better solution than: "Let's hope that Steam runtime updates its libraries often enough"

**Comment by mmstick** [comment]
I'm surprised that this is still a **serious problem**, and it's only going to become more serious as time passes. **Ubuntu 16.04** is about to release and **Steam will not be able to work with AMD graphics cards at all, period,** because of the Steam Runtime. Every time I install Steam, I have to apply the same small change time and time again to the **steam.desktop** which I shouldn't have to do. Steam will not launch on any platform with open source drivers without it. Simply edit **/usr/share/applications/steam.desktop** and change `Exec=/usr/bin/steam %U` to `LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1' /usr/bin/steam %U` and everything works fine.

**Comment by mariojuniorjp** [comment]
@alexander255 i try this, but i get this error:

ln: failed to create symbolic link '/usr/lib32/libstdc++.so.6': file exists

In my case is Arch Linux.

**Comment by Ruedii** [comment]
Is there a way a shim library could be written for games explicitly written for the GCC4 version of libstdc++?

I know it would be hit and miss, but it should work.

While it's a dirty hack, it might be the only option.

Simply put there should be two steam runtimes.
Steam-Runtime-compatGCC4 (or Steam-Runtime-Ubuntu12.04 after the Ubuntu standard base it's based on) and Steam-Runtime.

Steam-Runtime-compatGCC4 should include shim libraries to handle compatibility with GCC5 systems.

**Comment by Guard13007** [comment]
Okay what the fuck. I've just installed Ubuntu 16.04, expecting things to, you know, work. Yet this apparently has been going on for almost a year? None of the above solutions work, and I'm beginning to get a little pissed honestly.

**Comment by mmstick** [comment]
@Guard13007 This has been going on for more than a year -- try since Steam for Linux's inception. The fix is on the [Arch Linux wiki](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues). There's also [Solus OS](https://solus-project.com/) as an option as it is supporting its own Steam native runtime to fix this problem.

**Comment by Guard13007** [comment]
@mmstick I'll look into that for the future. For now I switched to Ubuntu 14.04.4 with fglrx-updates installed and following the instructions [here](http://askubuntu.com/a/671193). I definitely like Arch Linux, but I've had some issues with stability, which is why I'm not 100% eager to jump on it for my main system.

**Comment by mmstick** [comment]
@Guard13007 The information on the Arch wiki applies to all Linux distributions. The same fix works on Ubuntu 16.04 and Fedora.

**Comment by Ruedii** [comment]
I was wondering if moving all of Steam to use Snappy packaging would solve this issue as well as prevent future issues.

I'd even recommend making Steam use a variant of snappy for their next generation packaging.

**Comment by alexander255** [comment]
> I was wondering if moving all of Steam to use Snappy packaging would solve this issue as well as prevent future issues.

@Ruedii: I hope Snappy packages do not contain userland driver libraries??
If they do, I'd end up as disaster; if they don't then I'm pretty sure nothing would change!?

> I'd even recommend making Steam use a variant of snappy for their next generation packaging.

Is it possible to host your own Snappy repos outside of the Ubuntu store at this point?

**Comment by Ruedii** [comment]
Yes.  Also there are currently two stores that I know of.  One is the
Ubuntu one, the other is run by the site for the snappy standard.  You can
just ship a .snap file without the store as well.

Currently snappy can be run on all major distros, but only Ubuntu has it in
their main install.

On Aug 8, 2016 8:04 AM, "Alexander Schlarb" <notifications@github.com>
wrote:

I was wondering if moving all of Steam to use Snappy packaging would solve
this issue as well as prevent future issues.

@Ruedii <https://github.com/Ruedii>: I hope Snappy packages do not contain
userland driver libraries??
If they do, I'd end up as disaster; if they don't then I'm pretty sure
nothing would change!?

I'd even recommend making Steam use a variant of snappy for their next
generation packaging.

Is it possible to host your own Snappy repos outside of the Ubuntu store at
this point?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ValveSoftware/steam-runtime/issues/34#issuecomment-238216285>,
or mute the thread

**Comment by jgmatu** [comment]
I resolved the problem installing propietary drivers of graphics in linux mint 

Regards,

**Comment by smalltock** [comment]
fglrx is deprecated and is incompatible with current Xorg releases.  fglrx is no longer supported on Ubuntu either, so steam is incompatible with current Ubuntu LTS.

**Comment by alexander255** [comment]
In case people here haven't noticed yet: Valve has (FINALLY!) addressed this issue in the latest version of Steam :
http://store.steampowered.com/news/26953/ (First bullet point in the Linux section)

If you cannot currently start the steam client then try running `STEAM_RUNTIME=0 steam` in a terminal. This should launch the updating application and download the latest version. After everything has been downloaded the updater will then restart steam and crash. At this point simply run steam normally (using the official steam runtime and no `LD_PRELOAD` or similar hacks) and it should apply the previously downloaded update and "just work" after that.

**Comment by smalltock** [comment]
I don't know, my dude.  Doesn't 𝕁𝕦𝕤𝕥 𝕎𝕠𝕣𝕜™ for me.  I still have to LD_PRELOAD.

**Comment by kisak-valve** [comment]
Steam's handling of the Steam runtime changed to prefer the host's libraries by default some years back, which includes all of mesa's dependencies.
