### ISSUE TITLE
EVERSPACE™ 2 (1128920) doesn't start anymore with 0.20210114.0+srt1

### ISSUE THREAD

**Issue by Corben78** [ValveSoftware/steam-runtime#349]
#### Your system information

* Steam Runtime Version: 0.20210114.0+srt1
* Distribution: Ubuntu 20.04
* Link to your full system information: [Gist](https://gist.github.com/Corben78/fe9544f14d93e1cf6746ec7688dba16d) 
  
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:

With the recent Steam Linux Runtime - Soldier [client_beta] I cannot start Everspace 2 anymore. The game doesn't start at all, no splash screen is shown, no Proton log file can be created. Works with the stable version of the Steam Linux Runtime - Soldier, or when steam is started with `PRESSURE_VESSEL_RELAUNCH_CONTAINER=0 steam`.
Other games I tested still work (e.g. GTFO, Bioshock 2 Remastered, HELLDIVERS™, Drone Swarm). It might be related to the name of the folder of Everspace 2: `steamapps/common/EVERSPACE™ 2` with the ™ in it, as no other game has that for me so far.

Pressue Vessel log: [slr-app1128920-s241f1ecd1dadc529.log](https://gist.github.com/Corben78/34a22318fa7d6eb7a347f25f5169ee63)

#### Steps for reproducing this issue:

1. Update Steam Linux Runtime - Soldier [client_beta] to 0.20210114.0+srt1
2. Start EVERSPACE™ 2 with Proton 5.13-5
3. See it closing directly

**Comment by smcv** [comment]
What is the exact name of the directory? Please use something like this:

```
$ ls -d EVERSPACE™\ 2 | od -tx1z   
0000000 45 56 45 52 53 50 41 43 45 e2 84 a2 20 32 0a     >EVERSPACE... 2.<
0000017
```

(In my example, the `™` is encoded in UTF-8 - 0xe2, 0x84, 0xa2 - but I want to know whether on your system, it's UTF-8 or Latin-1 or something else.)

Also, what are your locale environment variables set to, at the time that pressure-vessel runs? If you edit the `_v2-entry-point` script, so that just after printing the `argv` it runs `locale`, `env | grep '^LC_'` and `env | grep '^LANG'`, that will tell us.

**Comment by smcv** [comment]
> What is the exact name of the directory?

Never mind, I can see from the log that it's UTF-8: `EVERSPACE\342\204\242 2`.

**Comment by Corben78** [comment]
Do you still need info about my locale settings? Will have to check with pressure-vessel environment, so far on my shell the `local`command returns:
```bash
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by smcv** [comment]
Steam overrides those with `LC_ALL=C` as a heavy-handed solution for issues like https://github.com/ValveSoftware/steam-for-linux/issues/5827, so what happens during pressure-vessel startup is not going to match those. We have a minimal reproducer for this at https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/52 so I don't think we need more info, though.

It would be a less big hammer if Steam used `LC_NUMERIC=C` and `LC_COLLATE=C`, rather than resorting to `LC_ALL=C`.

@TTimo, now that we have `STEAM_COMPAT_FLAGS`, is there any possibility of having new/well-behaved games flagged to respect the user's locale settings (at least for `LC_MESSAGES`), rather than overriding everything?

**Comment by TTimo** [comment]
@smcv maybe create a phabricator to discuss this internally. I'm not sure how we would spec that - default behavior would be to default `LC_ALL=C` on existing apps for backwards compatibility, and we can support a few new settings, `LC_NUMERIC/LC_COLLATE`, or not setting anything at all. Problems are:

- Those problems also depend on the host, a game for which we don't set `LC_ALL=C` might still work on most hosts and only fail on some systems.
- As a policy, we've stayed away from modifying metadata for any title. Things should probably stay that way, so it would be up to authors to update their configurations?

**Comment by smcv** [comment]
> The crash is caused by a locale conversion in pressure-vessel when we try to parse the launch options.

This regression should be fixed in the new client beta (soldier >= 0.20210126.1, which comes with pressure-vessel >= 0.20210126.0+srt1). @Corben78, please could you try Everspace 2 again with this new beta?

**Comment by smcv** [comment]
(note for @kisak-valve: because this was a regression in 0.20210114.0, which never made it past beta status, we can close this as soon as it is confirmed to be fixed in the beta)

**Comment by smcv** [comment]
> is there any possibility of having new/well-behaved games flagged to respect the user's locale settings (at least for LC_MESSAGES), rather than overriding everything?

(Now tracked as T26045 internally)

**Comment by Corben78** [comment]
Works fine with Everspace 2. Thank you very much!
