### ISSUE TITLE
Rocket League using integrated graphics instead of secondary GPU

### ISSUE THREAD

**Issue by jph168** [ValveSoftware/steam-runtime#352]
# Compatibility Report
- Rocket League
- Steam App ID: 252950

## System Information
- CPU: Ryzen 5 3550H 
- GPU: Rx560
- Driver/LLVM version: Mesa 21.1.0 Devel git
- Kernel version: 5.11rc4
- System Specs via Steam Sys info: 
https://gist.github.com/jph168/b17d76bf69ff15afd2fc94ca92d950d5
- Proton version: 5.13-5

## I confirm:
these requirements.
I have tested on 5.11 rc4, 5.10.9-1, and 5.9.16-1 with mesa 21 git and mesa 20.3.3-1. just to confirm it was not in any of those.
<I can confirm that. Switching between proton 5.0-10 and 5.13-5 I can confirm regression is between. Discrete Gpu utilization also drastically drops with this regression, which seems to cause integrated graphics to be utilized over it.
5.0-10 is good 5.13-5 is bad. I haven't been able to get any farther sadly.

[steam-252950 5.0-10.log](https://github.com/ValveSoftware/Proton/files/5840273/steam-252950.5.0-10.log) 5.0-10
[steam-252950 5.13-5.log](https://github.com/ValveSoftware/Proton/files/5840275/steam-252950.5.13-5.log) 5.13-5

## Symptoms 
Fps is consistently half it was never getting any higher with pretty bad performance compared. 
![5 0-10 with utilization](https://user-images.githubusercontent.com/31376624/105140539-7731c000-5abd-11eb-97f1-56e81b0428ff.png)
![5 13-5utilization](https://user-images.githubusercontent.com/31376624/105140543-7a2cb080-5abd-11eb-843f-a935e3aac680.png)

## Reproduction
I believe this would affect only those having a fully Amd laptop with integrated and discrete graphics. 
Any hardware configuration with 2 Amd cards technically. Between Proton 5.0-10 / 5.13-2.

**Comment by kisak-valve** [comment]
Hello @jph168, let's treat this as a Pressure Vessel issue until there's a stronger indication the issue is elsewhere. Starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment and that's setup by Pressure Vessel.

Before we dig too deeply into this issue, please describe how do you normally tell games to use the secondary video card. Also, please test the 2021-01-14 (or newer) build of Steam Linux Runtime - Soldier by going to your Steam library, searching for `Steam Linux Runtime - Soldier`, right click on it -> Properties ... -> Betas -> select `client_beta` from the dropdown.

**Comment by jph168** [comment]
Hey kisak-valve, so I've tested using the beta version of Steam Linux Runtime - Soldier, result is no different. 
I assume games use dgpu when performance is good, normally they just do as proton had. How do you normally tell games to use the secondary video card. I, don't.

**Comment by jph168** [comment]
Hey kisak-valve again, I've gone through more extensive testing and it seems the actual root of this problem is steam itself using my igpu over dgpu under my steam system information. 

Video Card:
    Driver:  AMD AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.11.0-1-MANJARO, LLVM 11.0.1)
which in turn makes games not just on the latest proton but native games to. 

It's been like this I just didn't notice it until the latest proton exposed the probable issue.

Surprisingly proton 5.0-10 still used dgpu over igpu even though it was under igpu still.

I must set DRI_PRIME=1 parameter for steam itself to detect my dgpu
under steam system information

Video Card:
    Driver:  AMD Radeon RX 560 Series (POLARIS11, DRM 3.40.0, 5.11.0-1-MANJARO, LLVM 11.0.1)
so it uses it for all games native or not.

**Comment by smcv** [comment]
> Setting DRI_PRIME=1 %command% makes rocket league use it on 5.13-5

If you run a DXVK game like this while *not* in the container (for example with Proton 5.0), with `DRI_PRIME=1` in the environment, does it end up running on the fast discrete GPU or on the slower integrated GPU?

The mechanisms used to choose a GPU to run on are quite complicated (particularly when DXVK is involved) so it isn't clear what piece of information is not getting through to the container.

> System Specs via Steam Sys info

This is incomplete. Please could you wait for the full report to appear, and then send that?

You should get up to four blobs of information: first what you already provided, then a report about the `LD_LIBRARY_PATH` runtime in JSON format, then a JSON report about the `SteamLinuxRuntime` container runtime if you have it, and finally a JSON report about `SteamLinuxRuntime_soldier`.

**Comment by smcv** [comment]
@jph168 (or anyone else experiencing this), please could you check this again with a current version of **Steam Linux Runtime - soldier**, and provide the information I described in my previous comment?

I don't currently have access to a multi-GPU system that is new enough to have fully working Vulkan, so I'm relying on people like you to provide the information necessary to figure out what is going wrong here.

**Comment by jph168** [comment]
Full Sys Info https://gist.github.com/jph168/e4f2c3135983848106ad78933d57ab73 
Sw config
Kernel 5.11.2
Mesa 20.3.4
Running a **DXVK Game**(Rocket League) with **DRI_PRIME=1** in a **Non Containerized Proton**(5.0-10) that **uses Discrete without the Command** continues using the Discrete Graphics like is :). sry for late response.

**Comment by smcv** [comment]
Unlike most of the other multi-GPU issues, instead of Intel/NVIDIA, you have AMD/AMD ("AMD RADV RAVEN (ACO)" and "AMD RADV POLARIS11 (ACO)").

The "Raven" seems to be flagged as an integrated GPU and the "Polaris11" is the discrete GPU. Is that correct?

The LD_LIBRARY_PATH Steam Runtime is disabled: you seem to be using Arch Linux's `steam-native` (and the `desktop-entries` section of the log confirms that it is set as your default handler for `steam://` URLs). Valve specifically does not support this configuration. It will break some native Linux games, but might leave Proton unaffected if you're lucky. You can see the effect of this in the `library-details` section of the log: lots of libraries are failing to load. If a native Linux game or an older version of Proton depends on one of those libraries, then it would also fail to load.

Our diagnostic tool can successfully draw a polygon using either of the GPUs. The default (the first one listed) seems to be the integrated "Raven", both outside and inside the container.

You're using Mesa 20.3.4, the latest stable release, so I would have expected you to have the device selection layer `libVkLayer_MESA_device_select.so`; but it seems to be missing from your system (or, at least, the diagnostic tool can't find it). Is that deliberate? The device selection layer is an important part of how this is meant to work.

> Running a DXVK Game(Rocket League) with DRI_PRIME=1 in a Non Containerized Proton(5.0-10) that uses Discrete without the Command continues using the Discrete Graphics like is :)

I'm not sure whether I'm reading this correctly, so let me try to rephrase what I think you're saying:

* no special environment variables, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
* no special environment variables, containerized Proton (5.13): game runs on slow Raven integrated GPU
* `DRI_PRIME=1`, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
* `DRI_PRIME=1`, containerized Proton (5.13): game runs on fast Polaris 11 discrete GPU

Is that correct?

**Comment by jph168** [comment]
Yes, I am using Steam Native I can switch to Steam Runtime if that's correct. 
The "Raven" seems to be flagged as an integrated GPU and the "Polaris11" is the discrete GPU< that is Correct.
VlkMesaLayers<good to know, thats easy to solve. I can resend sys info and test under requested configuration If wanted.

    no special environment variables, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    no special environment variables, containerized Proton (5.13): game runs on slow Raven integrated GPU
    DRI_PRIME=1, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    DRI_PRIME=1, containerized Proton (5.13): game runs on fast Polaris 11 discrete GPU
That is correct but also wanted to mention.
DRI_PRIME=1, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU< this result is same with/without DRI_PRIME=1.

**Comment by jph168** [comment]
Yes, I was using Steam Native I can switch to Steam Runtime if that's correct. VlkMesaLayers inferred important, I now have that. 
System Information using Steam Runtime https://gist.github.com/jph168/d25f1ba70dcf329298d36a54658a8b5e 
The "Raven" seems to be flagged as an integrated GPU and the "Polaris11" is the discrete GPU
That is Correct sw/hw config wise.


    no special environment variables, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    no special environment variables, containerized Proton (5.13): game runs on slow Raven integrated GPU
    DRI_PRIME=1, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    DRI_PRIME=1, containerized Proton (5.13): game runs on fast Polaris 11 discrete GPU
^ is correct
I expected issues, not severe ones with this niche hardware configuration as mentioned, most don't have. 
People who have AMD Apu's Desktop, cpu's with radeon graphics or Mobile like my laptops 3550h _will_ run into this issue. 
Due to the Integrated Graphics being detected as a Gpu itself, it will be set as the Primary Graphics Card0.
 If it's just an AMD cpu with a discrete graphics card required which is most of AMD's
  it will not be a problem as the correct gpu is used because only option. 

I can retest under requested configuration.
Kernel 5.11.3 
Mesa 20.3.4 with Vulkan Mesa Layers
Steam Runtime 
These Test:

    no special environment variables, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    no special environment variables, containerized Proton (5.13): game runs on slow Raven integrated GPU
    DRI_PRIME=1, non-containerized Proton (5.0): game runs on fast Polaris 11 discrete GPU
    DRI_PRIME=1, containerized Proton (5.13): game runs on fast Polaris 11 discrete GPU
   
    are the same either Steam Runtime or Native
    
Steam by Default Detects my Card as:
Video Card:
    Driver:  AMD AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.11.3-1-MANJARO, LLVM 11.1.0)
Unless I Force Steam itself to run with DRI_PRIME=1 
Video Card:
    Driver:  AMD Radeon RX 560 Series (POLARIS11, DRM 3.40.0, 5.11.3-1-MANJARO, LLVM 11.1.0)

Which solves ever setting DRI_PRIME=1 for any Game but I assume since Steam can tell a difference between Igpu/Dgpu
or it's likely driver related: https://gitlab.freedesktop.org/mesa/mesa/-/commit/517600b4d59c631a59dc3b8426fb485c830dd127

**Comment by Leopard1907** [comment]
When you install Soldier Runtime beta ( needs Steam client beta+opt in to soldier runtime beta under tools section in library ) and start Steam client with `DRI_PRIME=1 steam` does game still use your igpu?

**Comment by jph168** [comment]
Unless I Force Steam itself to run with DRI_PRIME=1
Video Card:
Driver: AMD Radeon RX 560 Series (POLARIS11, DRM 3.40.0, 5.11.3-1-MANJARO, LLVM 11.1.0)
Which solves ever setting DRI_PRIME=1 for any Game
@Leopard1907 No but I retested to re confirm that. I've been using the Beta Client so requirements for enabling anything inferred doesn't fall short.

**Comment by jph168** [comment]
@kisak-valve this issue can be closed as Steam Linux Runtime Soldier is properly handling using dgpu over igpu without forcing the command.
CPU: Ryzen 5 3550H
GPU: Rx560
Driver version: Mesa 21.3.0-devel (git-4f7043fc0c)
Kernel version: 5.14rc3
Proton 6.3-5
