### ISSUE TITLE
pressure-vessel-wrap: Too many levels of symbolic links

### ISSUE THREAD

**Issue by axelgenus** [ValveSoftware/steam-runtime#366]
I've had this issue for a while now and, although I tried to fix it myself, nothing seems to work.

The attached log is for Control (Steam app ID 870780) but it is applicable to all non-native games in my library.
[control.log](https://github.com/ValveSoftware/Proton/files/5980944/control.log)

The problem seems to be described in the log as follows:
`pressure-vessel-wrap[203173]: openat(/proc/self/fd/21): Too many levels of symbolic links`

I am currently running Gentoo with a custom compiled Linux ZEN kernel but I also tried the dist-binary (based off Fedora kernel configuration) and gentoo-sources to no avail.

Any suggestion would be greatly appreciated.

EDIT: Proton 5.0 and previous versions work flawlessly.

**Comment by kisak-valve** [comment]
Hello @axelgenus, starting with Proton 5.13, Proton is being run inside the Steam Linux Runtime - Soldier container environment and Pressure Vessel is what sets that up. Let's treat your issue as a Pressure Vessel issue until there's a stronger indication the issue is elsewhere.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share a Steam Linux Runtime log along with your system information from Steam in a [gist](https://gist.github.com).

**Comment by axelgenus** [comment]
Thank you for looking into my issue. I am also under the impression that it is an issue related to pressure-vessel but I cannot find anything related to this kind of error message either among the GH issues nor searching the internet.

[These](https://gist.github.com/axelgenus/a7efacf29274ca9ae175e8ef3fa28a08) are the system information as reported by steam client.

[This](https://gist.github.com/axelgenus/734128b622c49fc0131544d5a8fc1daf) is the log when I try starting the game with Proton 5.13.

**Comment by smcv** [comment]
`Too many levels of symbolic links` is the `ELOOP` error code, which can mean one of three things:

* you have a filesystem structure with a symlink to a symlink to ... etc. that repeats forever
* you have a filesystem structure with a symlink to a symlink to ... etc. that does not repeat forever, but is a long enough chain that the kernel gives up following it and assumes it repeats forever
* we are opening a file with the `O_NOFOLLOW` option to avoid following symbolic links (often done to avoid symlink attack vulnerabilities or infinite loops), but it's a symbolic link, so we refuse to open it 

Your system info reports a bunch of Vulkan ICDs and layers: `/etc/vulkan/icd.d/nvidia_icd.json"`, `/etc/vulkan/implicit_layer.d/nvidia_layers.json`, `/usr/share/vulkan/implicit_layer.d/MangoHud.json`, `/home/REDACTED/.local/share/vulkan/implicit_layer.d/steamfossilize_i386.json`, `/home/REDACTED/.local/share/vulkan/implicit_layer.d/steamfossilize_x86_64.json`, `/home/REDACTED/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json`, `/home/REDACTED/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json`.

Are any of those filenames actually symbolic links? If they are, what is their target? If the target is a symbolic link, please repeat until you get to a regular file.

Similarly, are `/home`, `/home/REDACTED`, etc., up to `/home/REDACTED/.local/share/vulkan/implicit_layer.d`, symbolic links? If yes, what is their target? And the same for `/etc/vulkan/implicit_layer.d` and `/etc/vulkan/icd.d`.

Also, if you look in the .json files, each one describes a shared library (`library_path`). Are any of *those* symbolic links, or are their parent directories symbolic links?

**Comment by axelgenus** [comment]
I checked all JSON files and none of them is a symlink. Only `/etc/vulkan/icd.d/nvidia_icd.json` and `/etc/vulkan/implicit_layer.d/nvidia_layers.json` point to symlinked shared libraries but those symlinks immediately redirect to the physical file in the same folder.

The only "uncommon" filesystem structure I have on my PC is the /home directory being mounted to a ZFS volume. I use OpenZFS 2.0.3 currently. I tried moving a game to the root partition (formatted as ext4) but nothing really changed.

**Comment by axelgenus** [comment]
I managed to solve the issue myself by (manually) removing Steam Runtime Linux - Soldier and reinstalling it.

Thank you for your support.

**Comment by kisak-valve** [comment]
Glad to hear you got it running, but unfortunately that also means we no longer have a test case to ponder.

Closing per the last comment.

**Comment by axelgenus** [comment]
> Glad to hear you got it running, but unfortunately that also means we no longer have a test case to ponder.
I have a backup of the old `SteamLinuxRuntime_soldier` folder if it can be of any use.

**Comment by kisak-valve** [comment]
It might be interesting to ponder the difference between the old folder and the newly unpacked folder including the target of any symlinks in the diff. I don't have a ready crafted command to suggest which would tell us that.

**Comment by axelgenus** [comment]
The only difference seems to be an additional "tmp-5IG1Y0" directory, in the broken Steam soldier "var" folder.

Here you can find the tree of the additional folder: https://gist.github.com/axelgenus/725e3c00393627ad1d94aa83295ca089
There are literally hundreds of symlinks. I can't possibly check all of them manually. I am going to find a way to recursively check all symlinks.

**Comment by axelgenus** [comment]
Ah, I think I got it:

```
$ find -L . > /dev/null
find: ‘./var/soldier_0.20210126.1/files/lib/ssl/private’: Permission denied
find: File system loop detected; ‘./var/soldier_0.20210126.1/files/bin/X11’ is part of the same file system loop as ‘./var/soldier_0.20210126.1/files/bin’.
find: ‘./var/tmp-5IG1Y0/lib/ssl/private’: Permission denied
find: File system loop detected; ‘./var/tmp-5IG1Y0/bin/X11’ is part of the same file system loop as ‘./var/tmp-5IG1Y0/bin’.
find: ‘./var/tmp-5IG1Y0/usr/lib/ssl/private’: Permission denied
find: File system loop detected; ‘./var/tmp-5IG1Y0/usr/bin/X11’ is part of the same file system loop as ‘./var/tmp-5IG1Y0/usr/bin’.
find: ‘./var/soldier/files/lib/ssl/private’: Permission denied
find: File system loop detected; ‘./var/soldier/files/bin/X11’ is part of the same file system loop as ‘./var/soldier/files/bin’.
```

There are multiple issues here:
- I guess the "permission denied" errors leads to a NSS error[1] which I keep experiencing even if pressure-vessel seems to be working fine now. On Gentoo /etc/ssl/private is readable only by root.
- the others are symlink infinite loops which seems to be the root cause of this issue.

[1] `[0219/133905.138047:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018`

**Comment by smcv** [comment]
> Anyways, this is what I think happened: previously I used the Flatpak version of Steam because it is easier to use but pressure-vessel is incompatible with that version so I decided to give the "official" Gentoo Steam overlay a spin. I've just reused the same steamapp folder so I've never actually reinstalled SteamLinuxRuntime_soldier.

This is not *meant* to break things. I'm working on making pressure-vessel and Flatpak compatible with each other, and my test systems have `SteamLinuxRuntime_soldier` in a Steam library shared between the two, so it definitely *can* work.

Sharing the Steam installation (`~/.steam`, `~/.local/share/Steam`) between Flatpak and native installations of Steam is probably a bad idea, because the two installations will have different ideas about what an absolute path means. The setup I use is to create a separate Steam library (mine is `~/SteamLibrary`), share it with the Flatpak app via `flatpak override --filesystem='~/SteamLibrary' com.valvesoftware.Steam`, and configure both the Flatpak and native installations to have that directory as a second Steam library, which I set as the default.

> File system loop detected; ‘./var/soldier/files/bin/X11’ is part of the same file system loop as ‘./var/soldier/files/bin’

I would have expected this to always happen, for all runtime versions - which means it should be harmless, because the runtime works for at least some people. The runtime is based on Debian 10, and Debian's `x11-common` package has a symlink `/usr/bin/X11 -> .` to avoid regressions for old packages that hard-code paths to executables of the form `/usr/bin/X11/foo`.

There must be something different about your system that is causing this to be a problem for you. Do you perhaps have both `/usr/bin/X11` and `/usr/bin` included as separate entries in your `PATH`, or something like that?

> find: ‘./var/soldier_0.20210126.1/files/lib/ssl/private’: Permission denied
>
> On Gentoo /etc/ssl/private is readable only by root (root:root 600).

My Debian systems have the same setup as Gentoo, so this is working as intended. It's OK that you can't read the directory you are not meant to be able to read :-)

**Comment by smcv** [comment]
> The only difference seems to be an additional "tmp-5IG1Y0" directory, in the broken Steam soldier "var" folder

This is part of the work-in-progress implementation of making pressure-vessel work in Flatpak. Some of the setup we need to do cannot be done from inside a Flatpak sandbox for permissions reasons, so when running in the Flatpak environment, we do it differently, by "copying" the runtime to a temporary directory and modifying the copy to be the way we need it to be. The copying is actually done with hard links (like `cp -al`) so it doesn't really use extra disk space.

This copying process is meant to copy symlinks as symlinks instead of following them (again, like `cp -al`), so it shouldn't have a problem with cyclic symlinks like `/usr/bin/X11 -> .`.

When you're running native Steam on the host system, this code path shouldn't be used anyway, so the contents of the `tmp-` directory shouldn't actually matter...

Do you have a file `var/copy-runtime` in the broken version of `SteamLinuxRuntime_soldier`? In some older versions, this flag file was created if you try to run pressure-vessel in a Flatpak environment. It pushes pressure-vessel onto the code path where the runtime gets copied and modified in-place, even when you move to running it outside Flatpak.

**Comment by axelgenus** [comment]
> Do you perhaps have both `/usr/bin/X11` and `/usr/bin` included as separate entries in your `PATH`, or something like that?
Uhm, no... this is my PATH environment variable:

```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/11/bin
```

> It's OK that you can't read the directory you are not meant to be able to read :-)
Agreed. I was just wondering why Steam needs to access that folder...

**Comment by smcv** [comment]
> I was just wondering why Steam tries accessing that directory

Do you have evidence that it does, or are you just guessing from the NSS warning?

I would expect that Steam is trying to load the public certificates, which are in `/etc/ssl/certs/ca-certificates.crt` or `/etc/ssl/certs/${eight_hex_digits}.0` on Debian/Ubuntu.

**Comment by smcv** [comment]
Am I correct to think that `var/soldier` in the broken installation is a symlink to `soldier_0.20210126.1`?

If it is, please could you do a `tree` on `soldier_0.20210126.1`? Or if it is not, please could you do a `tree` on each of `soldier` and `soldier_0.20210126.1`?

**Comment by axelgenus** [comment]
> > I was just wondering why Steam tries accessing that directory
> 
> Do you have evidence that it does, or are you just guessing from the NSS warning?

Nah, I am just guessing and I may be terribly wrong to think that. The NSS error message is in the main Steam log, not in the proton log.

> Am I correct to think that `var/soldier` in the broken installation is a symlink to `soldier_0.20210126.1`?

Yes, you are not wrong. Here is the tree of that folder: https://gist.github.com/axelgenus/24285939f7b758a4e906dd0a471387bf.

**Comment by smcv** [comment]
Please could you keep your backup of the old `SteamLinuxRuntime_soldier` around for a while?

I think I might at least see where this error is coming from (although not why!), so a later version of pressure-vessel might be able to produce better diagnostics for that failure, which would let us track down what happened.

**Comment by smcv** [comment]
Here's a thing that would be useful to try...

```
cd .../SteamLinuxRuntime_soldier
./run --verbose steam-runtime-system-info >normal.json 2>normal.log
./run --verbose --copy-runtime-into="$(pwd)/var" steam-runtime-system-info >copy.json 2>copy.log
```

Then look at the output.

Because you now have Proton games working, `normal.json` should be a big blob of JSON similar to what's in the System Information (it's the same diagnostic tool), and `normal.log` should be a log reporting that everything is basically fine. This is our baseline for what *does* work.

My theory is that `copy.json` will end up empty, and `copy.log` will show a failure similar to the one you originally reported here. If I'm right, then that means the problem is with the "make a copy" mode - which means I need to dig deeper and find out why this is failing for you, because we might need to use that mode more often in future.

You will also get a directory like `var/tmp-XXXXXX`. You can delete that - what I'm more interested in is the log.

**Comment by smcv** [comment]
I think I might see where the bug is, and I suspect it's triggered by `/etc/vulkan/icd.d/nvidia_icd.json`.

After the test in my previous comment, if `copy.log` shows the same failure as your original report, it would be useful if you could try moving `/etc/vulkan/icd.d/nvidia_icd.json` to either `/usr/local/share/vulkan/icd.d/nvidia_icd.json` or `/usr/share/vulkan/icd.d/nvidia_icd.json` (create the directory if it doesn't already exist), and then try the command with `--copy-runtime-into` again.

If I'm right, then that change will make it succeed, and I'll know which pressure-vessel bug triggered this. If not, I'll have to come up with a different theory.

After trying that, it's best for you to move `nvidia_icd.json` back to where it was originally, if that's where it normally goes on Gentoo systems.

**Comment by axelgenus** [comment]
> My theory is that copy.json will end up empty, and copy.log will show a failure similar to the one you originally reported here. 

It seems you got it.

Both logs (normal.log and copy.log): https://gist.github.com/axelgenus/f631268cb25d84699038cf80102fb913

**Comment by smcv** [comment]
Thanks for testing. You can delete your backup of the old `SteamLinuxRuntime_soldier` now that we know how to reproduce the failure with the current version.

I can reproduce this on a test system now, so I think I'm on the right track.

> I tried moving nvidia_icd.json to both location and each time the --copy-runtime execution failed with the symlink error.

I'm a bit surprised by this. Please could I see the last few lines of output before the failure? I don't need the whole log, just the last 10 lines or so.

If you see an extra line `Setting up Vulkan implicit layer JSON...` before the failure, then I think I might know what is happening. If you move `nvidia_icd.json` like before, but also move `/etc/vulkan/implicit_layer.d/nvidia_layers.json` into `/usr/local/share/implicit_layer.d`, then *that* might be enough for it to work?

(Again, this is not something I want you to do permanently, just a way to isolate what is wrong in pressure-vessel so I can fix it.)

**Comment by smcv** [comment]
I think https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/245 is going to solve this, although it's difficult to be sure.

**Comment by axelgenus** [comment]
> Thanks for testing.

No, thank you for your support. ;)

> If you move `nvidia_icd.json` like before, but also move `/etc/vulkan/implicit_layer.d/nvidia_layers.json` into `/usr/local/share/implicit_layer.d`, then _that_ might be enough for it to work?

Success! I actually did move the entire /etc/vulkan directory to /usr/local/share and that did the trick.

**Comment by smcv** [comment]
> Success! I actually did move the entire /etc/vulkan directory to /usr/local/share and that did the trick.

OK, great. Please move it back to where it ought to be, if that's where your distribution normally puts it (I don't want to break your upgrades).

Your test results are consistent with my latest theory about the root cause. It will take a bit of time for the fix to get into a beta, but when it has gone out in a public beta I'll ask you to re-test.

**Comment by axelgenus** [comment]
> when it has gone out in a public beta I'll ask you to re-test.

Sure thing. Thank you again.

**Comment by axelgenus** [comment]
I just updated SteamLinuxRuntime_soldier to the latest client_beta but here is my VERSION.txt contents:

```
#Name	Version		Runtime	Runtime_Version	Comment
SteamLinuxRuntime	v0.20210309.0-0-gb38a1fb			# Entry point scripts, etc.
**pressure-vessel	0.20210305.0+srt1**	scout	0.20210309.0	# pressure-vessel-bin.tar.gz
soldier	0.20210309.0	soldier	0.20210309.0	# com.valvesoftware.SteamRuntime.Platform-amd64,i386-soldier-runtime.tar.gz
```

I'll try again tomorrow.

**Comment by smcv** [comment]
Oh, sorry, I'm mixing up the version numbers. soldier 0.20210309.0 with pressure-vessel 0.20210305.0+srt1 is correct: please try that.

**Comment by axelgenus** [comment]
It seems to be fixed now: `copy.log` does not contain the symbolic link error anymore and it exits cleanly ("Exiting with status 0").

**Comment by smcv** [comment]
soldier 0.20210309.0 has now been released as the non-beta version (and there is a new beta). @kisak-valve, I think we can close this now, based on previous confirmation https://github.com/ValveSoftware/steam-runtime/issues/366#issuecomment-795611843
