### ISSUE TITLE
steam-runtime soldier doesnt map PROTON_LOG_DIR inside the container

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/steam-runtime#369]
#### Your system information

* Steam Runtime Version: 0.20210208.0
* Distribution (e.g. Ubuntu 18.04): Gentoo
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  https://gist.github.com/farmboy0/16f79f8c08e6062bb1cf5365963499ce#file-steam-system-information
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
In order to not have Proton clutter my home directory with log files I have set PROTON_LOG_DIR to another custom path
(/mnt/work/SteamTools/logs to be exact).

I was wondering why Proton 5.13 doesnt create any log files. Looks like PROTON_LOG_DIR doesnt work with the container. Unsetting the variable made Proton write logs again (to my home directory)

#### Steps for reproducing this issue:

1. Enable logging in Proton 5.13 i.e. with user_settings.py
2. Set PROTON_LOG_DIR to some custom directory
3. Run a game with Proton 5.13

**Comment by RyuzakiKK** [comment]
I suspect this is happening because pressure-vessel doesn't know that you need this custom directory, so it doesn't mount it inside the container.

Does it work if you manually teach pressure-vessel to share your directory?
You can do it by setting the `PRESSURE_VESSEL_FILESYSTEMS_RW` environment variable, either in the specific game launch options, e.g. `PRESSURE_VESSEL_FILESYSTEMS_RW=/mnt/work/SteamTools/logs %command%`, or globally, e.g. launching Steam from a terminal as `PRESSURE_VESSEL_FILESYSTEMS_RW=/mnt/work/SteamTools/logs steam`.

**Comment by farmboy0** [comment]
Yes, that works.

**Comment by smcv** [comment]
Please use that workaround for now. The next beta should make the workaround unnecessary.

**Comment by farmboy0** [comment]
This seems to be fixed, I excluded my logs directory from PRESSURE_VESSEL_FILESYSTEMS_RW and ran Path of Exile and the Protonm log was still written.

**Comment by smcv** [comment]
Thanks for confirming. This improvement will make its way into the non-beta branch at some point in the future.

**Comment by smcv** [comment]
0.20210309.0 has been released as the production version, so this should now be fixed even without using the beta. @kisak-valve, I think we can close this based on the confirmation in https://github.com/ValveSoftware/steam-runtime/issues/369#issuecomment-796979914.
