### ISSUE TITLE
life is strange is going into out of memory with `SDL_VIDEODRIVER=wayland` and SLR

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/steam-runtime#370]
#### Your system information

* Steam Runtime Version: steam-runtime_0.20201203.1
* Distribution (e.g. Ubuntu 18.04): Kubuntu 20.10
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/soredake/ed1fa30f885371dda5f331815920a3ae
  
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:

Life is Strange is going out of memory after starting when using `SDL_VIDEODRIVER=wayland` and SLR.

Log:
[lis_wayland_slr.log](https://github.com/ValveSoftware/steam-runtime/files/6049369/lis_wayland_slr.log)

</details>

</details>

#### Steps for reproducing this issue:

1. Download lis on KDE/Wayland
2. Set `SDL_VIDEODRIVER=wayland` and SLR for lis
3. Start it

**Comment by smcv** [comment]
Didn't you just close this issue? (#232)

You're running a game from 2015, on a library stack that is, as much as possible, taken from 2012, while forcing it to use a graphics API that SDL still doesn't use by default due to significant compatibility issues. This is not something game developers of Valve are putting any QA into, and not something that is ever going to be particularly reliable.

The most likely solution to this is for the scout container runtime to force `SDL_VIDEODRIVER=x11`, so that games compiled against scout always go via Xwayland... but because SDL's default is `x11`, you can already have that behaviour, by just not setting `SDL_VIDEODRIVER`.

If Steam gets a way for newer games to be compiled against a newer runtime (soldier or newer) and run in a container with that runtime, then *those* games are a lot more likely to work with native Wayland. However, that mechanism does not yet exist, and even if it did, games published in 2015 would not be using it.

**Comment by soredake** [comment]
> 
> 
> Didn't you just close this issue? (#232)
> 
> You're running a game from 2015, on a library stack that is, as much as possible, taken from 2012, while forcing it to use a graphics API that SDL still doesn't use by default due to significant compatibility issues. This is not something game developers or Valve are putting any QA into, and not something that is ever going to be particularly reliable. The `libwayland` in scout is just too old.
> 
> The most likely solution to this is for the scout container runtime to force `SDL_VIDEODRIVER=x11`, so that games compiled against scout always go via Xwayland... but because SDL's default is `x11`, you can already have that behaviour, by just not setting `SDL_VIDEODRIVER`.
> 
> If Steam gets a way for newer games to be compiled against a newer runtime (soldier or newer) and run in a container with that runtime, then _those_ games are a lot more likely to work with native Wayland. However, that mechanism does not yet exist, and even if it did, games published in 2015 would not be using it.

Game works without SLR now, with SLR it goes into out of memory.
