### ISSUE TITLE
I just got a bug when starting my game on steam

### ISSUE THREAD

**Issue by zouyonghe** [ValveSoftware/steam-runtime#386]
#### Your system information

* Steam Runtime Version: 1.0.0.69-1(pacman--steam-native-runtime)
* Distribution (e.g. Ubuntu 18.04): arch rolling
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/zouyonghe/ff478f173cabefc8cf95ccee9d11e74c
  
* Have you checked for system updates?: [Yes/No]Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:

The game Sakuna Of Rice and Ruin did not start normally.It just showed it was running and then stopped.

#### Steps for reproducing this issue:

1. Open the terminal
2. Run: PRESSURE_VESSEL_VERBOSE=1 steam 2>&1 | tee ~/pressure-vessel.log
3. Start the game
4. It just stopped

Here is the log:
[pressure-vessel.log](https://github.com/ValveSoftware/steam-runtime/files/6197771/pressure-vessel.log)
Thanks for your help

**Comment by RyuzakiKK** [comment]
The Vulkan check is failing, even outside the container, with:
```
"ERROR at /usr/src/packages/BUILD/vulkaninfo/vulkaninfo.h:644:vkCreateInstance failed with ERROR_OUT_OF_HOST_MEMORY"
```
Which is quite odd. Is `/usr/src/packages/BUILD/vulkaninfo` something that you have manually added on your machine?

And then regarding the bwrap error, it seems to be caused by the fact that you are storing Steam games under the `/usr/` directory. For more info https://github.com/ValveSoftware/steam-runtime/issues/288#issuecomment-717954844

You can try to move your game to another location, e.g. `/home/` or `/media/`, and check if that solves your issue.

**Comment by kisak-valve** [comment]
Hello @zouyonghe, it looks like the Vulkan render paths are broken on your system with `vkCreateInstance failed with ERROR_OUT_OF_HOST_MEMORY`. I think I've seen this before from a bad interaction with AMDVLK like https://github.com/Frogging-Family/nvidia-all/issues/7.

Please uninstall the `amdvlk` and `lib32-amdvlk` system packages and retest.

**Comment by zouyonghe** [comment]
I will try the method you provide. Thank you for your help.

**Comment by zouyonghe** [comment]
Thanks a lot!
It was useful that just solved my bug.
