### ISSUE TITLE
No native wayland games start.I get the error "SDL_Init(SDL_INIT_VIDEO) failed:wayland not available"

### ISSUE THREAD

**Issue by Toadfield** [ValveSoftware/steam-runtime#396]
#### Your system information

* Steam client version (build number or date): 1.0.0.70
* Distribution (e.g. Ubuntu): Arch KDE with Wayland and kernel 5.4.15
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I was using X11 in the past and everything worked,but I switched to wayland and the native wayland games just don't work.
If I open a native Wayland game,then this error message appears:"SDL_Init(SDL_INIT_VIDEO) failed:wayland not available"
All the xwayland games work flawlessly.
I tested some native Wayland applications that are not steam games and they all worked.

#### Steps for reproducing this issue:

1. Install Wayland
2. Open Steam
3. Execute any wayland game

**Comment by kisak-valve** [comment]
Hello @Toadfield, I've transferred this issue because this reads like a Steam runtime issue instead of a Steam client issue, and is likely the same scenario as #232.

**Comment by smcv** [comment]
> Install Wayland

Wayland is a protocol, not an implementation, so this is a bit like saying "Install HTTP". Probably you mean installing the packages that make KDE Plasma act as a Wayland compositor?

> the native wayland games

Which games, specifically?

How are you running those games? Are you using the **Steam Linux Runtime** compatibility tool for them?

**Comment by Toadfield** [comment]
> Wayland is a protocol, not an implementation, so this is a bit like saying "Install HTTP". Probably you mean installing the packages that make KDE Plasma act as a Wayland compositor?

Yea,I mean the "wayland-session" package.

> Which games, specifically?

I tried it with CS:GO and Gmod.
I know that there are separate issue trackers for those games,but I don't know if that bug would happen on other native wayland games or not,I don't have any to test,are there any free ones that I can test?

> Are you using the Steam Linux Runtime compatibility tool for them?

Yea

**Comment by Toadfield** [comment]
I looked at https://github.com/ValveSoftware/steam-runtime/issues/232 and the games still don't work with `SDL_VIDEODRIVER=wayland`.
Btw what do you mean by "the container" and "LD_LIBRARY_PATH"?

**Comment by smcv** [comment]
The short answer is that the Steam Runtime is based on an OS from 2012, which is far too old for Wayland to work well. If you let SDL do what it does by default, your game will use X11 via Xwayland and should work fine. If you force it to use Wayland but *don't* use the "Steam Linux Runtime" compatibility tool, it might work if you're lucky.

If you force it to use Wayland, *and also* force it to run in a very strict Steam Runtime environment (which is what the "Steam Linux Runtime" compatibility tool does), then it's [not going to work](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/steamlinuxruntime-known-issues.md#common-issues-and-workarounds-specific-to-scout

), because the libraries you're using to run the game are travelling back in time to 2012, when Wayland wasn't ready.

> Btw what do you mean by "the container" and "LD_LIBRARY_PATH"?

Steam runs games in a special library stack, the Steam Runtime. All native Linux games on Steam currently use Steam Runtime version 1, 'scout', which is based on Ubuntu 12.04 (newer runtimes exist, but they are only used for Proton at the moment).

By default, all native Linux games on Steam run in a mixture of the libraries from your operating system (Arch) and the Steam Runtime version 1. If a library in your operating system is compatible with the version from the Steam Runtime, and it's newer, then it will be used instead of the one from the Steam Runtime. In particular, you'll usually get `libwayland-client.so.0` and `libSDL2-2.0.so.0` from 2021, even though the `libwayland-client.so.0` in the Steam Runtime is from 2012.

The problem with that approach is that often the libraries in the operating system appear to be compatible with the ones in the Steam Runtime, but are not actually 100% compatible, causing weird crashes. It's easy to get a game that works for me but doesn't work for you - or more importantly, works for the game developer, but not for you.

The "Steam Linux Runtime" compatibility tool runs the game in a container - a bit like Flatpak. This is a very strict Steam Runtime 1 'scout' environment where most of the libraries from your host system are not used or available. The only libraries from the host system that get used are your graphics drivers and Vulkan layers. Not all games work in this environment, because some games make assumptions that they are not meant to, but for the games that *do* work in this environment, if they work for me they will probably also work for you.

The version of SDL that's included in the Steam Runtime had to be compiled with native Wayland disabled, because the Steam Runtime is based on an operating system from 2012, with a `libwayland-client.so.0` from 2012, and that's several years too old for what the native Wayland video driver in SDL needs.

If we start to get games compiled against a newer runtime (Steam Runtime 2 or higher), those games will also have to run in a container, but they will be able to do native Wayland, because it's a newer container.

**Comment by smcv** [comment]
#232 has more background on this. The symptom is different now, because instead of an old version of SDL that would try (but then fail) to use native Wayland, the Steam Runtime now has a newer version of SDL, where the Wayland backend had to be disabled because it couldn't be compiled against such old libraries.

Are these games automatically choosing to use Wayland with no action from you, or did you or your OS distribution specifically set `SDL_VIDEODRIVER=wayland`?

Backporting a modern libwayland-client into a library stack from nearly a decade ago is unlikely to be straightforward: one of the reasons for the container runtime effort is to escape from the situation where we can only use libraries multiple years old.

The most likely solution to this is for the container runtime setup to detect `SDL_VIDEODRIVER=wayland` and turn it off when running on Steam Runtime version 1, which will result in the games falling back to X11/Xwayland.

**Comment by Toadfield** [comment]
> The "Steam Linux Runtime" compatibility tool runs the game in a container - a bit like Flatpak. This is a very strict Steam Runtime 1 'scout' environment where most of the libraries from your host system are not used or available. The only libraries from the host system that get used are your graphics drivers and Vulkan layers. Not all games work in this environment, because some games make assumptions that they are not meant to, but for the games that do work in this environment, if they work for me they will probably also work for you.

To be sure,if I use the package "Steam (runtime)" and not the "Steam-Native" package,then it will run it with that container properly?

> Are these games automatically choosing to use Wayland with no action from you, or did you or your OS distribution specifically set SDL_VIDEODRIVER=wayland?

I looked into a file and it seems that I have selected that env var to work globally.
So do I need to start steam with a env var that disables that?
If "Yes",then how is that env var calles?

**Comment by smcv** [comment]
> I looked into a file and it seems that I have selected that env var to work globally

I assume you did this for a reason?

> So do I need to start steam with a env var that disables that?

Please try starting Steam with `SDL_VIDEODRIVER=wayland` not set, for example `env -u SDL_VIDEODRIVER steam` or `unset SDL_VIDEODRIVER; steam`, or put `env -u SDL_VIDEODRIVER %command%` in a game's launch options.

Or, you could force the use of the default X11 driver: `SDL_VIDEODRIVER=x11 steam`, or `SDL_VIDEODRIVER=x11 %command%` in a game's launch options.

> To be sure,if I use the package "Steam (runtime)" and not the "Steam-Native" package,then it will run it with that container properly?

"Steam (runtime)" is Arch Linux's name for the way Steam is designed to work. It lets Steam set up the `LD_LIBRARY_PATH` runtime that I described. This is used for Steam itself, and for games where you have **not** selected "Steam Linux Runtime".

Steam-Native is an Arch Linux thing that we cannot support. It disables the `LD_LIBRARY_PATH` runtime, which can break games where you have **not** selected "Steam Linux Runtime".

Games where you **have** selected "Steam Linux Runtime" will always run in the container, regardless of whether you are using "Steam (runtime)" or Steam-Native to run Steam itself.

**Comment by smcv** [comment]
Newer versions of pressure-vessel (>= 0.20210430.0) automatically check for `SDL_VIDEODRIVER=wayland` and disable it when using the scout runtime. This change has been released in "Steam Linux Runtime" version 0.20210430.0, currently on the `client_beta` branch.

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by JohnTheCoolingFan** [comment]
Trying to do the last solution didn't help much. For instance, in Team Fortress 2 even if pressure vessel is enabled, sdl still tries to use wayland. If I launch steam with that variable, the game starts but then fails to load post intro screen.

I'm using Arch Linux, Sway DE. Opted into steam beta.

**Comment by smcv** [comment]
@JohnTheCoolingFan: My 2021 comment might not be relevant any more, because a lot has changed in 2 years. Please open a separate issue with full details of your system, including:

* the Steam Runtime diagnostics;
* any configuration that you know is special on your system, for example if you have forced `SDL_VIDEODRIVER=wayland` via `.bashrc` or similar;
* which games are affected/unaffected;
* any workarounds that you have tried (successfully or unsuccessfully): for example it sounds as though you have tried enabling/disabling "Properties -> Compatibility -> Steam Linux Runtime 1.0 (scout)" for TF2 and it does not make any difference

In the case of TF2, I think it's still using its own bundled copy of SDL rather than the Steam Runtime's, which means there is nothing that we can do within the Steam Runtime's SDL to change the behaviour of TF2's SDL; but Portal, Portal 2, Tomb Raider (2013) and Life Is Strange are examples of games that *do* use the Steam Runtime's SDL.

**Comment by beattie19** [comment]
Just wanted to note that setting the launcher option of `env -u SDL_VIDEODRIVER %command%` worked for me when I was getting the following error running Into The Breach on Omarchy - `"SDL Error: wayland,x11 not available"`

**Comment by smcv** [comment]
I would (still) not recommend setting `SDL_VIDEODRIVER=wayland`. Newer versions of SDL default to using native Wayland, if it is safe to do so, even without that environment variable. In the older versions of SDL that defaulted to X11, that default was there for a reason - the native Wayland backend has/had known compatibility or performance issues with some games and some Wayland compositors, so the SDL maintainers' judgement was that it is safer to use the X11 backend and Xwayland.

If you force this non-default behaviour anyway, then you can expect to have to apply workarounds to some individual games as a result.

> Just wanted to note that setting the launcher option of `env -u SDL_VIDEODRIVER %command%` worked for me when I was getting the following error running Into The Breach on Omarchy - `"SDL Error: wayland,x11 not available"`

This is a different issue, really. Into The Breach bundles an older copy of SDL 2 at `linux_x64/libSDL2-2.0.so.0`, which is too old for the workaround described in https://github.com/ValveSoftware/steam-runtime/issues/396#issuecomment-831873563 to work - but that copy is probably also too old for `SDL_VIDEODRIVER=wayland` to work well, either.

There is not much that the Steam Runtime can do about games that bundle an outdated copy of a library: problems with the files included in a game are something that the game publisher/developer would need to resolve. Valve's policy is to not edit the contents of games: they are just distributing what they were given by the game's publisher, as-is.

For SDL 2 specifically, setting launch options to `STEAM_COMPAT_RUNTIME_SDL2=1 %command%` or `STEAM_COMPAT_RUNTIME_SDL2=sdl2-compat %command%` can sometimes bypass a bundled copy of SDL 2, but this is not really something that we can safely force by default, because the bundled copy might contain game-specific changes. As a result, this is another non-default configuration which can be used at your own risk, but will not work for every game.
