### ISSUE TITLE
Issues with Multiple GPUs?

### ISSUE THREAD

**Issue by stack123-afk** [ValveSoftware/steam-runtime#401]
I have steam installed and use proton to play various games.

I originally had one NVIDIA GPU  (RTX 2080)  and was happily gaming on Linux  using proton with no issues,

I  installed a additional NVIDA GPU and now all the games I run from steam are running on the CPU, i.e. proton is not using my GPU, why? how can I fix it? 

Note:  I attempted reinstalling steam to no avail. 

Note 2: both GPUs work and drivers fully installed.

**Comment by kisak-valve** [comment]
Let's treat this as a Pressure Vessel issue until there's a stronger indication the issue is elsewhere. Proton 5.13 and newer is run inside the Steam Linux Runtime - Soldier container environment, and Pressure Vessel is what sets that up. Please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by stack123-afk** [comment]
Gist to system info:
https://gist.github.com/stack123-afk/5411c2a50d4bcca2b080cfe453cc60e3

**Comment by kisak-valve** [comment]
Thanks, your system information is telling us that Steam is running on llvmpipe, which is mesa's faster CPU renderer and the nVidia driver install is broken.

There are lines like:
`/usr/lib/i386-linux-gnu/libGLX_nvidia.so.460.39`
`renderer" : "NVIDIA VDPAU Driver Shared Library  460.56  Tue Feb 23 23:19:15 UTC 2021\n",`
`"library_link" : "libvdpau_nvidia.so.460.56"`
`"library_path" : "/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.460.39"`
Which hint that your system is halfway between two driver versions. The nVidia proprietary requires that the running kernel module, 32 bit userspace, and 64 bit userspace have the exact same version to work properly, which you do not have.

**Comment by stack123-afk** [comment]
@kisak-valve  I see; should reinstalling the nvidia driver solve this issue then?

**Comment by CSahajdacny** [comment]
So, does Proton support a second Nvidia card for Physx, like Windows or is not supported yet?

**Comment by smcv** [comment]
> should reinstalling the nvidia driver solve this issue then?

Hopefully. Try it?

Since you seem to be using Ubuntu, I would suggest using the NVIDIA driver that's available via Ubuntu.

I don't know which of your GPUs will be chosen. Vulkan GPU discovery is complicated already, the container adds a new layer of complexity, and then Proton (including DXVK and Wine) just adds to that. If the GPU you want isn't being selected, you might have to set the `__NV_PRIME_RENDER_OFFLOAD_PROVIDER` environment variable as described in [NVIDIA's documentation](http://us.download.nvidia.com/XFree86/Linux-x86_64/460.56/README/primerenderoffload.html).

> does Proton support a second Nvidia card for Physx?

I don't know. Try it?

The Steam Runtime doesn't do anything special to enable multiple NVIDIA cards, but it doesn't do anything special to disable them either. Programs running in the container environment (like Proton) should be able to see both GPUs. Anything after that is up to Proton or the games to deal with.

**Comment by stack123-afk** [comment]
@smcv  @kisak-valve  Thank you reinstalling the drivers from scratch seems to have solved the issue!
