### ISSUE TITLE
Attempting to run game using proton immediately crashes

### ISSUE THREAD

**Issue by Webatron11** [ValveSoftware/steam-runtime#416]
#### Your system information

* Steam Runtime Version: Soldier
* Distribution (e.g. Ubuntu 18.04): Gentoo
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/Webatron11/02bafa62f9969536c218973e907abea2
  
* Have you checked for system updates?: [~Yes~/No]
* Are you using the Steam Linux Runtime compatibility tool?: [~Yes~/No]

#### Please describe your issue in as much detail as possible:

Upon attempting to run a non-linux native game, it looks like it is starting but then promptly goes back to saying play. Works on any game that would use Proton.

Logs as instructed: https://dpaste.com/6VGUXL6N8

#### Steps for reproducing this issue:

1. Install non-linux game
2. Attempt to run using Proton

**Comment by RyuzakiKK** [comment]
`bwrap: Can't mkdir /usr/lib64/gconv: Read-only file system`

In the past this issue was caused by a partially extracted Soldier runtime.

Can you try to switch to the `client_beta` version of Soldier? This new version provides the runtime as already extracted, so there are less things that could go wrong.  Here you can find more info on how to choose the beta version https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version

Otherwise you can also try to remove the directory `/home/dakka/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.2021*`, because when it is missing, pressure-vessel will attempt to extract it again.

**Comment by Webatron11** [comment]
The fix about enabled me to start the game, but now it gives me an error regarding a missing library. I do not think this applies to the Steam Runtime anymore however, so I will close the issue for now.
