### ISSUE TITLE
fatal error: cannot find 'ld' When Building with GCC 9 in Soldier

### ISSUE THREAD

**Issue by d10sfan** [ValveSoftware/steam-runtime#468]
#### Your system information

* Steam Runtime Version: registry.gitlab.steamos.cloud/steamrt/soldier/sdk:0.20210906.1
* Distribution (e.g. Ubuntu 18.04): sdk:0.20210906.1
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): N/A
  
* Have you checked for system updates?: [Yes/No] N/A
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Steam Linux Runtime Soldier
* If you are using Steam Linux Runtime for native Linux games: N/A
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: N/A

#### Please describe your issue in as much detail as possible:
I was attempting to build with the provided gcc 9 in the soldier docker image (registry.gitlab.steamos.cloud/steamrt/soldier/sdk:0.20210906.1) due to issues with gcc 8 with the particular project.
I ran the following commands to attempt to set gcc 9 as the default, which has worked with similar systems in the past:

```sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
sudo update-alternatives --set gcc "/usr/bin/gcc-9"
sudo update-alternatives --set g++ "/usr/bin/g++-9"
export CXX='g++-9'
export CC='gcc-9'
```

It seems to have been failing at the linking stage, with this error below:

 ```/usr/bin/g++-9 -Werror=delete-non-virtual-dtor -Wno-conversion-null -fuse-ld=lld  -Werror=delete-non-virtual-dtor -Wno-conversion-null -fuse-ld=lld -O2 -ftree-vectorize -ffast-math  Source/XPrm/CMakeFiles/XPrm.dir/StdAfx.cpp.o Source/XPrm/CMakeFiles/XPrm.dir/Token.cpp.o Source/XPrm/CMakeFiles/XPrm.dir/XPrm.cpp.o -o Source/XPrm/XPrm  Source/XTool/libXTool.a  /usr/lib/x86_64-linux-gnu/libSDL2.so  -lpthread  Source/Exodus/libExodus.a  -ldl && :
collect2: fatal error: cannot find 'ld'
compilation terminated.
```

This was an attempt to build this project: https://github.com/KranX/Perimeter

GCC 8 had issues completing the build of dxvk-native

Also, there was another build for another project that I needed gcc 9 for that when I used the gcc 9 commands above, it complained about missing libgcc_s libraries. I was able to work around it with this, but it seems strange:

```
cp -rfv /usr/lib/gcc/x86_64-linux-gnu/8/libgcc*.so* /usr/lib/gcc-9/lib/
```

#### Steps for reproducing this issue:

1. Create a docker container based on the image above.
2. Attempt to switch to gcc 9 and build a project
3. Build fails with linking errors

**Comment by TTimo** [comment]
Hello @d10sfan,

`steamrt-soldier` is not available as a selectable runtime for running native Steam titles at this time. This will change in the near future but at this time soldier is only used internally by the Steam client for Proton.

The same version of gcc 9 is available in `steamrt-scout` however, so maybe give that a try first?

You might also want to clarify if the problem you are trying to solve is `update-alternatives` not working or a problem with the gcc 9 backport, or a problem with the build system of the software you are trying to compile.

FWIW we have worked with the gcc 9 backport at Valve - we didn't use `update-alternatives`, our build system seemed happy enough with an `export CXX=` type of approach.

**Comment by d10sfan** [comment]
@d10sfan Is steamrt-scout available as a buildable target with gcc 9? The last time I tried that, it was the ubuntu 12.04 target with very old dependencies. I'm building against this for a compatibility tool similar to proton.

I'll see if there's an issue with one of those steps, it did seem to work ok for more normal ubuntu-based distros (by installing the backports gcc 9).

**Comment by smcv** [comment]
> Is steamrt-scout available as a buildable target with gcc 9?

Yes:

```
$ podman pull registry.gitlab.steamos.cloud/steamrt/scout/sdk
$ podman run -it --rm registry.gitlab.steamos.cloud/steamrt/scout/sdk
(steamrt scout 0.20210906.1)root@609bc3219b1c:/# gcc-9 --version
gcc-9 (SteamRT 9.3.0-17+steamrt1.3+srt1) 9.3.1 20210309
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Binaries compiled by this `gcc-9` (or `g++-9`) should in principle work in either the ordinary `LD_LIBRARY_PATH` scout runtime, or the "Steam Linux Runtime" container environment (so your compat tool will be "the same shape" as Proton 5.0).

**Comment by d10sfan** [comment]
@smcv I just tried that image running in docker, and got the following error trying to clone a git repository:


```
(steamrt scout 0.20210906.1)root@7d48130192c7:~# git clone git@github.com:luxtorpeda-dev/packages.git
Cloning into 'packages'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
(steamrt scout 0.20210906.1)root@7d48130192c7:~# 
```

Is git expected to work in this environment? On an older version of this and the newer soldier, this was working ok.

I'll see as well if there's something I'm doing wrong in trying to switch to gcc-9 on the soldier  runtime.

**Comment by smcv** [comment]
> the ubuntu 12.04 target with very old dependencies

Yes, scout is and always will be based on Ubuntu 12.04, with very old dependencies. It has to be - otherwise, users of old distros like Debian 8 and Ubuntu 14.04 would be unable to run games and compatibility tools compiled on scout. We backported gcc 9 and binutils 2.30 into that environment.

The backported gcc 9 is specially configured to always link `libgcc` and `libstdc++` statically, similar to `gcc -static-libgcc -static-libstdc++`. This was necessary because we cannot rely on all Steam users having a libgcc and libstdc++ as new as that. If you are using complicated compiler options, you might need to make sure it is still linking those libraries statically, or force it with `-static-libgcc -static-libstdc++`.

`gcc-9` and `g++-9` are actually wrapper scripts that set up the `PATH` so that they will find the linker, etc. from `binutils-2.30` instead of the default Ubuntu 12.04 toolchain, which is too old.

The backported gcc-9 in soldier is very similar to the one in scout, but it doesn't need to use a special build of binutils.

I would recommend not using `update-alternatives`. Other components in the Steam Runtime ecosystem can still assume that the default gcc is version 5 or older.

> Attempt to switch to gcc 9 and build a project

We do have some automated tests that are run every time we update the Docker container, which build trivial C and C++ projects with this version of gcc: [g++9](https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/scout/tests/sdk/g++-9.t) [g++-9-m32](https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/scout/tests/sdk/g++-9-m32.t) [gcc-9](https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/scout/tests/sdk/gcc-9.t) [gcc-9-m32](https://gitlab.steamos.cloud/steamrt/steamrt/-/blob/steamrt/scout/tests/sdk/gcc-9-m32.t). Obviously those are very simple C and C++ projects (it already takes a long time to build and test a new version, so we don't want to make it any slower!) so your project will be a lot more complicated. If you can reproduce an issue with a minimized project that is as small as possible, we are more likely to be able to solve it.

> Also, there was another build for another project that I needed gcc 9 for that when I used the gcc 9 commands above, it complained about missing libgcc_s libraries

To avoid creating too-new dependencies, linking libgcc (and libstdc++) statically is the only way to use these compiler backports.

> `cp -rfv /usr/lib/gcc/x86_64-linux-gnu/8/libgcc*.so* /usr/lib/gcc-9/lib/`

Please don't do that, it is not correct and could lead to subtle failures.

In [the earlier version of this issue report](https://gitlab.steamos.cloud/steamrt/steamrt/-/issues/16) you mentioned:
>  /usr/bin/g++-9 -Werror=delete-non-virtual-dtor -Wno-conversion-null -fuse-ld=lld  -Werror=delete-non-virtual-dtor -Wno-conversion-null -fuse-ld=lld -O2 -ftree-vectorize -ffast-math  Source/XPrm/CMakeFiles/XPrm.dir/StdAfx.cpp.o Source/XPrm/CMakeFiles/XPrm.dir/Token.cpp.o Source/XPrm/CMakeFiles/XPrm.dir/XPrm.cpp.o -o Source/XPrm/XPrm  Source/XTool/libXTool.a  /usr/lib/x86_64-linux-gnu/libSDL2.so  -lpthread  Source/Exodus/libExodus.a  -ldl && :

I would not recommend `-fuse-ld=lld` with this toolchain. `lld` is part of LLVM, but we have not backported a version of LLVM that is of the same age as gcc 9. The only tested linker for this gcc 9 backport is the one from GNU binutils.

I don't know whether Valve-internal builds have been using the older `ld.bfd` (`g++-9 -fuse-ld=bfd`) or the newer `ld.gold` (`g++-9 -fuse-ld=gold`). You could try both?

**Comment by d10sfan** [comment]
Thank you for the explanation, I'll investigate that with the gcc-9 backport.

**Comment by smcv** [comment]
> `error: cannot run ssh: No such file or directory`

There is no ssh client in the SDK. If you are cloning a git repo inside the SDK container, please use its `https://` address. That will also avoid having to give the Docker container access to your ssh public key or password!

If you really need `ssh` (or any other development tool, within reason), you can get it from Debian 10. The container's apt sources are preconfigured to use the `deb.debian.org` CDN.

**Comment by d10sfan** [comment]
Ah right, used to doing that locally, so mixed that up. I'll investigate what I can do with gcc 9 on the tool. Thanks

**Comment by d10sfan** [comment]
@smcv Thank you for the explanation, that helped alot, appreciate the help and patience.

It looks like removing the update alternatives and using gold fixed the issues. That particular project was also setting lld as the default, which I disabled. Now all I'm doing to switch to gcc and gold is below:

```
    export CXX='g++-9'
    export CC='gcc-9'
    export CXXFLAGS='-fuse-ld=gold'
```
