### ISSUE TITLE
Game doesn't start - World War Z Aftermath

### ISSUE THREAD

**Issue by aha999** [ValveSoftware/steam-runtime#469]
#### Your system information

* Steam Runtime Version: **where can i find this ?**
* Distribution (e.g. Ubuntu 18.04): Pop!OS 21.04 
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/):  [gist link](https://gist.github.com/aha999/b2ac6f37cd1d08f9af888161c4178a12)
  
* Have you checked for system updates?: YES
* What compatibility tool are you using?: Proton 6.3-6
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`? **where can i find this ?**
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`? **where can i find this ?**

#### Please describe your issue in as much detail as possible:

I try to play World War Z Aftermath that i just purchased and installed to a second drive (ntfs formatted), but it  doesn't even start.
log code: [gist link](https://gist.github.com/aha999/d5e0a8d1afdbf3912bffc2469d757637)

#### Steps for reproducing this issue:

1. Install World War Z aftermath
2. Enable Proton
3. Game doesn't start

I'm sorry if i couldn't yet provide all the information, i hope someone can advise where can i find the files.

**Comment by kisak-valve** [comment]
Hello @aha999, Proton interacting with NTFS is known to be finicky, and using a native Linux filesystem instead is recommended.

Looking at your system information, the Steam Linux Runtime - Soldier container environment looks healthy. I don't think your issue is on that side. You could give the community workarounds at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a try.

There are already [several issue reports](https://github.com/ValveSoftware/Proton/search?q=NTFS&type=issues) tracking Proton's behavior with NTFS on the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues) tracking NTFS issues.

Closing as not a Steam runtime issue.

**Comment by aha999** [comment]
I'm stressing over being unable to play.  I  ordered a new secondary 2tb drive to transfer the files over and use it as ext4 as it should be instead of proprietary standards. Will divert the issue to Proton repo if there are still issues that i can't solve myself with online search.

> Closing as not a Steam runtime issue.
Oh, i thought this repo was correct for finding user issues like this. Can you recommend me a correct support repo, Is it a Proton one that you linked?

Again, thanks a lot, your information has been extremely useful and thanks for fast response.

**Comment by kisak-valve** [comment]
Starting with Proton 5.13, Proton is run inside of the Steam Linux Runtime - Soldier container environment. From a high-level perspective, it can be difficult to distinguish if an issue is with the container or with Proton. Issues that appear to be with Pressure Vessel and the Steam Linux Runtime are tracked here, while issues with Proton and games run with Proton are tracked in the Proton issue tracker. In your specific case we know about a set of long-standing issues with Proton interacting with NTFS, which heavily suggests your issue is on Proton's side as well.
