### ISSUE TITLE
Warframe crashes after launcher

### ISSUE THREAD

**Issue by TheRealPingWin** [ValveSoftware/steam-runtime#519]
* Steam Runtime Version: Steam manjaro 1.0.074-1
* Distribution : Manjaro 21.3.2
* System and driver information: https://gist.github.com/TheRealPingWin/f8710d3000e715c373a6b949d2a13e60
  
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime / Proton 5.13+ 
* If you are using Steam Linux Runtime, or Proton 5.13 or newer:  steam-runtime-heavy_0.20220315.0

#### Please describe your issue in as much detail as possible:
After clicking play on the warframe launcher the game crashes. (No error codes just the default warframe crash windows)
Steam crash log (ran on 7.0-3 proton):
https://gist.github.com/TheRealPingWin/7c23cea7f187131e47702c071eada751

I've tried different proton versions and none of them worked. 6.10 GE-1, experimental, 7.0-3, 6.3-8, 5.0-10

#### Steps for reproducing this issue:

1. Download steam-manjaro from pamac manager
2. Install warframe from steam
3. Click play on launcher

**Comment by kisak-valve** [comment]
Hello @TheRealPingWin, since the game's launcher is working, it's unlikely your issue is with Steam Linux Runtime - Soldier.

On Proton's side, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-1194123513.

**Comment by TheRealPingWin** [comment]
Oh okay thanks.
