### ISSUE TITLE
Proton games won't start due to missing libraries in the Steam runtime container

### ISSUE THREAD

**Issue by ILadis** [ValveSoftware/steam-runtime#521]
#### Your system information

* Steam Runtime Version: 0.20220601.1 (according to system information)
* Distribution (e.g. Ubuntu 18.04): Void Linux
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/):  
  https://gist.github.com/ILadis/83dfae139805b64b2b64d2f244fff068
  
* Have you checked for system updates?: Yes, also tried beta branches
* What compatibility tool are you using?: Proton 5.13+
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20220727.64			# Overall version number
pressure-vessel	0.20220726.0			
scripts	v0.20220726.0-0-ga110829			# Entry point scripts, etc.
soldier	0.20220726.0	soldier	0.20220726.0	# soldier_platform_0.20220726.0/
```

#### Please describe your issue in as much detail as possible:

Any game that requires proton to launch does not start anymore. I also tried switching to the latest beta releases (for both proton and the steam runtime soldier).

When inspecting the console output of steam I see the following error during proton setup:

```
Traceback (most recent call last):
  File "/home/ladis/.local/share/steam/steamapps/common/Proton - Experimental/proton", line 20, in <module>
    from ctypes import CDLL
  File "/usr/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

I also ran steam with `PRESSURE_VESSEL_VERBOSE=1 steam` and recorded the output, see [here](https://gist.github.com/ILadis/e4aa63e7fb5ca0a81e0f1776cad6811e).  
I am using a bind mount for the `$STEAMROOT` as described in [this comment](https://github.com/ValveSoftware/steam-runtime/issues/518#issuecomment-1197254602) from a recent issue.

**Comment by RyuzakiKK** [comment]
The interesting part seems to be:
```
pressure-vessel-adverb[19627]: D: regenerate_ld_so_cache: final ld.so.conf: 
pressure-vessel-adverb[19627]: D: Output:
/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu: (from /run/pressure-vessel/ldso/ld.so.conf:1)
/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu: (from /run/pressure-vessel/ldso/ld.so.conf:2)
/lib/i386-linux-gnu: (from /etc/ld.so.conf.d/i386-linux-gnu.conf:3)
	ld-linux.so.2 -> ld-2.28.so
/usr/local/lib: (from /etc/ld.so.conf.d/libc.conf:2)
/lib/x86_64-linux-gnu: (from /etc/ld.so.conf.d/x86_64-linux-gnu.conf:3)
	ld-linux-x86-64.so.2 -> ld-2.28.so
/usr/lib: (from <builtin>:0)
/usr/lib64: (from <builtin>:0)
/lib/i386-linux-gnu/sse2: (hwcap: 0x0000000000000001) (from /etc/ld.so.conf.d/i386-linux-gnu.conf:3)

pressure-vessel-adverb[19627]: D: Diagnostic output:
/sbin/ldconfig: Can't stat /usr/local/lib/i386-linux-gnu: No such file or directory
/sbin/ldconfig: Path `/usr/lib/i386-linux-gnu' given more than once
(from /etc/ld.so.conf.d/i386-linux-gnu.conf:4 and /etc/ld.so.conf.d/i386-linux-gnu.conf:3)
/sbin/ldconfig: Can't stat /usr/local/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig: Can't stat /lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig: Can't stat /usr/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
(from /etc/ld.so.conf.d/x86_64-linux-gnu.conf:4 and /etc/ld.so.conf.d/x86_64-linux-gnu.conf:3)
/sbin/ldconfig: Can't stat /usr/libx32: No such file or directory
/sbin/ldconfig: Cannot mmap file /lib/i386-linux-gnu/libatomic.so.1.

/sbin/ldconfig: Cannot mmap file /lib/i386-linux-gnu/libcairo.so.2.11600.0.

[...] (Long list of failed mmap)
```

Can you please post the output of: `ls -l /home/ladis/.local/share/steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-JAWIQ1/lib/i386-linux-gnu`
The output of ldconfig suggests that probably the libraries in `.../lib/i386-linux-gnu/` are either missing, broken symlinks or something similar. 

Another odd thing is that all the previous temporary directories are not cleaned up because they don't have the `.ref` file.

**Comment by RyuzakiKK** [comment]
> Any game that requires proton to launch does not start anymore. I also tried switching to the latest beta releases (for both proton and the steam runtime soldier).

Just to have a confirmation, does this mean that if you switch to the stable branch of "Steam Linux Runtime - Soldier" (its `VERSIONS.txt` should say `0.20220602.55`) you still get the same issue?

You mentioned that you are using bind mounts. Can you please describe exactly what and how you are doing it? And which filesystem are you using?

**Comment by ILadis** [comment]
I switched back to the stable branch for both the Steam Client and "Steam Linux Runtime -Solider".  
The `VERSION.txt` now contains:

```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20220602.55			# Overall version number
pressure-vessel	0.20220601.0			
scripts	v0.20220527.0-0-g8669533			# Entry point scripts, etc.
soldier	0.20220601.0	soldier	0.20220601.0	# soldier_platform_0.20220601.0/
```

[Here](https://gist.github.com/ILadis/ce61d05cad362090aa76ed1131a5ae3e) is another recorded output of `PRESSURE_VESSEL_VERBOSE=1 steam` now using the stable branch. It's odd since now the "failed mmap's" are gone.

As for the bind mount, this is an excerpt of my `/etc/fstab`:

```
# /dev/nvme0n1p2
UUID=1bd99361-05ca-4392-8f0f-db1ec9ad6eee / ext4 rw,relatime,noatime 0 0

# /dev/nvme0n1p1 
UUID=0403-3ECA /boot vfat rw,relatime 0 0

# /dev/sda2
UUID=f4ec8c2f-811d-4a3e-a7ef-da41aebb1191 /home/games ext4 rw,relatime,noatime 0 0

# bindfs for steam
bindfs#/home/games/steam /home/ladis/.local/share/steam fuse mirror=ladis,group=ladis 0 0
bindfs#/home/games/steam /home/sabbi/.local/share/steam fuse mirror=sabbi,group=sabbi 0 0
```

Essentially I'm sharing the Steam installation between two user accounts. The permissions are "mirrored" to prevent any "access denied" errors.

My home directory is setup like this:

```
$ ls -al ~
drwxr-xr-x  2 ladis ladis 4.0K Aug  2 23:26 .steam
lrwxrwxrwx  1 ladis ladis   30 Aug  2 23:25 .steampath -> /home/ladis/.steam/sdk32/steam
lrwxrwxrwx  1 ladis ladis   28 Aug  2 23:25 .steampid -> /home/ladis/.steam/steam.pid

$ ls -al ~/.steam
lrwxrwxrwx  1 ladis ladis   24 Aug  2 23:25 bin -> /home/ladis/.steam/bin32
lrwxrwxrwx  1 ladis ladis   42 Aug  2 23:25 bin32 -> /home/ladis/.local/share/steam/ubuntu12_32
lrwxrwxrwx  1 ladis ladis   42 Aug  2 23:25 bin64 -> /home/ladis/.local/share/steam/ubuntu12_64
lrwxrwxrwx  1 ladis ladis   30 Aug  2 23:25 root -> /home/ladis/.local/share/steam
lrwxrwxrwx  1 ladis ladis   38 Aug  2 23:25 sdk32 -> /home/ladis/.local/share/steam/linux32
lrwxrwxrwx  1 ladis ladis   38 Aug  2 23:25 sdk64 -> /home/ladis/.local/share/steam/linux64
lrwxrwxrwx  1 ladis ladis   30 Aug  2 23:25 steam -> /home/ladis/.local/share/steam
-rwxrwxr-x  1 ladis ladis 4.1K Aug  2 23:26 registry.vdf
-rwxrwxr-x  1 ladis ladis 4.3K Jul 29 20:10 registry.vdf.bak
-rw-r--r--  1 ladis ladis    5 Aug  2 23:25 steam.pid
prw-------  1 ladis ladis    0 Jul 31 23:58 steam.pipe
-r--------  1 ladis ladis   16 Aug  2 23:25 steam.token
```

This setup has worked without any issues in the past.

**Comment by smcv** [comment]
> There is unfortunately another issue with the ./steamwebhelper on this machine at the moment, which might have a similar cause

I think this is unlikely to have much in common with any problems you are having with the container runtime. Please could you report it as a separate issue, and retitle this one to reduce its scope to just the Proton/container part?

I think the key message to differentiate your steamwebhelper issue from other people's steamwebhelper issues will be this: `ERROR:icu_util.cc(247)] Couldn't mmap icu data file`.

In general we try to keep to one bug = one issue report, otherwise it gets very confusing to keep track of which parts are fixed in which releases, and which parts still need fixing.

**Comment by smcv** [comment]
> I think this is unlikely to have much in common with any problems you are having with the container runtime

The particular reason I have for saying this is that `steamwebhelper` doesn't use the container runtime, so any bugs in the container runtime are not going to affect it.

While investigating the container runtime issue, you can use Steam in either "big picture" mode or "small" UI mode, so that the steamwebhelper is not involved in drawing the UI you need to use.

**Comment by ILadis** [comment]
Alright, I removed the `steamwebhelper` part from this issue and relabeled it accordingly. If you need anything more to investigate this issue further let me know.

Is the ValveSoftware/steam-runtime repository the right place for the `steamwebhelper` issue or is ValveSoftware/steam-for-linux a better fit?

**Comment by RyuzakiKK** [comment]
> Is the ValveSoftware/steam-runtime repository the right place for the steamwebhelper issue or is ValveSoftware/steam-for-linux a better fit?

Please open it in ValveSoftware/steam-for-linux.

**Comment by RyuzakiKK** [comment]
By looking at the logs nothing pops up as an obvious error.

Probably a quick test to iron out, or confirm, that this is really caused by bindfs is to move Soldier to another real directory and check what happens.
You can achieve that by creating a directory like `/home/ladis/additional_steam_games`. Then from the Steam client go to "Steam->Settings->Downloads->Steam Library Folders". Press the "+" button and add your new directory `/home/ladis/additional_steam_games`.
Finally from your Steam games list right click on "Steam Linux Runtime - Soldier"->Properties->Local Files->Move Install Folder and move it to the `additional_steam_games`.

**Comment by RyuzakiKK** [comment]
Ah I guess I found what's going on.

By checking bindfs changelog I saw that in the latest release 1.17.0 they mentioned: "Reverted change in 1.16.0 that made direct_io the default. It turned out to be more problematic than not having it."
And the linked issue is this one https://github.com/mpartel/bindfs/issues/117, where the user mentions that direct_io breaks several programs including `steamwebhelper`.

And by checking Void Linux repos I see that they are currently shipping bindfs 1.16.1, so not the latest version with the fix.

If that's the case, by using bindfs option `--no-direct-io` you should solve your issue (at least until you update to version 1.17.0).

**Comment by ILadis** [comment]
By using the bindfs option `--no-direct-io` both the Steam UI (`steamwebhelper`) and proton games started working again.  
Thank's for your support!
