### ISSUE TITLE
Game is unable to see workshop contents

### ISSUE THREAD

**Issue by grappas** [ValveSoftware/steam-runtime#523]
# Compatibility Report
- Name of the game with compatibility issues: Arma 3
- Steam AppID of the game: 107410

## System Information
- GPU: RX6700XT
- Driver/LLVM version:  mesa 22.1.4-1 xf86-video-amdgpu 22.0.0-1
- Kernel version:  5.18.16-arch1-1
- Full system information: https://gist.github.com/grappas/586f85acaef66226f267aea0d0b38ae3
- Proton version: Proton Experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-107410.log](https://github.com/ValveSoftware/Proton/files/9269856/steam-107410.log)
## Symptoms 

Launcher is unable to find mods on the disk drive. It sees only contents of a pfx's drive_c, home directory and nothing else.

## Reproduction

`STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/grappas/.local/share/Steam STEAM_COMPAT_DATA_PATH=/home/grappas/.local/share/Steam/steamapps/compatdata/107410 /home/grappas/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/proton run "C:"`

Before launching the game:

![obraz](https://user-images.githubusercontent.com/1036957/183107159-1eb74120-2df0-4c1a-9ef2-76cfec560720.png)

After launching the game:

![obraz](https://user-images.githubusercontent.com/1036957/183110644-f44c3f44-13eb-46c2-8427-33a5c7e8e4ec.png)

Hiding system files from game makes sense, but at least give it chance to find it's own mods ;)

Dayz has the very same issue.

**Comment by grappas** [comment]
https://gist.github.com/grappas/444b9dd3df4e5a8a5e52625f172b157a

**Comment by smcv** [comment]
Steam thinks the game is installed in `~/.local/share/Steam/steamapps`:

```
22:22:53.829736: pressure-vessel-wrap[281313]: D: 	'STEAM_COMPAT_INSTALL_PATH=/home/grappas/.local/share/Steam/steamapps/common/Arma 3
```

and as far as I know, workshop content always lives in the same library as the game itself; but Steam also thinks the game is installed in `/run/media/windows/D/SteamLibrary`:

```
22:22:53.829601: pressure-vessel-wrap[281313]: D: 	'PWD=/run/media/windows/D/SteamLibrary/steamapps/common/Arma 3'
```

So I'm confused, or Steam is confused, or both.

I think this is because it exists in both libraries, but one copy is a symlink to the other:

```
22:22:54.322735: pressure-vessel-wrap[281313]: D: /home/grappas/.local/share/Steam/steamapps/common/Arma 3 is a symlink, resolved to /run/media/windows/D/SteamLibrary/steamapps/common/Arma 3/
22:22:54.322742: pressure-vessel-wrap[281313]: D: Trying to export the target instead: /run/media/windows/D/SteamLibrary/steamapps/common/Arma 3/
```

> STEAM_COMPAT_MOUNTS=/run/media/windows/D/SteamLibrary/steamapps/workshop/content/107410:/home/grappas/.local/share/Steam/steamapps/workshop/content/107410

Are those physically different locations? Do you perhaps have half your mods in one place and half your mods in the other?

I think perhaps what has happened here might be that you moved the game from one library to the other "behind Steam's back", which only moved the actual game installation, and not the other files that should follow it around (workshop content, Wine prefix, shader cache)? The recommended way to move games between drives is to have a Steam library on each drive, and use Steam's built-in library management, which should move all the local files associated with the game as well as the game itself.

There isn't much that the container runtime can do to solve this, beyond what was done in #470. If the Steam client told us about *all* your Steam libraries (not just the one that it thinks the game is installed in), then that would ensure they were all visible, but at the moment we don't get that information.

**Comment by grappas** [comment]
> the game from one library to the other "behind Steam's back"
Answer is yes, but don't tell kissak, gonna be mad ;). Since I use both Linux and Windows from time to time this is my disk space precaution, to have one installation for both systems.

Since Soldier runtime has no problem following symlink to original game folder, why it not following symlink to workshop content folder?

**Comment by smcv** [comment]
> Since Soldier runtime has no problem following symlink to original game folder, why it not following symlink to workshop content folder by it's own (which I also made)?

Because the container runtime has no way to know that there might be symlinks in the workshop content that point to the other library, and no other way to know that the other library might be relevant. The container runtime doesn't know where all your games are installed, and it doesn't know a complete list of your Steam libraries; it only knows about the games and libraries that the Steam client tells it about.

We're not going to add code to search each shared directory for symbolic links and automatically share all of their targets, because that would slow down launching every game for every user, particularly on magnetic hard disks. On one of my test machines with a not-particularly-large Steam library (150G), searching my Steam library for symbolic links with `find ~/SteamLibrary -type l` took nearly 2 minutes. We don't want to slow down every game launch by 2 minutes!

If the Steam client told the container runtime about every Steam library (not just the ones that it thinks are involved in launching this particular game), then it would share them all. The Steam client doesn't currently do that, because if you move games around in [the way that is supported](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move), it wouldn't be necessary.

The beta version of the soldier runtime automatically shares all of `/run/media` with the game, which would solve the problem for your particular installation locations. Please [try it](https://github.com/ValveSoftware/steam-runtime/issues/470#issuecomment-1205594862).

> unfortunately for DayZ problem remains

I can't do anything with "problem remains". If you want this to be solved, please describe the situation in more detail: where your DayZ installation, DayZ mods and anything those mods depend on are physically installed, and what symbolic links are pointing to them.

**Comment by SeongGino** [comment]
Hi! That mention was me being directed to this issue for the game in question, so I suppose this is more relevant for my case.

I only recently found this to be an issue with Black Ops 3; though BO3 does have a local mods/usermaps workaround (that does require mangling workshop contents somewhat to conform to a different standard, and also makes mods' saves read/write to a different directory), the problem was still quite bothersome to overcome.

Unfortunately, in my case (on Arch), I have my games installed on a secondary internal drive and partition mounted as a subdirectory in `/mnt`, meaning my games' and workshop mods' installations are in roughly `/mnt/Name/SteamGames/steamapps/...`, so even the beta Soldier runtime mentioned wouldn't account for this.

I really can't pretend to know the ramifications of adding more whitelisted directories to search for, and it's not like I'd be aware of a better solution for this. I'm just adding my own input here.

**Comment by smcv** [comment]
> Unfortunately, in my case (on Arch), I have my games installed on a secondary internal drive and partition mounted as a subdirectory in /mnt, meaning my games' and workshop mods' installations are in roughly /mnt/Name/SteamGames/steamapps/..., so even the beta Soldier runtime mentioned wouldn't account for this.

The beta soldier runtime linked above should be OK for this case: it shares `/mnt` and everything "below" `/mnt` by default. Please try it?

Or, if that is not sufficient, please describe your situation in detail, and attach logs. I can't do anything with "a different directory" or "a local mods/usermaps workaround", I need to know specifics before I can usefully change anything.

The only situations that the beta runtime does not address are those where required files are physically located in a custom top-level directory that is not shared by default (`/storage`, `/games`, etc.), *and* the the game is accessing them via symbolic links in a directory that *is* shared by default, *and* the required files are not in any of the locations that Steam tells the runtime about (in particular, Steam tells the runtime a list of some of your Steam library directories, and the runtime shares those automatically).

**Comment by SeongGino** [comment]
> The beta soldier runtime linked above should be OK for this case: it shares `/mnt` and everything "below" `/mnt` by default.

*Ah,* I did not know this when reading your earlier post prior to my own.
The reason being because of you saying:
> The beta version of the soldier runtime automatically shares all of /run/media with the game...

...and thus I assumed that it was exclusively `/run/media` since that was all that was mentioned, and wasn't aware of any other exceptions being made. I know that might be a stretch to say, but forgive me for my slow learning, considering I'd only *just* learned that the Soldier Runtime had a beta branch yesterday.

Regardless, I just now had the time to check this with the beta branch, and it does in fact seem to work for my setup now. I appreciate the clarification.

**Comment by smcv** [comment]
> Because the path you're interested in is in /run/media, using the beta version of "Steam Linux Runtime - soldier" would probably avoid the problem for you

The beta change described in #470 was promoted to the default branch today.

**Comment by SteveHeist** [comment]
I have retested and can confirm, that the default branch of Soldier Runtime works with at least Call of Duty: Black Ops III Workshop mods:
![image](https://user-images.githubusercontent.com/42606649/188157350-3d14ad1d-6a7b-480a-a139-59d59774619a.png)

On my machine, both the game and the workshop are installed in a Steam directory under /media/[user]/[UUID]/SteamLibrary/[standard Steam Directory structure], using the Steam *Client* beta, but I did revert to the stable branch of the Soldier Runtime itself.

**Comment by kisak-valve** [comment]
Closing as fixed.
