### ISSUE TITLE
MangoHud crashes due to "symbol lookup error (fatal)"

### ISSUE THREAD

**Issue by SteveHeist** [ValveSoftware/steam-runtime#530]
#### Your system information

* Steam Runtime Version: 0.20220804.66	
* Distribution (e.g. Ubuntu 18.04): Ubuntu 22.04 LTS
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): https://gist.github.com/SteveHeist/ac5a23f05f7f0413bc5445e5c943683f
  
* Have you checked for system updates?: [Yes/No] Yes
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] Proton 5.13+ (Experimental as of Sep 14 2022)
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`? (Not sure what of this you would want, so have a Gist https://gist.github.com/SteveHeist/d4ecaf7c945589c10e3b8148bcdbfeae#file-versions-txt)

#### Please describe your issue in as much detail as possible:
Running Call of Duty: Modern Warfare Remastered - Multiplayer (393100) should have provided MangoHud in the top corner compliant with the `mangohud %command%` call. Instead, nothing shows in-game. On a hunch I reran the game with `PROTON_LOG=1 LD_DEBUG=libs` and got a fatal error: `/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan_imp_layer/6/libMangoHud.so: error: symbol lookup error: undefined symbol: vkNegotiateLoaderLayerInterfaceVersion (fatal)`

[steam_393100.log](https://gist.github.com/SteveHeist/1d7d478ba94377d82f56e97d420e40f0)

[slr-app393100-t20220914T214411.log](https://github.com/ValveSoftware/steam-runtime/files/9566868/slr-app393100-t20220914T214411.log) - slr log ran with all settings as predescribed above: `PROTON_LOG=1 LD_DEBUG=libs gamemoderun mangohud %command%` 
[steam-393100.log](https://github.com/ValveSoftware/steam-runtime/files/9566879/steam-393100.log) second log generated with `PROTON_LOG=1 LD_DEBUG=libs` while the slr log was also running.

#### Steps for reproducing this issue:

1. configure MangoHud. I only have a global ~/.config/MangoHud/MangoHud.conf - nothing specific to any games
2. attempt to add MangoHud functionality to 393100.
3. Launch 393100 using the commands predescribed.
4. Note, somewhere around line 30000 (the second proton log has it at line 28924, for example) the error.

**Comment by smcv** [comment]
This is "MangoHud fails to load", not "MangoHud crashes". If it was a crash, your game would not be running (because MangoHud is in the same process space as the game, so if MangoHud crashes, it will bring the game down with it).

It looks as though you compiled MangoHud yourself from source code and installed it into `/usr/local`. Is that correct? If yes, what version?

In fact, you seem to have both a local copy in `/usr/local` and a system copy in `/usr`. To minimize confusion, it's probably a good idea to remove one of those and only keep the other, so one of:

* `apt remove mangohud`, and only keep your locally-installed copy; or
* remove your locally-installed copy, and only keep Ubuntu's `mangohud` package

**Comment by smcv** [comment]
What version of the `libvulkan1` package do you have installed on the host system? This could also be relevant.

**Comment by smcv** [comment]
> and got a fatal error: `/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/vulkan_imp_layer/6/libMangoHud.so: error: symbol lookup error: undefined symbol: vkNegotiateLoaderLayerInterfaceVersion (fatal)`

This is not *necessarily* the problem. Confusingly, ld.so can sometimes say an error is `(fatal)` when actually it isn't. What it really means is that this was fatal to the process of looking up this specific symbol - but if the symbol was looked up via `dlsym()` rather than ELF relocations, application code is still running and can potentially recover!

I suspect there might be some sort of conflict here between:

* the version of `libvulkan-dev` that you used to compile your version of MangoHud
* the version of `libvulkan1` on your Ubuntu host system
* the version of `libvulkan1` in the Steam Runtime container
* the version of the Vulkan layer API that each of those expects

so please be as specific as possible about what those versions are.

**Comment by smcv** [comment]
A current `Steam Linux Runtime - soldier` runtime should have `libvulkan1` version `1.3.216.0-1~steamrt2.1`, I think (the correct version number is listed in `SteamLinuxRuntime_soldier/soldier_platform_*/files/manifest.dpkg`).

An up-to-date Ubuntu 22.04 system should have `libvulkan1` and `libvulkan-dev` both at version `1.3.204.1-2`, unless you have upgraded them yourself (perhaps using a PPA or similar).

The container runtime infrastructure is meant to choose whichever version is newer, so if I'm right about those version numbers, it would be using soldier's version `1.3.216.0-1~steamrt2.1`.

**Comment by smcv** [comment]
Your log has:

```
skipping config: /home/steveheist/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /media/steveheist/db156669-652b-4622-ba48-36d43a6b13511/SteamLibrary/steamapps/common/Proton - Experimental/files/bin/MangoHud.conf [ not found ]
skipping config: /home/steveheist/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/steveheist/.config/MangoHud/MangoHud.conf [ ok ]
```

which implies that MangoHud is getting loaded, and the `(fatal)` message probably wasn't fatal.

**Comment by SteveHeist** [comment]
I didn't have `libvulkan-dev` installed when I compiled. That may have been the issue with the *self-compiled* version. It is worth noting, however, the original log with 393100 was generated using the precompiled 0.6.8 release of MangoHud. 

As mentioned in [MangoHud/#829](https://github.com/flightlessmango/MangoHud/issues/829), I manually force-fed the MangoHud source tree a `vk_layer.h` file from elsewhere in it's own file tree. For the sake of *sanity* and for a working version to compare against, I generated a log and a screenshot of 393100 with that version:

![MWR-hacky-fix](https://user-images.githubusercontent.com/42606649/191155601-5d5e4b44-d420-4f86-a1ab-e41b5ec35284.png)
[steam-393100.log](https://github.com/ValveSoftware/steam-runtime/files/9603580/steam-393100.log)

I then installed `libvulkan-dev` to the most recent version in the Ubuntu APT repositories (I also ran a Verify Integrity of Tool Files against the Soldier container as a sanity check):

![versions](https://user-images.githubusercontent.com/42606649/191155895-9af644d4-761c-462e-9201-d4e160efd163.png)

![manifest](https://user-images.githubusercontent.com/42606649/191156206-d899e652-05dc-4a93-af63-3f7287b5e348.png)

I then removed the `vk_layer.h` I forcefed and recompiled against the same github pull I did yesterday. 

![MWR-proper](https://user-images.githubusercontent.com/42606649/191156714-8b56dbd4-07b3-4eab-9ab5-eaac06d179bd.png)

[steam-393100.log](https://github.com/ValveSoftware/steam-runtime/files/9603633/steam-393100.log)

Sure enough, it works. My apologies for the wild goose chase. That seems to be the issue, given even the releases are mostly from source. I appreciate the assistance.
