### ISSUE TITLE
Missing GLVND in the Sniper platform runtime?

### ISSUE THREAD

**Issue by quyykk** [ValveSoftware/steam-runtime#531]
The Sniper SDK has GLVND installed, so I assumed that it could be linked against for games that target Sniper. But turns out that's not the case, because the Sniper platform runtime *doesn't* include GLVND. So if GLVND isn't present on the user's system, the game fails to launch with:

```
error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
```

The commands I used to verify:

```bash
$ docker run -it --rm registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest bash
(steamrt sniper 0.20220803.0)root@579a69b1e4e7:/# find /usr -name libOpenGL\*
/usr/lib/x86_64-linux-gnu/libOpenGL.so.0
/usr/lib/x86_64-linux-gnu/libOpenGL.so
/usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
/usr/lib/i386-linux-gnu/libOpenGL.so.0
/usr/lib/i386-linux-gnu/libOpenGL.so
/usr/lib/i386-linux-gnu/libOpenGL.so.0.0.0
(steamrt sniper 0.20220803.0)root@579a69b1e4e7:/# 
exit
$ docker run -it --rm registry.gitlab.steamos.cloud/steamrt/sniper/platform:latest bash
(steamrt sniper 0.20220803.0)I have no name!@7ed024b5cdec:/# find /usr -name libOpenGL\*
(steamrt sniper 0.20220803.0)I have no name!@7ed024b5cdec:/# 
exit
```

Is this intended or am I missing something?

**Comment by smcv** [comment]
This is sort-of-intended. During production use of `SteamLinuxRuntime_sniper`, the whole graphics driver stack is meant to be provided by the host system, using the pressure-vessel container runner to set things up. It's unspecified whether this means legacy monolithic drivers or GLVND, and if it's GLVND, it's unspecified whether anything beyond `libGL.so.1` will be present. The only graphics driver that Steam directly requires is `libGL.so.1` (traditional GLX + OpenGL), so that's the only one you can count on having.

If the host system uses a legacy monolithic driver rather than GLVND (so `libGL.so.1` is provided directly by Mesa or NVIDIA and contains Mesa- or NVIDIA-specific code), then that's what you'll get in the pressure-vessel container: no more, no less. Other GLVND entry points (`libGLX.so.0`, `libOpenGL.so.0`, `libEGL.so.1`, `libGLESv2.so.2`, `libGLESv1_CM.so.1`) will either not be present, or be present but not work because there is no driver-specific loadable module like `libGLX_nvidia.so.0` or `libEGL_mesa.so.0` for them to load.

We cannot usefully provide the actual GLVND driver modules like `libGLX_nvidia.so.0` or `libEGL_mesa.so.0` with the container: Mesa would be out of date, and NVIDIA wouldn't work because it has to be upgraded in lockstep with the corresponding kernel module. The Platform and SDK containers do have *a* fallback version of Mesa, but it's quite out of date, and a future release is likely to cut it down to software-rendering-only to save some space.

Some host operating systems (like Arch, I think?) install all of GLVND as a unit, so it's all-or-nothing; but other host OSs (like Debian) have separate packages for the different entry points (`libGL.so.1`, `libGLX.so.0`, `libOpenGL.so.0` and so on). On OSs that have separate packages for the different entry points, we can't guarantee which ones will be present, beyond saying that Steam pulls in `libGL.so.1` and won't work without it.

The Platform container is basically `SteamLinuxRuntime_sniper` with the pressure-vessel stuff discarded, so all you get is the GLX entry points and the fallback version of Mesa, and that's only because some other packages that go into the container have dependencies on them.

The SDK container has more in it than the Platform container, but that's only because it got dragged in by dependencies (`-dev` packages tend to be broken up at a coarser granularity than runtime library packages). If the SDK has the legacy-free `libOpenGL.so.0` entry point, that's coincidental more than deliberate.

I'm not sure that it would be a good idea to add the other entry points like `libOpenGL.so.0` to the container's library stack. If we get a GLVND `libGL.so.1` from the host system, but a GLVND `libOpenGL.so.0` from the container, then each of them is going to want a matching version of `libGLdispatch.so.0`; but we can only have one `libGLdispatch.so.0` in the global search path, so only one of them can possibly get what it wants.

OS-specific Steam packages could *try* to pull in the other GLVND entry points, but on older OS distributions there's no guarantee that they're even available.

So, unfortunately, I think you have to either use `libGL.so.1`, or `dlopen()` your GL drivers and be prepared to fall back to `libGL.so.1` if there is nothing better available.

**Comment by quyykk** [comment]
Thank you for the explanation!

**Comment by smcv** [comment]
[Since 0.20230216.41810](https://gitlab.steamos.cloud/steamrt/steamrt/-/wikis/Sniper-release-notes#sniper-depot-02023021641810-steampipe-build-id-10570137), it is possible to `apt install libopengl0 libegl1` in the Platform runtime.
