### ISSUE TITLE
Old version of libxcb in steam client (but the one available for games is correct)

### ISSUE THREAD

**Issue by sergio-costas** [ValveSoftware/steam-runtime#539]
#### Your system information

* Steam client version (build number or date): Sep 28 2022, at 00:52:47
* Distribution (e.g. Ubuntu): ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When launch from the console, I can see this error:

libGL error: MESA-LOADER: failed to open radeonsi: /snap/steam/x8/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: undefined symbol: xcb_dri3_buffers_from_pixmap_strides (search paths /snap/steam/x8/usr/lib/i386-linux-gnu/dri:/snap/steam/x8/usr/lib/x86_64-linux-gnu/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /snap/steam/x8/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: undefined symbol: xcb_dri3_buffers_from_pixmap_strides (search paths /snap/steam/x8/usr/lib/i386-linux-gnu/dri:/snap/steam/x8/usr/lib/x86_64-linux-gnu/dri, suffix _dri)
libGL error: failed to load driver: swrast

This is because the XCB library available at `.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu` and `.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu` is old and lacks that symbol. Replacing the `libxcb.so.1.1.0` and `libxcb-dri3.so.0.0.0` in those folders with the ones distributed by you at `.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220919.0/files/lib/i386-linux-gnu` and `.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220919.0/files/lib/x86_64-linux-gnu` fixes this problem.

#### Steps for reproducing this issue:

1. open a terminal
2. launch from there the steam client
3. check the output

**Comment by smcv** [comment]
We do not directly support Canonical's Snap-packaged Steam client. Is this reproducible with Valve's .deb version from https://repo.steampowered.com/steam/ or with the .deb in Ubuntu? If not, then it might be better to report this as a bug in [the Snap packaging](https://github.com/canonical/steam-snap).

The `scout` runtime is meant to load libraries from the OS in preference to the corresponding library from the `scout` runtime, if the version of the OS library is equal or newer. When running in a Flatpak container, the "OS" libraries that are seen by Steam are really the Flatpak runtime, rather than the host OS; I'm not familiar with the inner workings of Snap, but I think the situation is similar in the Snap package.

What versions of `libxcb.so.1` and `libxcb-dri3.so.0` for `i386 and `amd64` are available in the environment in which the Snap package runs Steam?

What `LD_LIBRARY_PATH` is used to invoke Steam in the Snap package?

What is the output of running `STEAM_RUNTIME_VERBOSE=1 ~/.local/share/Steam/ubuntu12_32/steam-runtime/setup.sh --force` in the Snap environment?

> Replacing the libxcb.so.1.1.0 and libxcb-dri3.so.0.0.0 in those folders with the ones distributed [in soldier] fixes this problem.

The soldier runtime is designed to be used in a container environment where we can have a lot more control over the libraries that are in use. Because the `LD_LIBRARY_PATH` runtime is more simplistic and has less control over its libraries, we cannot safely upgrade libraries in it to versions that are newer than the oldest OS we aim to be able to run on (currently Ubuntu 14.04, Debian 8 and SteamOS 2) unless the library is set up in a way that lets us determine which version is newer. We can do that for libraries like SDL and Pipewire that always update their filename with each new release, but unfortunately libxcb doesn't always update its filename, so we cannot do that comparison.

**Comment by sergio-costas** [comment]
Thank you for the info!! I've been able to write a fix for it. I'll close this.

Thanks again!

**Comment by sergio-costas** [comment]
The problem happens only with the Steam executable, which is 64 bits.

**Comment by smcv** [comment]
The main Steam executable is 32-bit, but the `steamwebhelper` is 64-bit. We need both word sizes to work.

**Comment by sergio-costas** [comment]
Fixed. Thanks!!!!
