### ISSUE TITLE
Proton/SteamLinuxRuntime games not starting on NTFS with user_id=0

### ISSUE THREAD

**Issue by Saraistupid** [ValveSoftware/steam-runtime#544]
Hello! I'm having trouble with launching games through proton, here's a log from steam itself after running a game
```
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 698780, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 698780, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0PROTON_LOG=1 /home/e404nnf/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=698780 -- /home/e404nnf/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/run/media/e404nnf/Backup/New Folder/steamapps/common/Doki Doki Literature Club/DDLC.exe'\0
Game process added : AppID 698780 "PROTON_LOG=1 /home/e404nnf/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=698780 -- /home/e404nnf/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/run/media/e404nnf/Backup/New Folder/steamapps/common/Doki Doki Literature Club/DDLC.exe'", ProcID 25355, IP 0.0.0.0:0
chdir /run/media/e404nnf/Backup/New Folder/steamapps/common/Doki Doki Literature Club
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/e404nnf/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 698780, ActionID 2] : LaunchApp changed task to Completed with ""
pid 25359 != 25356, skipping destruction (fork without exec?)
**
pressure-vessel:ERROR:../subprojects/libglnx/glnx-local-alloc.h:74:glnx_close_fd: assertion failed: (errno != EBADF)
Game process removed: AppID 698780 "PROTON_LOG=1 /home/e404nnf/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=698780 -- /home/e404nnf/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/run/media/e404nnf/Backup/New Folder/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/run/media/e404nnf/Backup/New Folder/steamapps/common/Doki Doki Literature Club/DDLC.exe'", ProcID 25355 
ThreadGetProcessExitCode: no such process 25357
ThreadGetProcessExitCode: no such process 25356
Uploaded AppInterfaceStats to Steam
```

I assume the issue is `pressure-vessel:ERROR:../subprojects/libglnx/glnx-local-alloc.h:74:glnx_close_fd: assertion failed: (errno != EBADF)` but I don't know exactly what's causing it, I tried different proton versions too, still same problem

Distro: `Arch Linux`
Proton Version: `Proton Experimental`
Games: `Doki Doki Literature Club`, `Muse Dash` (only games i tested)

**Comment by kisak-valve** [comment]
Hello @Saraistupid, Starting with Proton 5.13, Proton is run inside the Steam Linux Runtime - Soldier container environment, and that is setup by Pressure Vessel. Since the assert you've encountered is with Pressure Vessel, then that's before Proton gets a chance to run and I've gone ahead and transferred this issue report to the steam-runtime issue tracker.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information. Also, what filesystem are you using with `/run/media/e404nnf/Backup/New Folder`?

**Comment by kisak-valve** [comment]
Proton has a long history of having a hard time interacting with NTFS. It's not surprising that Pressure Vessel also has a hard time when it's put on an NTFS partition as well. The general recommendation is to use a native Linux filesystem instead.

**Comment by Saraistupid** [comment]
i downloaded a small game on my linux partition and i still experience the same problem, same error even
```
pressure-vessel:ERROR:../subprojects/libglnx/glnx-local-alloc.h:74:glnx_close_fd: assertion failed: (errno != EBADF)
```

**Comment by smcv** [comment]
> `user_id=0,group_id=0`

This configuration isn't one that we are likely to be able to support. It will result in files being owned by root, even if we created them as your normal user, which leads to weird permissions issues when we try to do things with those files later. Even though the file is read/write for your user as a result of `umask=000`, we can't do things like setting permissions (only the owner can do that). Creating hard-links will sometimes also fail, which is bad for us, because we use hard-links quite a lot to avoid wasting your disk space.

If you migrate the "Steam Linux Runtime - soldier" app to your Linux partition, that might help. See [How do I move a game's installation folder?](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move) on Steam support, but instead of doing this for a game, do it to the "Steam Linux Runtime - soldier" tool that appears in your library. If you have other tools with names like "Steam Linux Runtime" or "Steam Linux Runtime - sniper", do the same for those. Having the various Steam Linux Runtime compatibility tools on a Linux partition is actually more important than the game itself being on a Linux partition.

Migrating all Proton versions onto a Linux partition might also help.

If you need to use a NTFS partition to store your Steam library, the least bad way to do it is to set up the mount options so that all files appear to be owned by the user that will run Steam. Depending on the filesystem implementation, this might be a `user` or `uid` or `user_id` option. NTFS also needs to be set up to allow filenames containing `:` even though those are not allowed in Windows (Steam Linux Runtime / pressure-vessel doesn't actually need this, but Proton does).

If at all possible, I'd recommend just not using NTFS for your Linux Steam library - there are too many things that can go wrong.

> `pressure-vessel:ERROR:../subprojects/libglnx/glnx-local-alloc.h:74:glnx_close_fd: assertion failed: (errno != EBADF)`

This assertion failure is the result of some bugs in the error handling - coincidentally, I think I might already have fixed that bug in a future release of pressure-vessel. When these are fixed, you'll get a better error message that gives a bit more information about what didn't work, but launching the affected games still won't actually succeed.

> `umask=000`

This setting is a bad idea if you have any untrusted users on your system - not just human users, but also system services like Avahi, Samba, etc. that might get compromised as a result of a bug. With this umask, any user ID that can access the NTFS partition will be able to overwrite your games with code of their choice, which will be run the next time you launch that game (a privilege escalation that takes over control of your user account).

**Comment by smcv** [comment]
@kisak-valve, please could you retitle this something like "Proton/SteamLinuxRuntime games not starting on NTFS with user_id=0" to indicate the scope?

(Having SLR installed on a FAT or ExFAT filesystem, or with ownership set to any uid other than the current one, could also be treated as in-scope here, but NTFS with uid 0 is the most likely and I don't want to make the title excessively long.)

**Comment by smcv** [comment]
@Saraistupid, if you replace `SteamLinuxRuntime_soldier/pressure-vessel/` with the result of unpacking <https://repo.steampowered.com/pressure-vessel/snapshots/0.20221115.1/pressure-vessel-bin.tar.gz>, that should give you a better log with a bit more indication of what is going on here: instead of the assertion failure, it should report the actual failure reason. Use the ["Verify integrity" button](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) on "Steam Linux Runtime - soldier" when you want to go back to the released version.

If the root cause is what we suspect, then this issue will probably have to be "won't fix", because there isn't really a good way to deal with the library being owned by a user that isn't the current one - but it would be useful to be able to confirm whether our diagnosis is correct.

The workaround would be to migrate the "Steam Linux Runtime - soldier" tool to your Linux partition, as I described in [a previous comment](https://github.com/ValveSoftware/steam-runtime/issues/544#issuecomment-1314281671). The library in `/home/e404nnf/.local/share/Steam/steamapps` that Steam sets up by default is a good place to keep these tools.

**Comment by LeXofLeviafan** [comment]
I'm having the same exact issue (with pretty much identical log) on a system with only **ext4** partitions.

Oddly enough, toggling on/off the `client_beta` in Steam Linux Runtime – Soldier fixes the issue temporarily (until I restart Steam). Maybe it's a side effect of a faulty update (…but a welcome one :sweat_smile:)

***
…When using the snapshot from the previous comment, the log stays exactly the same except I'm getting the following error instead of EBADF assertion (added linebreaks for better readability):
```
pressure-vessel-wrap[4637]: E: Could not create copy
 "./lib/steamrt/expectations/x86_64-linux-gnu/libxcb-xkb1.symbols" from
 "/home/lex/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20221017.1/files/./lib/steamrt/expectations/x86_64-linux-gnu/libxcb-xkb1.symbols" into
 "/home/lex/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-ZKZKX1/usr":
 fstatat(./lib/steamrt/expectations/x86_64-linux-gnu/libxcb-xkb1.symbols): No such file or directory
```
…Then again, it might just be that the snapshot is outdated – it's over a month old by now (I've had this problem for a while but only stumbled upon this ticket now).

**Comment by smcv** [comment]
@LeXofLeviafan, you are **not** seeing the same issue as the original reporter, although bugs in pressure-vessel's error-handling (which are fixed by the snapshot linked above) are obscuring it.

> Could not create copy "blahblah" from "blahblah/files/blahblah": No such file or directory

This is not the same issue. If some required files are missing from the `SteamLinuxRuntime_soldier/soldier_platform_*/files` directory, that would indicate that the Steam client's file-distribution mechanism (Steampipe) is not downloading `SteamLinuxRuntime_soldier` correctly (or possibly that something else is somehow deleting required files from it). The maintainers of the Steam Runtime do not have control over this mechanism, which is the same one used to download the games themselves.

Toggling the `client_beta` likely works around this by forcing Steam to re-download the runtime. Telling Steam to [verify installed files](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) might be helpful.

If verifying the installed files does not solve this for you, please report this to https://github.com/ValveSoftware/steam-for-linux/ as a separate issue. Steam developers would be able to advise on which of the logs in `~/.steam/root/logs/` are the most relevant.

**Comment by smcv** [comment]
@kisak-valve, I think we can close this as a duplicate of #434 - as far as I can tell, it's essentially the same issue.

Today's beta releases work around this, to the extent that it's possible to do so (see https://github.com/ValveSoftware/steam-runtime/issues/434#issuecomment-1710491239).
