### ISSUE TITLE
regression: Borderlands 2 incompatible with latest client/UI update on Arch Linux

### ISSUE THREAD

**Issue by uqs** [ValveSoftware/steam-runtime#546]
#### Your system information

* Steam Runtime Version:  1668654564
* Distribution (e.g. Ubuntu 18.04):  Arch Linux, fully updated
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  
* Have you checked for system updates?: [Yes/No] Yes, a "steam client update" mid-November broke it
* What compatibility tool are you using?: [None / Steam Linux Runtime / Proton 5.13+ / older Proton] None AFAIK
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?

* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
% cat /opt/steam/steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt
#Name   Version         Runtime Runtime_Version Comment
depot   0.20220930.72                   # Overall version number
pressure-vessel 0.20220927.0
scripts v0.20220823.0-0-gcc4e44f                        # Entry point scripts, etc.
soldier 0.20220927.0    soldier 0.20220927.0    # soldier_platform_0.20220927.0/
```

#### Please describe your issue in as much detail as possible:

Borderlands 2 starts when ran outside of the Steam UI, but as of a week ago it no longer works when started from within the Steam UI.

#### Steps for reproducing this issue:

1. Arch Linux, install steam and Borderlands 2, play the native version just fine till the last Steam update that happened mid-November
2. Get told by Steam "a new version is available", install it
3. Borderlands 2 no longer works, due to a conflict in libc++ and the LD overrides.

So here's what happens when running it from Steam:

```
Game process added : AppID 49520 "/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup", ProcID 4753, IP 0.0.0.0:0
chdir /opt/steam/steamapps/common/Borderlands 2
GameAction [AppID 49520, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
/opt/steam/steamapps/common/Borderlands 2/./Borderlands2: Symbol `_ZTVN10__cxxabiv120__si_class_type_infoE' has different size in shared object, consider re-linking
/opt/steam/steamapps/common/Borderlands 2/./Borderlands2: Symbol `_ZTVN10__cxxabiv117__class_type_infoE' has different size in shared object, consider re-linking
GameAction [AppID 49520, ActionID 1] : LaunchApp changed task to Completed with ""
Game process removed: AppID 49520 "/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup", ProcID 4753 
ThreadGetProcessExitCode: no such process 4754
```

Those C++ symbols are in conflict now, this was working fine before the steam client update.

I can still run it just fine outside of steam, by first providing a `steam_appid.txt` and then running `cd /opt/steam/steamapps/common/Borderlands\ 2/ && /home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup`
This works fine, but I'm not sure whether this correctly captures my Achievements.

Anyway, is there a way to downgrade the steam client by 1 version? I know there's a `steam-runtime.old` copy on my disk, how can I make use of that?

Borderlands2 ships with its own set of libraries, can I maybe tweak LD_LIBRARY_PATH just for this 1 game?
```
% ll
total 44948K
-rwxr-xr-x 1 uqs uqs 37294704 Apr 26  2021 Borderlands2*
-rwxr-xr-x 1 uqs uqs       33 Apr 26  2021 com.aspyr.bl2.version.json*
-rwxr-xr-x 1 uqs uqs     1755 Nov 23 09:34 installscript.vdf*
-rwxr-xr-x 1 uqs uqs   920044 Apr 26  2021 libc++.so*
-rwxr-xr-x 1 uqs uqs   920044 Apr 26  2021 libc++.so.1*
-rwxr-xr-x 1 uqs uqs   920044 Apr 26  2021 libc++.so.1.0*
-rwxr-xr-x 1 uqs uqs  1734772 Apr 26  2021 libcrypto.so.1.0.0*
-rwxr-xr-x 1 uqs uqs   128822 Apr 26  2021 libcxxrt.so*
-rwxr-xr-x 1 uqs uqs  1219620 Apr 26  2021 libiconv.so*
-rwxr-xr-x 1 uqs uqs  1219620 Apr 26  2021 libiconv.so.2*
-rwxr-xr-x 1 uqs uqs  1219620 Apr 26  2021 libiconv.so.2.5.1*
-rwxr-xr-x 1 uqs uqs   346124 Apr 26  2021 libssl.so.1.0.0*
-rwxr-xr-x 1 uqs uqs    66598 Apr 26  2021 libsteam_api.so*
-rw-r--r-- 1 uqs uqs        6 Nov 17 11:35 steam_appid.txt
drwxr-xr-x 9 uqs uqs     4096 Apr 26  2021 steamassets/
```

I've changed the soldier runtime to `previous_release` (0.20220919.0) but that still runs into the same linker errors and symbol conflicts. :(

It looks to me like the UI update pulled in some incompatible library version and it prebinds them or messes with LD_LIBRARY_PATH in other ways that make launching it from within steam break.

**Comment by zow34tq** [comment]
Stop. The government said i couldn't work with you on this. And. NOw russian air controller m8chaela is interrogating you.

**Comment by smcv** [comment]
You are not currently using the container-based Steam Linux Runtime compatibility tool for this game (if you were, the command-line would be different). You *are* using the older `LD_LIBRARY_PATH`-based runtime, which is what's used by default for most native Linux games. (This is the issue tracker for both of them.)

In the game's Properties in Steam, try setting it to "force a specific compatibility tool" and choosing "Steam Linux Runtime"? That will change it from the old `LD_LIBRARY_PATH`-based runtime to the container runtime, which might avoid this.

The container runtime you'll get by choosing "Steam Linux Runtime" is based on the same "Steam Linux Runtime - soldier" container that Proton uses, but with some extra libraries to provide backwards-compatibility with the old `LD_LIBRARY_PATH`-based runtime (which some games need).

> I've changed the soldier runtime to previous_release (0.20220919.0) but that still runs into the same linker errors and symbol conflicts

You're not (yet) using soldier for this game, so that won't have any effect. Please try the default branch of soldier first, and only try its `previous_release` if the default branch isn't working.

**Comment by smcv** [comment]
Arch is a rolling release, so it's constantly changing. How confident are you that the trigger for this regression was the mid-November update to the Steam client, and not an update to Arch at around the same time?

> Link to your full system information (Help -> System Information) in a Gist

Please provide this information, it's often very helpful in diagnosing what has gone wrong.

> is there a way to downgrade the steam client by 1 version?

Not a supported one. The only supported versions of the Steam client are the normal (general-availability) branch and the public beta. I think 1668654564 is the general-availability branch; have you tried the Steam client beta?

> I can still run it just fine outside of steam

This is not a supported thing to do, use at your own risk.

There are two significant differences that this will create:

* it's not using the `LD_LIBRARY_PATH` runtime
* it's not using the Steam Overlay (`LD_PRELOAD`)

and we don't yet have enough information to know which is the one that caused the difference.

If you try inserting the `LD_LIBRARY_PATH` runtime's `run.sh` into the middle of the long command you're running, like this:

```
cd ... && /home/uqs/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /home/uqs/.local/share/Steam/ubuntu12_32/reaper ...
```

does it launch successfully? If it works, then the `LD_LIBRARY_PATH` runtime is not the problem, and either the Steam overlay (a `LD_PRELOAD` module) or some other change made to the execution environment by Steam is significant. Conversely, if it fails in the same way you saw via Steam, then the `LD_LIBRARY_PATH` runtime is significant.

**Comment by uqs** [comment]
Thank you for the detailed response!

I did not try the compatibility, as my assumption there is that it is Proton, which is Wine, and I didn't want to run the win32 version of the game, but the native one. So what you're saying is that Proton is not just Wine, but also useful to run Linux games in a proper container that avoids all that DLL hell?

> Arch is a rolling release, so it's constantly changing. How confident are you that the trigger for this regression was the mid-November update to the Steam client, and not an update to Arch at around the same time?

I'm 95% confident that I did not run an update prior to it breaking. The steam client update however was immediately preceding. The fact that it runs "outside" of steam is also telling, I believe.

I did run a system update since then though, trying to see if it was fixed forward or not. It's hard to now reconstruct the exact series of events :/
 
> > Link to your full system information (Help -> System Information) in a Gist

https://gist.github.com/uqs/601205adfe7cb9c31fe68a9639fd5fc6

> 
> > is there a way to downgrade the steam client by 1 version?
> 
> Not a supported one. The only supported versions of the Steam client are the normal (general-availability) branch and the public beta. I think 1668654564 is the general-availability branch; have you tried the Steam client beta?
> 
> > I can still run it just fine outside of steam
> 
> This is not a supported thing to do, use at your own risk.
> 
> There are two significant differences that this will create:
> 
> * it's not using the `LD_LIBRARY_PATH` runtime
> * it's not using the Steam Overlay (`LD_PRELOAD`)
> 
> and we don't yet have enough information to know which is the one that caused the difference.
> 
> If you try inserting the `LD_LIBRARY_PATH` runtime's `run.sh` into the middle of the long command you're running, like this:
> 
> ```
> cd ... && /home/uqs/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh /home/uqs/.local/share/Steam/ubuntu12_32/reaper ...
> ```
> 
> does it launch successfully? If it works, then the `LD_LIBRARY_PATH` runtime is not the problem, and either the Steam overlay (a `LD_PRELOAD` module) or some other change made to the execution environment by Steam is significant. Conversely, if it fails in the same way you saw via Steam, then the `LD_LIBRARY_PATH` runtime is significant.

That indeed works just fine, putting more blame on the overlay preloading some, now incompatible, libraries.

I've now selected Compatibility > Linux runtime, this caused a 1GB download (I guess the container), then ran it:

```
/bin/sh\0-c\0/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/opt/steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup\0
Game process added : AppID 49520 "/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/opt/steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup", ProcID 6018, IP 0.0.0.0:0
chdir /opt/steam/steamapps/common/Borderlands 2
GameAction [AppID 49520, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/uqs/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 49520, ActionID 1] : LaunchApp changed task to Completed with ""
Game process removed: AppID 49520 "/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/opt/steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup", ProcID 6018 
ThreadGetProcessExitCode: no such process 6125
ThreadGetProcessExitCode: no such process 6020
ThreadGetProcessExitCode: no such process 6019
Uploaded AppInterfaceStats to Steam
```

Btw, I turned off the Steam overlay for this game, why does it still try to LD_PRELOAD it?

Trying that same thing outside of steam from an XTeam launches the game fine (but I needed to re-configure all the Video settings)

```
/home/uqs/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=49520 -- /home/uqs/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/opt/steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/opt/steam/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/opt/steam/steamapps/common/Borderlands 2/./Borderlands2' -nolauncher -nomoviestartup
Setting breakpad minidump AppID = 49520
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198040470610 [API loaded no]
```

Btw, I tried stracing the non-compatibility launch but did not see it call any "run.sh" in there (because then I could put LD_ overrides and some logging in there, maybe.


Sigh, and now I tried launching Bioshock Infinite w/ and w/ Linux compat and it doesn't work either. But I haven't run that in ages, so no idea when that broke :/

**Comment by smcv** [comment]
> So what you're saying is that Proton is not just Wine, but also useful to run Linux games in a proper container that avoids all that DLL hell?

*Proton* is still just for running Windows games on Linux. It's not *just* Wine, it has some other components like DXVK.

However, Steam's "compatibility tools" infrastructure is not just for Proton: it's more generic than that, and can also be used to run a native Linux game in a container that has a different library stack, which is what the "Steam Linux Runtime" compatibility tool option does.

> I've now selected Compatibility > Linux runtime, this caused a 1GB download (I guess the container), then ran it:

I can't tell from the output you quoted whether the game worked or not. Did it?

If it didn't work, then it's maybe crashing without an error message, which is unfortunate.

> I turned off the Steam overlay for this game, why does it still try to LD_PRELOAD it?

I don't have visibility into proprietary Steam code, but I believe the option in the GUI to turn off the Steam overlay just turns off the actual user-visible overlay feature. The `LD_PRELOAD` module that is responsible for the overlay still gets loaded, because the overlay is not the only thing that it does: it's also responsible for injecting input events from Steam Input (gamepad remapping and Remote Play) and possibly other Steam features.

> putting more blame on the overlay preloading some, now incompatible, libraries

That would be more of a https://github.com/ValveSoftware/steam-for-linux/ thing (I don't have access to the overlay code), although the boundary between the runtime and the proprietary code is sometimes quite blurred, and it might be possible to work around an incompatibility via the runtime.

(@TTimo: I think this might coincide with parts of Steam having been compiled with g++-9? Maybe the overlay needs more explicit ABI control?)

**Comment by smcv** [comment]
> I tried stracing the non-compatibility launch but did not see it call any "run.sh" in there

That's normal, the `LD_LIBRARY_PATH` environment is set up once during Steam startup and applies to the whole of Steam (the Steam client plus every game it runs). The container runtime reverts the changes made by the `LD_LIBRARY_PATH` environment before it starts the container, so the practical result is similar to what would have happened if it had been started from outside Steam.

**Comment by uqs** [comment]
> I can't tell from the output you quoted whether the game worked or not. Did it?

It did _not_. Those few lines are all the output I get, no splash screen no nothing :/

It works with either runtime when started _outside_ of the steam UI.

**Comment by smcv** [comment]
> putting more blame on the overlay

There is a way you can confirm whether the overlay module is the problem: if you use the "Steam Linux Runtime" compatibility tool *and* set the Launch Options to `PRESSURE_VESSEL_REMOVE_GAME_OVERLAY=1`, then the container runtime will disable the overlay module completely.

This is an unsupported debugging/development thing, not a supported feature. Not loading the overlay module is known to break some Steam features: at least Steam Input and the visible parts of the overlay (notification popups, Shift+Tab overlay, overlay web browser and so on), and possibly also other Steam <-> game integration things like achievements. If you report issues while in this state, please remember to say that you have done so, and be prepared for the answer to be "if you disable the overlay then that can't work".

> Maybe the overlay needs more explicit ABI control?

It looks like `gameoverlayrenderer.so` exports a bunch of C++ weak symbols, so it might need the same tricks that were done e.g. in [recent versions of DXVK](https://github.com/doitsujin/dxvk/commit/1d3decf1008782428c4d34eadbf54d1077862da2): strictly exporting only the symbols that it is intentionally overriding, without accidentally exporting anything else. In C code it would be sufficient to use `-fvisibility=hidden` and decorate the public symbols with `__attribute__((visibility("default")))`, but in C++ it needs a version-script.

If that guess is correct, then this is not something that the Steam Runtime can solve, and it would have to be the Steam client that implements this.

> now I tried launching Bioshock Infinite [with and without?] [Steam Linux Runtime?] compat and it doesn't work either

I'd be interested to know whether that is also an overlay-related issue. If the truth table for which ways to run a game are successful and which ones are unsuccessful is the same as for Borderlands 2, then perhaps it might have the same root cause. If not, it would be better to report it as a separate issue with full details.

**Comment by davidfou** [comment]
Hello :wave: 

I ended up on this issue while understanding why borderland2 no longer starts.

I can confirm starting Steam with `PRESSURE_VESSEL_REMOVE_GAME_OVERLAY=1 flatpak run com.valvesoftware.Steam` managed to start the game :raised_hands: 

I'm on the distro Pop!_OS.

Let me know if I can somehow help you even more

**Comment by uqs** [comment]
Indeed, running with soldier and PRESSURE_VESSEL_REMOVE_GAME_OVERLAY=1 allows BL2 to launch from within the steam-client. 

Ignore Bioshock Infinite for now, it no longer launches at all and dumps core even when run outside of Steam.

So for BL2 this is a steam-client issue then? @smcv could you do me a favor and file that bug in the right component (I'm still confused about what's called what) and you also seem to have an idea for a fix already as well?

**Comment by TTimo** [comment]
It's a steam client problem, we're working on it. Workaround to disable the game overlay is correct.

**Comment by TTimo** [comment]
This will be fixed in the next beta client update. In the meantime, if you want to confirm that the overlay is working again for you and there are no adverse consequences to this change:

https://www.dropbox.com/s/zsr3d0glh597sba/linux-overlay-fix.zip?dl=0
`a4525e91aabbc95a94ef5aae62e0c9a549ebd1b72b5f73ce3af5fe99198ac07a  linux-overlay-fix.zip`

Run the Steam client with `-noverifyfiles` so the modified modules don't get reverted.

**Comment by TTimo** [comment]
The fix has shipped in latest Steam client beta.

**Comment by smcv** [comment]
I confirm that the new beta's `ubuntu12_{32,64}/gameoverlayrenderer.so` has a much smaller ABI with no exports of weak or C++ symbols. I don't have Borderlands 2 on my test system, so I can't confirm or deny this being a solution, but it certainly looks more likely to be robust than it was previously.

**Comment by smcv** [comment]
@uqs or @davidfou, please could you try [switching to the Steam Client beta](https://help.steampowered.com/en/faqs/view/276C-85A0-C531-AFA3) and removing the `PRESSURE_VESSEL_REMOVE_GAME_OVERLAY=1` workaround? With this beta version of Steam, Borderlands 2 should run without any special workarounds.

**Comment by uqs** [comment]
Unrelated to the fix, I can say that PRESSURE_VESSEL_REMOVE_GAME_OVERLAY=1 with soldier and BL2 still has working achievements, so there's that.

More importantly, I can confirm that the beta fixes the linker/symbol errors for the non-soldier runtime and the overlay works fully again.

Thanks for the fix!

**Comment by davidfou** [comment]
Sorry for the late reply. I can confirm with one of the recent official updates fixed the issue. Thanks a lot everyone for providing a quick and real fix :clap:
