### ISSUE TITLE
How to pack libraries in a Linux native game

### ISSUE THREAD

**Issue by ericoporto** [ValveSoftware/steam-runtime#553]
Hi,

I have a binary that depends on libraries that are placed on a directory together with a game. Because some libraries may depend on other libraries, the way we work currently is to use RPATH (not RUNPATH, as it doesn't propagates) on the game binary, so it loads all libraries correctly. We build with glibc 2.14 compatibility.

I read the mention of usage of LD_LIBRARY_PATH is used internally on Steam when launching a Linux Native game. This means our libraries take preference (they include SDL2, but there is also the steam API library `libsteam_api.so`). Is this a problem? Should we instead use `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:mylibdir` ?

**Comment by TTimo** [comment]
Hello,

The most important step is to compile the binaries for your title using the steam runtime scout SDK. See https://github.com/ValveSoftware/steam-runtime for documentation.

You should also make sure that your game works great when selecting the 'Steam Linux Runtime' in compatibility settings. This confirms that your binary is compatible with the steam runtime and will run on a broad variety of linux distributions.

We recommend relying on the libraries that are provided in the steam runtime as much as possible (particularly SDL2) rather than supplying your own. If a library isn't provided, then building and bundling it yourself is fine of course.

Using RUNPATH/RPATH is fine, you can also use LD_LIBRARY_PATH by appending to it and making sure not to remove the paths that Steam has already added.

**Comment by ericoporto** [comment]
Thanks for the information!
