### ISSUE TITLE
Update CMake inside the Sniper runtime

### ISSUE THREAD

**Issue by quyykk** [ValveSoftware/steam-runtime#556]
The CMake version in the Sniper runtime is currently 3.18. Would it be possible to update it to a newer version?

**Comment by TTimo** [comment]
@smcv

**Comment by smcv** [comment]
It's currently at the version in Debian 11 'bullseye', which is what sniper is based on. We could grab the version from bullseye-backports (which is a straightforward rebuild of the version that will be in Debian 12), if @TTimo is happy with the regression risk being low enough; that would give us 3.25.1.

Going forwards is easy but going backwards is really annoying, so we should only do this if we're confident that staying on 3.25.1 is going to be OK. In my experience CMake has usually had good backwards-compatibility, so it's probably fine?

I would prefer not to advance sniper beyond what's in Debian 12 if we can help it: the lowest-risk backport is usually when we advance from Debian *n* to *n*+1.

**Comment by TTimo** [comment]
Yeah I'd say this is fine for cmake.

**Comment by smcv** [comment]
OK, this is on my list for a future beta. I'll comment here when it becomes available.

**Comment by smcv** [comment]
Today's sniper beta (versioned as 0.20230116.1 internally) includes the new CMake. You can pull it as `registry.gitlab.steamos.cloud/steamrt/sniper/sdk:0.20230116.1` or `registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta`.

Note that binaries compiled with the sniper beta SDK are not guaranteed to work correctly with the production version of "Steam Linux Runtime - sniper", because some libraries have been upgraded. Developers can opt in to the `[client_beta]` branch of sniper to get a version that will work with the sniper beta SDK.

If you have a released game on Steam that is configured to use sniper, please continue to use either `registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest` or an older "pinned" version number for your official builds. This will not have the updated CMake yet; I'll comment again here when the beta that has the new CMake gets promoted to stable.

(@quyykk, I see you're an Endless Sky contributor?)

**Comment by quyykk** [comment]
Cool thanks

> (@quyykk, I see you're an Endless Sky contributor?)

yeah that's right; I'm part of the team.

**Comment by smcv** [comment]
> Today's sniper beta (versioned as 0.20230116.1 internally) includes the new CMake

This is now in the default branch, so `registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest` has CMake 3.25.1.

If you're involved in shipping Endless Sky or other games on Steam, I believe the situation with running games on sniper is that it is possible to do, but requires special metadata set on your game, which initially requires asking a Valve developer to set it up for you. The early adopters for this feature were [Battle for Wesnoth](https://github.com/ValveSoftware/steam-runtime/issues/508#issuecomment-1147665747) (currently for the 1.17 beta branch only) and [Retroarch](https://github.com/libretro/RetroArch/issues/14266) (for all branches).

The plan is that in future, setting the runtime that's used by each branch of your game will be something you can do yourself by editing its properties in the Steam partner website. As far as I know, this isn't ready yet, but I might be out of date on that.

**Comment by quyykk** [comment]
> initially requires asking a Valve developer to set it up for you

Thank you, we plan on doing that in the (very) near future.

Since 3.25.1 is now in the latest public branch, this can be closed. Thanks again!

**Comment by quyykk** [comment]
>The plan is that in future, setting the runtime that's used by each branch of your game will be something you can do yourself by editing its properties in the Steam partner website. As far as I know, this isn't ready yet, but I might be out of date on that.

@TTimo is this something we can do ourselves yet?

**Comment by TTimo** [comment]
No we still need to set it up on the backend for you.

**Comment by quyykk** [comment]
@TTimo So would it be possible for you to set it up for us at [Endless Sky](https://store.steampowered.com/app/404410/Endless_Sky/)? Thanks!

The `internal` branch (beta code `URGtAbcGXn7ArV`) contains 32-bit and 64-bit executables built using the latest Sniper SDK already.

**Comment by TTimo** [comment]
Sure! Please email me directly though, ttimo@valvesoftware.com and we'll get that going.

**Comment by smcv** [comment]
Until this is set up, there's a trick that developers can use: if you set the launch options to `steam-runtime-launch-options -- %command%`, you'll get a test UI where you can force it to use a particular runtime setup. This requires GTK 3 with its GObject-Introspection bindings, and Python 3 with PyGI.

For a game built with the sniper SDK, you want "Container runtime": sniper *and* "Layered runtime scripts": "None". This UI intentionally doesn't save any settings, so you'll have to make those choices every time. While debugging it's often also useful to select "Interactive shell": "Instead of running the command". This gives you an `xterm` where you can type `"$@"` to run the game (repeatedly, if necessary).

Be careful when using this, it's definitely a developer-only thing: it doesn't try to stop you from using combinations of options that are incompatible with your game, or make no sense at all.

**Comment by smcv** [comment]
Since this issue has been referenced elsewhere as an example of a game that uses `SteamLinuxRuntime_sniper`, I'll leave a comment here to say:

As of 2023-06-22 (and probably earlier), all branches of Endless Sky use `SteamLinuxRuntime_sniper` as their default (and only supported) runtime.
