### ISSUE TITLE
container runtime can't load Vulkan drivers when VK_LOADER_DRIVERS_SELECT is set

### ISSUE THREAD

**Issue by gulafaran** [ValveSoftware/steam-runtime#558]
#### Your system information

* Steam client version (build number or date): 1.0.0.75
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
im running a laptop with an amd 5800h cezanne main gpu and a nvidia 3060 dgpu, currently on wayland with KDE. native applications and other games i launch either from "gui" as in .desktop files or through a shell chooses and runs on the nvidia dgpu when i use the prime-run script. the prime run script sets these environment variables.

```
DRI_PRIME=1
DXVK_FILTER_DEVICE_NAME=NVIDIA
VKD3D_FILTER_DEVICE_NAME=NVIDIA
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
VK_LOADER_DRIVERS_SELECT=*nvidia*
_EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
__GLX_VENDOR_LIBRARY_NAME=nvidia
__NV_PRIME_RENDER_OFFLOAD=1
__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
__VK_LAYER_NV_optimus=NVIDIA_only
```

it also works just fine with system installed wine and dxvk/vkd3d.
however when using any proton versions or the famous proton-ge editions as a compatibility tool and setting launch options as `prime-run %command%` the games doesnt find my gpu at all, and errors like this, example from satisfactory. https://i.imgur.com/FzJSmX0.png

with some major headaches and googling i found some old wiki workaround https://wiki.archlinux.org/title/Steam/Troubleshooting#The_game_crashes_when_using_Steam_Linux_Runtime_-_Soldier and said and done when i append

```
shift 2
exec "${@}"
```

at the top of the `~/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point` file the games begin working again.

**Comment by smcv** [comment]
> `shift 2`

This is not a supportable thing to do and will randomly break when you least expect it to.

**Comment by gulafaran** [comment]
> > `shift 2`
> 
> This is not a supportable thing to do and will randomly break when you least expect it to.

yeah im quite a bit unsure of what those things actually does, more of just pointing out something seems to go wrong in the _v2-entry-point. either resetting my env vars? or not finding some vulkan icd .json files? im unsure.

**Comment by smcv** [comment]
Please collect a detailed log according to the instructions in <https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information>.

Do non-Proton games work correctly and use the GPU that you expect? CS:GO, Dota 2 and Life is Strange episode 1 are free games that would make good examples to work with. (The big advantage of using free games is that everyone who is experiencing a similar issue can easily replicate the same setup!)

Proton games have two separate sources of complexity: the container runtime, and also Proton. Instead of jumping directly from "run ordinary programs" to the full complexity of Proton in a container, it's a lot easier to figure out what is happening by introducing one complicated thing at a time.

If you use CS:GO as your test game and it works with default settings, there are a couple of things you can try to get it progressively more like Proton:

* setting its Launch Options to `%command% -vulkan`
* forcing it to use the container runtime: Properties -> Compatibility -> Force the use of a specific Steam Play compatibility tool -> Steam Linux Runtime

**Comment by smcv** [comment]
> Please collect a detailed log according to the instructions in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information.

Setting environment variable `STEAM_LINUX_RUNTIME_VERBOSE=1` would probably be helpful here: that puts a complete list of environment variables in the log, which seems likely to be useful information when `prime-run` works by altering the environment.

**Comment by gulafaran** [comment]
> 



> > Please collect a detailed log according to the instructions in https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information.
> 
> Setting environment variable `STEAM_LINUX_RUNTIME_VERBOSE=1` would probably be helpful here too: that puts a complete list of environment variables in the log, which seems likely to be useful information when `prime-run` works by altering the environment.

log of `STEAM_LINUX_RUNTIME_VERBOSE=1`  https://gist.github.com/gulafaran/8eaf7e4f77109ef13e8904af8a22dd14 
what i can tell is down the line somwhere pressure-vessel sets 
'VK_ICD_FILENAMES=/usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/0.json'
'VK_DRIVER_FILES=/usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/0.json'

while still maintaining
'VK_LOADER_DRIVERS_SELECT=*nvidia*'

 which seems like a potential conflict.

**Comment by smcv** [comment]
Ah, yes, well spotted! In older versions of Vulkan-Loader, the filename of the JSON manifest for the driver never actually mattered, so for simplicity we just use sequential numbered names when we're remapping the files into the container (we usually can't use exactly the same content or filename for various annoying reasons). In newer versions of Vulkan-Loader that have implemented the `VK_LOADER_DRIVERS_SELECT` feature, the filename has started to matter, so now we will have to teach pressure-vessel to preserve the basename of the JSON manifest, like `/usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/nvidia_icd.json`.

If prime-run is setting both `VK_ICD_FILENAMES` and `VK_LOADER_DRIVERS_SELECT`, then that's actually redundant, so you can probably work around this in the short term by unsetting `VK_LOADER_DRIVERS_SELECT`:

```
prime-run env -u VK_LOADER_DRIVERS_SELECT %command%
```

That's a narrower (and therefore more supportable) workaround than disabling the container completely.

> im quite a bit unsure of what those things actually does

The workaround you were previously using completely disables the container runtime, so it is taking Proton binaries that were intended to run in a Steam Linux Runtime 2 'soldier' container, and running them directly on your Arch system instead. If this works, then it's only working because you were lucky.

**Comment by smcv** [comment]
@kisak-valve or @gulafaran, please could you retitle this to "container runtime can't load Vulkan drivers when VK_LOADER_DRIVERS_SELECT is set"?

**Comment by gulafaran** [comment]
> Ah, yes, well spotted! In older versions of Vulkan-Loader, the filename of the JSON manifest for the driver never actually mattered, so for simplicity we just use sequential numbered names when we're remapping the files into the container (we usually can't use exactly the same content or filename for various annoying reasons). In newer versions of Vulkan-Loader that have implemented the `VK_LOADER_DRIVERS_SELECT` feature, the filename has started to matter, so now we will have to teach pressure-vessel to preserve the basename of the JSON manifest, like `/usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/nvidia_icd.json`.
> 
> If prime-run is setting both `VK_ICD_FILENAMES` and `VK_LOADER_DRIVERS_SELECT`, then that's actually redundant, so you can probably work around this in the short term by unsetting `VK_LOADER_DRIVERS_SELECT`:
> 
> ```
> prime-run env -u VK_LOADER_DRIVERS_SELECT %command%
> ```
> 
> That's a narrower (and therefore more supportable) workaround than disabling the container completely.
> 
> > im quite a bit unsure of what those things actually does
> 
> The workaround you were previously using completely disables the container runtime, so it is taking Proton binaries that were intended to run in a Steam Linux Runtime 2 'soldier' container, and running them directly on your Arch system instead. If this works, then it's only working because you were lucky.

> Ah, yes, well spotted! In older versions of Vulkan-Loader, the filename of the JSON manifest for the driver never actually mattered, so for simplicity we just use sequential numbered names when we're remapping the files into the container (we usually can't use exactly the same content or filename for various annoying reasons). In newer versions of Vulkan-Loader that have implemented the `VK_LOADER_DRIVERS_SELECT` feature, the filename has started to matter, so now we will have to teach pressure-vessel to preserve the basename of the JSON manifest, like `/usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/nvidia_icd.json`.
> 
> If prime-run is setting both `VK_ICD_FILENAMES` and `VK_LOADER_DRIVERS_SELECT`, then that's actually redundant, so you can probably work around this in the short term by unsetting `VK_LOADER_DRIVERS_SELECT`:
> 
> ```
> prime-run env -u VK_LOADER_DRIVERS_SELECT %command%
> ```
> 
> That's a narrower (and therefore more supportable) workaround than disabling the container completely.
> 
> > im quite a bit unsure of what those things actually does
> 
> The workaround you were previously using completely disables the container runtime, so it is taking Proton binaries that were intended to run in a Steam Linux Runtime 2 'soldier' container, and running them directly on your Arch system instead. If this works, then it's only working because you were lucky.

thanks, yeah doing that instead makes the games work aswell. so it seems it was that conflicting.

**Comment by smcv** [comment]
> now we will have to teach pressure-vessel to preserve the basename of the JSON manifest, like /usr/lib/pressure-vessel/overrides/share/vulkan/icd.d/nvidia_icd.json

(this is in progress and should turn up in a future beta)

**Comment by smcv** [comment]
This change was included in a beta update today, which should get promoted to the default branch soon (as a side-effect of a hotfix for a game controller hotplug regression).

**Comment by smcv** [comment]
> This change was included in a beta update today, which should get promoted to the default branch soon (as a side-effect of a hotfix for a game controller hotplug regression).

The default branch has this change now, so `VK_LOADER_DRIVERS_SELECT` should now work as you had hoped.

(If you have a version with this fixed, `VERSIONS.txt` should say `pressure-vessel 0.20230216.0` or later.)

**Comment by gulafaran** [comment]
> > This change was included in a beta update today, which should get promoted to the default branch soon (as a side-effect of a hotfix for a game controller hotplug regression).
> 
> The default branch has this change now, so `VK_LOADER_DRIVERS_SELECT` should now work as you had hoped.
> 
> (If you have a version with this fixed, `VERSIONS.txt` should say `pressure-vessel 0.20230216.0` or later.)

it works now, and the log from STEAM_LINUX_RUNTIME_VERBOSE=1 shows the names as i would expect them to be now. nice , well done :)
