### ISSUE TITLE
Games using vulkan cannot start beause of CommandLine Error: Option 'help-list'

### ISSUE THREAD

**Issue by FoxVK** [ValveSoftware/steam-runtime#560]
- Name of the game with issue:
  -  Hobo Tough Life  (AppID `632300`)
  - Counter-Strike Global Offensive (AppID `730`)

## System Information
- CPU Brand:  AMD Ryzen 5 3400G with Radeon Vega Graphics
- GPU:  AMD RAVEN (raven, LLVM 15.0.3, DRM 3.49, 5.19.0-32-generic)
- Driver Version:  4.6 (Compatibility Profile) Mesa 22.3.0-devel
- Kernel Version:  5.19.0-32-generic
- Link to full system information report as [Gist](https://gist.github.com/FoxVK/a7d4d924a5a93b03148243c991122532):
- Proton version: The current default one? (Sorry when can i find it?)

## I confirm:
- [* ] that I have checked whether there are updates for my system available.

## Symptoms 
Games using vulkan won't start. (CS:GO without `-vulkan` option works)

## Reproduction
1) start the game (cs:go with -vulkan option)
2) Nothing happens only steam writes some output into console. IN case of both games there is 
```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
steam outputs are here: 
- [Hobo Tough Life](https://gist.github.com/FoxVK/b26ee7fec0b7254fb88a9614e615d9ba)
- [Counter-Strike Global Offensive](https://gist.github.com/FoxVK/61a87a2917d0bd8815f89e17f1be3f4b)
No proton log is generated.

I guess proton has problem with compilation of shaders using AMD [ROCm™ v5.4.3](https://docs.amd.com/category/ROCm_v5.4.3) llvm 15

**Comment by kisak-valve** [comment]
Hello @FoxVK, this issue needs to be evaluated by your video driver vendor. The games you've mentioned have a native Linux variant and do not use Proton unless you've explicitly configured them to use a Steam Play compatibility tool.


I've tentatively transferred this issue report to the steam-runtime issue tracker for a runtime dev to ponder if this is an issue for them, but I don't expect there to be much to ponder there.

My understanding is that ROCm is an OpenCL implementation. No part of it is used by RADV/ACO to compile shaders.

I suspect this is due to mesa coming from regular distro packages and mesa coming from `/opt/amdgpu` and their dependencies are getting smashed together in a haphazard way.

**Comment by FoxVK** [comment]
Thank you for explanation and fast reply. Messed mesa makes sense.

**Comment by FoxVK** [comment]
OK it was definitively my fault. I will describe it if someone else does same smart things...

I upgraded ubuntu from 18lts to 22lts then like in old days I checked available/installed proprietary drivers and there was nothing (because those drivers are open source and now part of kernel).

So i runt glxgears to see it gives me 60FPS (not being aware it is by default synced to refresh rate of monitor. Use `vblank_mode=0 glxgears` let it run on full throttle)

So I looked on the internet and found few discussions describing how to install it. I didn't get those people wants it because of openCL or another black magic requiring closed source drivers.

And that is how I get to state of having two mesas installed...
Uninstallation of amd drivers fixed everything.

Thank you Kisak for turning me to the right direction.
