### ISSUE TITLE
CAppSystemDict::LoadSystemAndDependencies() error

### ISSUE THREAD

**Issue by Halifay** [ValveSoftware/steam-runtime#577]
#### Your system information

* System information from steam https://gist.github.com/Halifay/d30677187ed456785e26c2573d08b8e1
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

Description
After Muerta update the game started to have visual bugs. I then reinstalled game and now it doesn't even launch.
My system is Ubuntu 20.04
Game tells to verify files as they are corrupted. Verification does not help.
Tried both default and beta Steam versions
Reinstalled Steam, Dota and various graphics libraries for them.
My only partition is ext4.
libva2:amd64 is installed systemwide
Other games are running fine. Either proton and native.
I can't find human readable crash logs to determine what could raise the error. I believe only Valve could read log from /tmp/dump/*.dmp, therefore I'm attaching one.
[crash_20230321152109_2.zip](https://github.com/ValveSoftware/Dota-2/files/11028812/crash_20230321152109_2.zip)

I don't know how to reproduce the issue.

There are screenshots of what I see on launch.
First message:
![Screenshot from 2023-03-21 14-32-59](https://user-images.githubusercontent.com/29117268/226621859-f8132bd0-cc27-402f-b58f-144e97c19d04.png)

Second message: 
![Screenshot from 2023-03-21 14-33-51](https://user-images.githubusercontent.com/29117268/226621926-87e339ad-8991-4ff8-8542-0ecb173dedfc.png)

This report is related to https://github.com/ValveSoftware/Dota2-Gameplay/issues/7665
Possibly related https://github.com/ValveSoftware/Dota-2/issues/2282

**Comment by smcv** [comment]
The only thing that is definitely wrong in that system info is that `libva-x11` can't load:

```
        "libva-x11.so.2" : {
          "messages" : [
            "Unable to find the library: /lib/x86_64-linux-gnu/libva-x11.so.2: undefined symbol: va_fool_postp"
          ],
          "soname" : null,
          "path" : null,
          "issues" : [
            "cannot-load"
          ],
          "exit-status" : 1
        },
```

which can be resolved by ensuring that if `libva2` is installed on the host system, then `libva-x11-2`, `libva-glx2` and `libva-drm2` should also all be installed, and all at the same version (ValveSoftware/steam-for-linux#8673). So please try:

```
sudo apt install libva2 libva-x11-2 libva-glx2 libva-drm2
```

If `libva2:i386` is also installed, then repeat that for `libva-x11-2:i386 libva-glx2:i386 libva-drm2:i386` (but on your system it seems that `libva2:i386` is *not* installed, so you can skip that step.)

Unfortunately, installing system packages is the only way to make this work reliably: there is nothing the Steam Runtime can do for these libraries that will work in all possible situations.

The `steam-launcher.deb` [distributed by Valve](https://repo.steampowered.com/steam/) has Recommends that ensure a correct setup (unless you go out of your way to break it) since version 1.0.0.75, and so have the `steam-installer.deb` and `steam.deb` in Debian [since version 1:1.0.0.74-2](https://salsa.debian.org/games-team/steam-installer/-/commit/75db445c0ed5309cbc9b0e91b2bab11dd68aa04b) (and adjusted again [in 1:1.0.0.75-1](https://salsa.debian.org/games-team/steam-installer/-/commit/7284b212d71ca9148c8d5c4db6dccdf2c9740a89)).

However, Ubuntu have their own derivative of the Debian packages which doesn't generally get updated with changes like these; the only way to get that version updated would be Ubuntu users opening bugs in Launchpad about it.

The `"soname" : null` that @kisak-valve noticed for all libraries is unusual, and might be a symptom of something being not quite right, but it's not *necessarily* a problem. My advice would be to try installing all of `libva2 libva-x11-2 libva-glx2 libva-drm2` first, and only investigate the `soname` thing if that doesn't solve the problem.

**Comment by Halifay** [comment]
> 

Thanks, I purged libva2 of version 2.15* and installed 2.7.0-2 so other libraries could use it. Now Dota is loading successfully but the https://github.com/ValveSoftware/Dota2-Gameplay/issues/7445 issue is still here. I'm not sure, what should I do/attach to help resolve this?

**Comment by kisak-valve** [comment]
Glad to hear its running now. I didn't expect for Dota 2 to be sensitive to 64 bit libva2 being broken in that way.

The rendering issue should be pondered on the game's side and the other issue report you have is a better place to continue discussing that.
