### ISSUE TITLE
Run gamescope outside of the runtime environment

### ISSUE THREAD

**Issue by orowith2os** [ValveSoftware/steam-runtime#600]
Partially related to https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope/pull/1

When using the Steam runtime, the appropriate variables are set such that the runtime's libraries are preferred first and foremost. This broke the gamescope Flatpak extension, as either the runtime didn't ship libXfont2, or it shipped an incompatible version.

The runtime should attempt to run gamescope in the outer environment; applications can be redirected to the X11/Wayland socket that gamescope creates from there. 

Either this, or the Steam client needs to take it to mean that any commands before `%command%` MUST be ran outside of the Steam runtime. I imagine the runtime could ship a wrapper script that redirects to the gamescope from the host when necessary.

**Comment by smcv** [comment]
> The runtime should attempt to run gamescope in the outer environment

The Steam Runtime doesn't attempt to run gamescope (the Steam client might, I don't know). Have you modified the Launch Options of a game?

If you are reporting a bug, please provide steps to reproduce the bug, without assuming that we know the subtleties of third-party projects: jumping directly to what you believe the solution should be is often not going to produce the right answer.

It is not the Steam Runtime's decision which parts of a command-line are run in what environment (the Steam client decides what it will launch, and how it will launch it), so any change to how commands are invoked would be a ValveSoftware/steam-for-linux issue. However, it's not necessarily possible to change the meaning of the Launch Options command-line: any change here would be an incompatible one.

> the runtime's libraries are preferred first and foremost

They shouldn't be. This is the scout `LD_LIBRARY_PATH` runtime in `~/.steam/root/ubuntu12_32/steam-runtime`, right? The way that runtime is meant to work is:

* a small number of problematic libraries (libdbusmenu, libcurl, GTK 2, libdbus in older versions) are "pinned" and we always use the Steam Runtime's version;
* otherwise, if we can tell which version is newer by looking at the library suffix (for example the `0.7400.6` part of `libglib-2.0.so.0.7400.6`) then we use either the Steam Runtime's version or the version from the environment in which Steam was run (normally the host system, but in your case a Flatpak runtime), whichever is newer;
* or if the versions are the same or we can't tell the difference, we prefer the version from the environment in which Steam was run

So the only time libraries from the Steam Runtime are preferred, other than a few hard-coded special cases, is if they are strictly newer than the version from outside. On a modern host system or in a modern Flatpak runtime, SDL2 will be one of the few examples of this in practice.

**Comment by smcv** [comment]
> The reason this happened was because the libraries shipped by gamescope were put at the lowest priority possible, so it could be that we were doing something wrong by doing that

Yes, I think so. If you want those binaries to be able to be launched in an arbitrary execution environment, then they need to be able to cope with having an `LD_LIBRARY_PATH` that might point to older libraries first.

> Maybe a new placeholder in Steam should be used then, perhaps something like %env-command%? then you can do host-command %env-command% runtime-command %command%

That's not really how it works. You seem to be assuming that Steam runs each game, individually, in the scout LD_LIBRARY_PATH runtime by using some `env` command; but in fact the entire process tree starting from Steam, all of it together, runs in the scout LD_LIBRARY_PATH runtime. If you plan to use an external/third-party command in Steam launch options, then it needs to be able to cope with being run from the scout environment.

If Steam client developers want to implement the feature you are implicitly requesting, the way to implement that would be something like this untested pseudocode:

```
# existing implementation
script = contents of Launch Options

if not script.contains("%command%"):
    script = "%command% " + script

script = script.replace("%command%", shell-escaped argv for compat tools and the actual game)

# new
if script.contains("%env-command%"):
    script = '"$STEAM_RUNTIME"/switch-runtime.sh --runtime="" -- ' + script.replace("%env-command%", "~/.steam/root/ubuntu12_32/steam-runtime/run.sh --"

# back to existing implementation
run "sh", "-c", script
```

but that is not a feature that currently exists, and I'm not aware of any plans to provide it.
