### ISSUE TITLE
libarchive development files are missing from the Sniper runtime?

### ISSUE THREAD

**Issue by quyykk** [ValveSoftware/steam-runtime#614]
libarchive is included in the Sniper runtime, but the development files seem to be missing from the SDK:

```bash
(steamrt sniper 0.20230718.55074)root@f5d90022e97c:/# find /usr -name libarchive\*
/usr/share/doc/libarchive-zip-perl
/usr/share/doc/libarchive13
/usr/lib/x86_64-linux-gnu/libarchive.so.13.4.3
/usr/lib/x86_64-linux-gnu/libarchive.so.13
```

The runtime library is there, but if I search for a header:

```bash
(steamrt sniper 0.20230718.55074)root@f5d90022e97c:/# find / -name archive.h
find: '/proc/tty/driver': Permission denied
(steamrt sniper 0.20230718.55074)root@f5d90022e97c:/# 
```

CMake also fails to find libarchive (using `find_package(LibArchive REQUIRED)`). Is this intentional?

**Comment by smcv** [comment]
I believe libarchive is currently pulled in as an implementation detail of something else, and isn't currently part of the ABI that sniper is aiming to guarantee.

What's your use-case for it? If I remember correctly, you're an Endless Sky contributor - are you aiming to make libarchive be an external dependency for Endless Sky?

Is the version we ship in sniper (3.4.3-2+deb11u1 from Debian 11) suitable for your requirements? (You could check this by `apt install --no-install-recommends libarchive-dev` in the SDK.)

We basically have two options for this: either make it officially part of the ABI that we guarantee (at least on x86_64, and optionally i386 too), or say that it's officially *not* part of our ABI and therefore any game that needs it is expected to bundle a suitable version.

Since we're shipping it in the Platform *already*, I would tend to lean towards making it officially part of the ABI and adding the -dev package to the SDK, unless there's some blocker that I'm not immediately seeing. I'll look into it.

**Comment by quyykk** [comment]
> are you aiming to make libarchive be an external dependency for Endless Sky?

maybe

> Is the version we ship in sniper (3.4.3-2+deb11u1 from Debian 11) suitable for your requirements?

yup

> either make it officially part of the ABI that we guarantee (at least on x86_64, and optionally i386 too), or say that it's officially not part of our ABI and therefore any game that needs it is expected to bundle a suitable version.

Either option is fine by me. I was just curious why the development files were missing for a library that is already part of the runtime :) Thanks!

**Comment by smcv** [comment]
> libarchive is included in the Sniper runtime

Hmm, on closer inspection: are you sure? I don't immediately see any reason why it would be pulled in to the Platform (which is what we ship to end users in `SteamLinuxRuntime_sniper`). It *is* included in the Sniper *SDK*, which as far as I can see is only happening because cmake depends on it. That's why there's only an x86_64 version - we don't have separate i386 builds of utilities like cmake.

In general, not every library that's included in the SDK is supported (or something that we want to support) for the Platform: the toolchain tends to have various dependencies which we don't want taking up space on end-user systems, like compilers, linkers, debuggers, various font tools for Proton, and a relatively complete Perl installation.

For most of those libraries I'd stop here and say "sorry, not part of the Platform", but libarchive is small enough and useful enough that it might make sense to provide it to third-party games anyway. @TTimo, what do you think? My guess is that it would cost about +2 MiB for `SteamLinuxRuntime_sniper` and could be up to +6 MiB for the SDK; we can halve both of those if we declare it to be 64-bit-only.

@quyykk, until we've made this decision (or if the decision is that we won't ship it), the short-term answer is: you can `apt install libarchive-dev` into the SDK, but you will need to either link it statically, or bundle a compatible `libarchive.so.13` binary with the game for now (perhaps by fetching ours with `apt download`).

**Comment by quyykk** [comment]
> Hmm, on closer inspection: are you sure?

Not really. I've been using [this link](https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-depot/sources/) to see which packages are in the runtime, but it's possible I misunderstood it.

**Comment by smcv** [comment]
> I've been using [this link](https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-depot/sources/) to see which packages are in the runtime, but it's possible I misunderstood what the list is for.

Ah, I see. That's a list of all the source code that contributes to either the Platform or SDK (including some corner cases like statically linking a library that we wouldn't otherwise have included), so that's going to be a superset of what end-users see.

https://repo.steampowered.com/steamrt-images-sniper/snapshots/latest-container-runtime-depot/com.valvesoftware.SteamRuntime.Platform-amd64%2Ci386-sniper.manifest.dpkg is what's in the Platform, either intentionally as fully-supported or unintentionally via dependencies, and there's no libarchive listed there. `steamapps/common/SteamLinuxRuntime_sniper/*_platform_*/files/manifest.dpkg` on an end-user system is the same list.

**Comment by quyykk** [comment]
Ah I see, my bad sorry. Thank you! In that case, if we'll need libarchive we'll statically link it.

**Comment by smcv** [comment]
If static linking works well for your use-case, go ahead. But this is not a definite "no" to adding libarchive to the Platform, so if you or another developer would benefit from having libarchive in the Platform, it's still something we can consider.

**Comment by TTimo** [comment]
> libarchive is small enough and useful enough that it might make sense to provide it to third-party games anyway. @TTimo, what do you think?

@smcv I agree it'd be alright to include it in sdk + platform
