### ISSUE TITLE
crashing almost on every game

### ISSUE THREAD

**Issue by AntouanK** [ValveSoftware/steam-runtime#690]
not sure how to reproduce it or show it, but the latest version is crashing a lot.
every game once at least.
kind of making it impossible to play anymore.

**Comment by smcv** [comment]
Sorry, there is not enough information here to know what component is crashing or how to solve it. You haven't said what you updated, what OS you are running on, or what error messages appear.

> the latest version

Since what update, on what date?

> crashing a lot

What is crashing?

Please provide the information that is requested in the issue template: https://raw.githubusercontent.com/ValveSoftware/steam-runtime/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md

Also please collect the logs from `~/.steam/steam/logs/` as an attachment or Gist.

**Comment by Hursofid** [comment]
I've been posting details elsewhere, please check it out
https://github.com/ValveSoftware/Dota2-Gameplay/issues/21141#issuecomment-2306881608

**Comment by AntouanK** [comment]
I know I didn't.
What's crazy, is that I got an old razer laptop I have, I got windows 11 fresh install on it ( it has a GTX 1060 ) and installed Dota 2.
Again, it crashes all the time. 4-5 times in each game, I just don't even try to play anymore.
I tried to put the settings to basic, and to change DX11 and Vulkan.
No difference.
I'm baffled how it suddenly crashes so much. Never had this issue before.
How can this be just me, when it's on two completely different computers, one with linux and one with win11?

**Comment by AntouanK** [comment]
> Also please collect the logs from ~/.steam/steam/logs/ as an attachment or Gist.

where do I find that on windows 11?

**Comment by TTimo** [comment]
The Dota 2 issue is known and being worked on. Looks like this issue here should be closed in favor of https://github.com/ValveSoftware/Dota2-Gameplay/issues/21141 - I'm not sure why we're suddenly getting a volume of Windows reporters but this is altogether the wrong tracker (Linux, steam runtime).
