### ISSUE TITLE
Runtime 3.0 (sniper) : An error occred while launching this game 

### ISSUE THREAD

**Issue by DrNossberg** [ValveSoftware/steam-runtime#691]
#### System information

* Steam Runtime Version: 3.0
* Distribution: Fedora 40
* Link to your full system information : [`Gist`](https://gist.github.com/DrNossberg/a274f5bb1d8c2c4b04e10963fe1d2522.js)
* Have you checked for system updates?: Yes
* What compatibility tool are you using?:  Steam Linux Runtime / Proton 7.0 / Proton Experimental
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? Folder `SteamLinuxRuntime/` doesn't exist
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?
depot	0.20240718.95652			# Overall version number
pressure-vessel	0.20240718.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240718.0			# from steam-runtime-tools
soldier	0.20240718.95652	soldier	0.20240718.95652	# soldier_platform_0.20240718.95652/
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?
depot	0.20240718.95653			# Overall version number
pressure-vessel	0.20240718.0	scout		# pressure-vessel-bin.tar.gz
scripts	0.20240718.0			# from steam-runtime-tools
sniper	0.20240718.95653	sniper	0.20240718.95653	# sniper_platform_0.20240718.95653/

At start-up, steam open with an error popup
![image](https://github.com/user-attachments/assets/4f550b13-7aee-4ea4-95ea-bacfafa82d8a)

Runtime can't be uninstalled due to "missing shared content".

#### Steps for reproducing this issue:

1. Launch Steam
2. "Enjoy"
3. Close the pop-up

**Comment by smcv** [comment]
Does this happen automatically when you start Steam, without you having done anything specific to trigger it?

> An error occurred while launching this game: Invalid game configuration

In previous Steam releases, this is the error you would get if you tried to launch a compatibility tool like SLR or Proton (which isn't really something that makes sense to do, 

> Runtime can't be uninstalled due to "missing shared content"

I think that's a separate issue. The error message when you try to remove a compatibility tool like SLR or Proton should be more like "Can't remove Steam Linux Runtime 3.0 (sniper) because Counterstrike 2 depends on it", but for whatever reason, Steam says "missing shared content" instead.

**Comment by smcv** [comment]
> The error message when you try to remove a compatibility tool like SLR or Proton should be more like "Can't remove Steam Linux Runtime 3.0 (sniper) because Counterstrike 2 depends on it", but for whatever reason, Steam says "missing shared content" instead.

That's https://github.com/ValveSoftware/steam-for-linux/issues/8473

**Comment by smcv** [comment]
> Does this happen automatically when you start Steam, without you having done anything specific to trigger it?

@kisak-valve, if the answer to that is "yes", then this issue should probably be moved to https://github.com/ValveSoftware/steam-for-linux/issues and retitled to something like:

`Tries to launch SLR 3.0 during startup, leading to error: Invalid game configuration`

@DrNossberg, the Steam client developers will probably ask you to attach Steam's log files (which you can collect by running `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`) so you could save some time by collecting those now. You might also be able to find useful information in those log files yourself, especially if you search for SLR 3.0's app ID `1628350`.

I don't see this issue during Steam startup myself (using the public beta Steam client, if that matters). I can make it happen artificially, by running `steam steam://run/1628350`.

**Comment by Destinyg133** [comment]
I have same issue as OP, im on arch

**Comment by smcv** [comment]
@Destinyg133:
> I have same issue as OP, im on arch

Same question: does this happen automatically when you start Steam, without you having done anything specific to trigger it?

And please attach Steam's log files (which you can collect by running `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`).

You might also be able to find useful information in those log files yourself, especially if you search for SLR 3.0's app ID `1628350`.

If this is happening automatically without you doing anything, then the bug is probably: during startup, Steam is trying to launch the compatibility tool as though it was a game, and the intended solution is that it should stop doing that. If that's the case, then this would be a `steam-for-linux` issue rather than a `steam-runtime` issue.

**Comment by Destinyg133** [comment]
@smcv https://github.com/user-attachments/files/17085565/steam-logs.tar.gz

It happens automatically without me doing anything. Simply by running 3.0 (sniper) instead of steam (runtime)

**Comment by smcv** [comment]
> Simply by running 3.0 (sniper)

What do you mean by "running 3.0 (sniper)"? Please explain exactly what it is that you do.

**Comment by Destinyg133** [comment]
@smcv 
![image](https://github.com/user-attachments/assets/bcc9b649-6b28-4b91-9f62-e2da8204b910)
![image](https://github.com/user-attachments/assets/42edd85c-6b10-450c-9fee-7353b9e71513)

**Comment by smcv** [comment]
@Destinyg133, did Steam create that shortcut on your desktop, or did you create it yourself with some tool?

If Steam created it, then the bug is that it shouldn't have done that: it should only do that for games and apps that make sense to run independently, which isn't the case for the Steam Linux Runtime and Proton families of tools.

I would recommend removing that shortcut (it's useless) and continuing to run Steam via the shortcut that was created when you first installed it. Normally that's just called "Steam". Arch uses the name "Steam (runtime)" for the original shortcut, which I think might be what has led to your confusion by making you think that there are several different valid ways to launch Steam.

@DrNossberg, are you launching Steam via a similar shortcut?

**Comment by Destinyg133** [comment]
@smcv yep, steam created that shortcut
Im always going for "steam (runtime)" just wanted to give my 2cents on this topic

**Comment by smcv** [comment]
> If Steam created it, then the bug is that it shouldn't have done that: it should only do that for games and apps that make sense to run independently, which isn't the case for the Steam Linux Runtime and Proton families of tools.

This is https://github.com/ValveSoftware/steam-for-linux/issues/10306.

There's nothing that the Steam Runtime can do to solve this (any solution would have to be on the Steam side) so I think we should close this issue as "not planned", and use https://github.com/ValveSoftware/steam-for-linux/issues/10306 to represent the Steam issue that makes this happen.
