### ISSUE TITLE
Psychonauts: No Audio Running Under Steam Linux Runtime (1.0 Scout)

### ISSUE THREAD

**Issue by HurricanePootis** [ValveSoftware/steam-runtime#703]
#### Your system information

* Steam Runtime Version: Steam Runtime Linux (1.0 Scout)
* Distribution (e.g. Ubuntu 18.04):  Arch Linux
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): [here](https://gist.github.com/HurricanePootis/6cdeec3a722a1a1e8d626ab2b19f4d7e)
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`?: `0.20240808.0`
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`?: `0.20240917.101880`
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`?: `0.20240916.101795`

#### Please describe your issue in as much detail as possible:

Ever since Steam forces the use of Steam Linux Runtime (1.0 Scout), the original Psychonauts, which has a linux native version, has no audio whenever playing it. The game uses openal for it's audio.

#### Steps for reproducing this issue:

1. Install Psychonauts
2. Launch the game
3. Hear no audio.
4. Either disable Steam's force linux runtime with `-compat-force-slr off`, or just run the game from the game folder as it does not have DRM protection
5. Hear audio

**Comment by smcv** [comment]
Looking at https://steamdb.info/depot/3840/ it seems that Psychonauts has its own bundled copies of `libSDL-1.2.so.0` and `libopenal.so.1`, which are redundant with the (probably much newer) versions provided by the Steam Runtime.

If you move one of those files out of the way (e.g. rename `libSDL-1.2.so.0` to `libSDL-1.2.so.0.bundled`) so that the Steam Runtime's equivalent gets used instead, does that help?

Ideally, please try all four combinations:

* keep using the bundled `libSDL-1.2.so.0` and `libopenal.so.1`: you already tried this: game runs but audio doesn't work
* rename `libSDL-1.2.so.0` out of the way, use the bundled `libopenal.so.1`: what happens?
* use the bundled `libSDL-1.2.so.0`, rename `libopenal.so.1` out of the way: what happens?
* rename both libraries out of the way: what happens?

**Comment by HurricanePootis** [comment]
I figured out my problem, and got a new one instead.

OpenAL can be configured at `~/.config/alsoft.conf` and `~/.alsoftrc`. I configured OpenAL to only prioritize PipeWire as an audio backend, and it seems like for whatever reason, whenever running under the Steam Linux Runtime, OpenAL could not use PipeWire as an audio backend.

However, whenever using PulseAudio under the Steam Linux Runtime and natively, the audio quality is noticeably worse in contrast to the pipewire backend.

Here is an audio clip of me opening and closing the menu without Steam Linux Runtime on PulseAudio: 

https://github.com/user-attachments/assets/a1ff9a3a-9dbd-4778-ae23-2c8f537991f5

Here is an audio clip of me opening and closing the menu with Steam Linux Runtime on PulseAudio:

https://github.com/user-attachments/assets/c6245b35-ee44-4378-856f-00c77aaa62f7

Here is an audio clip of me opening and closing the menu without Steam Linux Runtime on PipeWire:

https://github.com/user-attachments/assets/b957e610-9a89-4a17-a88f-5b772ef0eb8a



Maybe the reason why Steam Linux Runtime cannot use PipeWire as an audio backend for OpenAL may be either to having an old OpenAL version, or their OpenAL version is built without PipeWire support?

**Comment by HurricanePootis** [comment]
I can confirm that using ALSA under the Steam Linux Runtime gives good audio quality. So, to sum it up, Psychonauts not having audio was due to me explicitly setting PipeWire to be the only audio backend for OpenAL globally, and the Steam Linux Runtime version and the built-in version (due to being old), does not support it for some reason. 

A second problem arose that the PulseAudio backend sounds noticeably shittier than both PipeWire and ALSA, and that's probably due to either a game issue, an OpenAL issue, or a me issue, so it should (probably) not concern the Steam Linux Runtime.

Anyways, I guess problem solved? Or, maybe in the future, Steam Linux Runtime 1.0 Scout can get OpenAL to support PipeWire, as it is becoming the default audio system for modern desktop linux. Thank y'all for the help!

**Comment by smcv** [comment]
> OpenAL can be configured at `~/.config/alsoft.conf` and `~/.alsoftrc`. I configured OpenAL to only prioritize PipeWire as an audio backend

In general, if you are running older software, configuring it for "only use the new thing" is not reliable. If possible, it is better to have configuration that says "try to use the new thing, or if that is not possible, fall back to the old thing".

We have had a similar problem with X11 and Wayland: some Steam users configure SDL so it will only try using Wayland and refuse to use X11, but some games and components contain a copy of SDL that does not support Wayland, meaning that configuration can't possibly work. The solution here is that those users should configure SDL to *prefer* Wayland, but be willing to fall back to X11 via Xwayland. Recent Steam betas automatically override `SDL_VIDEODRIVER=wayland` and replace it with `SDL_VIDEODRIVER=wayland,x11` to prevent it from breaking things.

In the case of OpenAL, instead of

```
drivers = pipewire
```

please prefer to use something like

```
drivers = pipewire,
```

or (perhaps better)

```
drivers = pipewire,pulseaudio,
```

which means: try Pipewire, if that fails try PulseAudio, and if that fails too, because of the trailing comma, try any other driver that might be available.

> it seems like for whatever reason, whenever running under the Steam Linux Runtime, OpenAL could not use PipeWire as an audio backend.

Yes, Steam Linux Runtime 1.0 only has access to an older version of `libopenal.so.1`, which I suspect either doesn't have the Pipewire audio backend, or doesn't have it enabled.

> whenever using PulseAudio under the Steam Linux Runtime and natively, the audio quality is noticeably worse in contrast to the pipewire backend

In this game specifically, or in all games?

If this is a general issue affecting multiple games (and in particular if you can reproduce it with a game or a media player on the host system, without Steam being involved at all), I would recommend reporting that to your OS vendor as a bug in Pipewire's `pipewire-pulse` component. The design of Pipewire audio is that it is meant to be possible (even recommended) for legacy code to continue to output via PulseAudio's IPC protocol, which will be received by Pipewire's `pipewire-pulse` and translated into Pipewire's native protocol.

If this is a game-specific issue, I believe it should be possible to put an `alsoft.conf` in the same directory as the Psychonauts executable, which will overrule the configuration in your home directory. You could use that mechanism to force something like `pipewire,alsa,` for this specific game.

> I can confirm that using ALSA under the Steam Linux Runtime gives good audio quality

Behind the scenes, this is probably *also* using the PulseAudio IPC protocol: in the Steam Linux Runtime environment, if we detect PulseAudio (or `pipewire-pulse` emulating PulseAudio) on the host system, we configure the ALSA client library `libasound.so.2` to use its PulseAudio plugin to send audio to your PulseAudio-compatible sound server. Otherwise, it would not be possible for more than one process to output audio at the same time (on most hardware).

So I think the difference in sound quality that you observed is probably a result of different defaults, or something like that: perhaps OpenAL's PulseAudio backend and the ALSA client library's PulseAudio plugin are outputting with a different sample rate or bit depth or something like that? Or perhaps they are using a different buffer size, with an excessively large buffer causing unwanted latency or an excessively small buffer causing buffer underruns?

> Here is an audio clip

To me, those all sound like a very similar metallic rustling noise... but probably your headphones, speakers or ears are better than mine!
