### ISSUE TITLE
War Thunder not launching on primary monitor when run through SLR.

### ISSUE THREAD

**Issue by apemax** [ValveSoftware/steam-runtime#719]
#### Your system information

* Steam Runtime Version: Sniper, 0.20241118.108552
* Distribution (e.g. Ubuntu 18.04): Arch Linux
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): https://gist.github.com/apemax/6bde68f40ceba0352cd0a4f95b117c65
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? 0.20240806.0
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`? 0.20241118.108551
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`? 0.20241118.108552

#### Please describe your issue in as much detail as possible:
War Thunder is not launching on the primary monitor when run through Steam Linux Runtime. This happens with both Scout 1.0 and Sniper 3.0.

For me my primary monitor is on the right and my secondary monitor is on the left, If launched outside of Steam directly from the launcher WT will launch on my primary monitor, If launched through Steam WT will launch on my secondary monitor on the left.

I'm not sure if it is related but this issue with SLR is very similar to this issue with Proton:

https://github.com/ValveSoftware/Proton/issues/7717

This issue happens on both Wayland and X11 on Gnome 47.

Log file from Wayland: https://gist.github.com/apemax/343430a0a90bbe3f34a74cb70edbeed7

Log file from X11: https://gist.github.com/apemax/8257dd94a7d715a4c524ddb3c7acbc77

#### Steps for reproducing this issue:

1. Install War Thunder through Steam on a system with at least two monitors with the one on the right set as the primary monitor.
2. Set War Thunder to run through Steam Linux Runtime.
3. Launch War Thunder through Steam.
4. Notice War Thunder will launch on the left most monitor, Not the primary one.

**Comment by smcv** [comment]
Please report this issue to the game developer's support channels if you haven't already. They can comment on this issue if it would be helpful to discuss technical details with the Steam Runtime team.

I'm downloading the game onto a test machine to see whether I can get a better idea of how it works (whether it uses SDL, etc.), but it's rather large, so that's going to take a while.

> If launched outside of Steam directly from the launcher WT will launch on my primary monitor

Launching Steam games without going via Steam is not, in general, a supported thing to do. In your case it seems like it's actually working around this specific issue, for whatever reason. That gives us a useful data point, but there are several aspects of the execution environment that will be different for games launched via Steam or directly, so it's going to be difficult to narrow down which one is the most relevant here.

If we can find a mechanism to launch War Thunder via Steam that *does* give you the desired results, then that would be a smaller environmental difference to work with, which would make it more likely that either we or the game developer can figure out what is going wrong.

> War Thunder is not launching on the primary monitor when run through Steam Linux Runtime. This happens with both Scout 1.0 and Sniper 3.0.

Each Linux game on Steam should be targeting either the Steam Runtime 1 'scout' or Steam Runtime 3 'sniper' environment (developer's choice), but not both. Unfortunately there are some Steam client bugs that mean you are sometimes offered options that are not actually meant to work. We should try to focus on the scenarios that *are* meant to work.

War Thunder's developer does not appear to have flagged it as targeting sniper, so the fact that you are able to select sniper at all is a Steam client bug. This is tracked as steamrt/tasks#553 internally, and is fixed in the Steam client public beta (since 2024-11-27).

The two environments where it should be possible to run War Thunder are:

* Steam Linux Runtime 1.0 (scout) container runtime;
* legacy `LD_LIBRARY_PATH`-based scout runtime

If you [switch to the Steam client beta](https://help.steampowered.com/en/faqs/view/276C-85A0-C531-AFA3), you will be able to select these in Properties → Compatibility → Force the use of..., where they are labelled  `Steam Linux Runtime 1.0 (scout)` and `Legacy runtime 1.0` respectively.

Or, in the non-beta version of Steam, if you run it as `steam -compat-force-slr off`, the default behaviour for native Linux games will be to launch them in the legacy runtime, and SLR will normally only be used if you explicitly select it via Properties → Compatibility.

One way or the other, please try launching War Thunder via the legacy runtime. Does it choose the primary monitor that you expected, like it did when launched outside Steam? Or does it choose the "wrong" monitor, like it did when using SLR? Whichever answer you get, it will be useful information.

**Comment by smcv** [comment]
Some more information about your system:

* I see from the System Information report that you have an AMD Radeon RX 6500 XT discrete GPU. Is this your only GPU, or do you have others, either discrete or integrated?
* How are your monitors physically connected to the GPU(s)?
* What is the logical layout of your monitors? Running the `xrandr` tool and pasting its output is a convenient way to answer this. This is important because some of the common heuristics for choosing which monitor is considered to be primary will default to the monitor that is closest to coordinates (0,0), which in your case is probably the one that you had intended to be secondary.

I see that you're using an AMD proprietary Vulkan driver (AMDGPU Pro?), with an AMD non-Mesa open source Vulkan driver (AMDVLK?) also available. We have seen some odd issues with these drivers in the past, so we generally recommend Mesa's driver for AMD GPUs ("RADV" internally), but I don't know whether this would influence the choice of primary display or not.

> For me my primary monitor is on the right and my secondary monitor is on the left

Just to check, when you say "primary monitor", do you mean the one that has the GNOME menus at the top?

> This issue happens on both Wayland and X11 on Gnome 47

What do you mean by "on Wayland" and "on X11", exactly? Do you mean you logged out and back in, selecting a session at the login prompt with a name like "GNOME on Wayland" or "GNOME on Xorg"? Or do you mean that, while logged in to a Wayland session, you used environment variables or some other similar mechanism to force the game to make a specific choice between native Wayland or X11-via-Xwayland?

If you happen to know any technical details about this game - like whether it uses SDL, or what game engine or other middleware it uses - then those would also give us a good starting point to investigate further.

**Comment by apemax** [comment]
> Please report this issue to the game developer's support channels if you haven't already. They can comment on this issue if it would be helpful to discuss technical details with the Steam Runtime team.

Yes I have just reported this to the WT Developers as well.

> Launching Steam games without going via Steam is not, in general, a supported thing to do.

For WT you can download the launcher direct from the games homepage, So you can run it either way as it is available to download outside of Steam.

> One way or the other, please try launching War Thunder via the legacy runtime. Does it choose the primary monitor that you expected, like it did when launched outside Steam? Or does it choose the "wrong" monitor, like it did when using SLR? Whichever answer you get, it will be useful information.

So when I launch Steam with the `steam -compat-force-slr off` command, Then disable SLR through Properties → Compatibility, WT will launch on the correct monitor that is set as the primary monitor.

> I see from the System Information report that you have an AMD Radeon RX 6500 XT discrete GPU. Is this your only GPU, or do you have others, either discrete or integrated?

I have 2 GPUs in my system, A RX 6500 XT and a GT 710.

> How are your monitors physically connected to the GPU(s)?

My two monitor are a iiyama 24" and a BenQ 22". The iiyama 24" is connected to the RX 6500 XT via HDMI and the BenQ 22" is connected to the GT710 via DVI. The iiyama 24" is set as my primary monitor on the right.

> What is the logical layout of your monitors?

`xrandr --listmonitors
Monitors: 2

0: +*HDMI-2 1920/530x1080/300+1920+0  HDMI-2
1: +DVI-D-1 1920/480x1080/270+0+0  DVI-D-1
`

> I see that you're using an AMD proprietary Vulkan driver (AMDGPU Pro?), with an AMD non-Mesa open source Vulkan driver (AMDVLK?) also available. 

Yes I have both amdvlk and AMDGPU-Pro installed and select which one I want to use with [AMD Vulkan Prefixes](https://aur.archlinux.org/packages/amd-vulkan-prefixes). I generally run everything with the Mesa RADV driver. This issue happens with all Vulkan drivers.

> Just to check, when you say "primary monitor", do you mean the one that has the GNOME menus at the top?

Yes, It is the monitor set as primary in the Gnome Displays settings and the one with the menus at the top.

> What do you mean by "on Wayland" and "on X11", exactly?

I mean running Gnome on Wayland or X11, So selecting "Gnome" or "Gnome on Xorg" at the Gnome log in screen. WT only has support for X11 right now so for Wayland it is running through XWayland.

> If you happen to know any technical details about this game - like whether it uses SDL, or what game engine or other middleware it uses - then those would also give us a good starting point to investigate further.

WT uses the Dagor Engine which was open sourced a while ago:

https://github.com/GaijinEntertainment/DagorEngine

I believe it uses Xlib directly for window management.

I think I have answered all your questions however if I have missed anything please let me know. :)

**Comment by smcv** [comment]
My first guess here would be that there has been a behaviour change in some library that is used by this engine, possibly Xlib (libX11) or one of its associated libraries like libXrandr, such that the copy on your Arch system is choosing the monitor that you wanted to be primary, but the (probably older) copy of the same library inside the Steam Linux Runtime container is not.

In "GNOME on Xorg", the Xorg server should be directly reporting via the Xrandr protocol which display is meant to be primary.

In the Wayland session, GNOME Shell reports to Xwayland via some protocol (exactly what protocol, I don't know) which display is meant to be primary, and ideally Xwayland should pass this information on to the game via the Xrandr protocol. But there are a couple of places in that chain where this information could get lost, resulting in Xwayland and/or the game needing to fall back to heuristics - and one popular heuristic is to assume that the monitor at (0,0) is meant to be primary, which, in your case, is wrong.

> My two monitor are a iiyama 24" and a BenQ 22". The iiyama 24" is connected to the RX 6500 XT via HDMI and the BenQ 22" is connected to the GT710 via DVI. The iiyama 24" is set as my primary monitor on the right.

Ah, like several of the users on the Proton issue you linked, you have your two monitors connected to different GPUs. This might be adding complexity to your situation.

Is it physically possible to connect both of your monitors via the same GPU - ideally the GPU that you want to be using for rendering (presumably the RX 6500 XT)? If yes, does that make any difference?

Also, when you say GT710, do you mean an Nvidia discrete GPU from around 2014? Is this using the proprietary Nvidia driver, or Mesa's Nouveau driver?

**Comment by smcv** [comment]
> WT uses the Dagor Engine which was open sourced a while ago

That's helpful, because it means we'll be able to see exactly what it's doing. I'm not going to be able to look at this again for a few days, but I'll come back to it when time permits.

**Comment by apemax** [comment]
> Is it physically possible to connect both of your monitors via the same GPU - ideally the GPU that you want to be using for rendering (presumably the RX 6500 XT)? If yes, does that make any difference?

Yes the primary GPU I use to render everything is the RX 6500 XT, Unfortunately I can't plug both monitors into the RX 6500 XT because it only has two display outputs, 1 DisplayPort and 1 HDMI and because of my case I have yet to find a DP cable that will fit correctly as most DP cables have large connector housings that hit my case before going all the way in to the GPU DP port.

I did however plug both monitors into my GT 710 and it didn't make any difference, Still starts on the wrong monitor. I only tested this on Wayland as for some reason with both my monitors plugged in to the GT 710 Xorg won't start.

> Also, when you say GT710, do you mean an Nvidia discrete GPU from around 2014? Is this using the proprietary Nvidia driver, or Mesa's Nouveau driver?

Yes that would be the one. I am using Mesa's Nouveau driver with it. The main reason I even have it in my system is because of the problem I mentioned previously about not being able to plug in any DP cable into my RX 6500 XT.

> That's helpful, because it means we'll be able to see exactly what it's doing. I'm not going to be able to look at this again for a few days, but I'll come back to it when time permits.

Right, Yep no problem. :)

I will also just add, there is a report on the WT community bug tracker regarding this issue:

https://community.gaijin.net/issues/p/warthunder/i/NHkOOFjzaY0c

And they only seem to have one GPU in their system. So maybe helpful to know.

**Comment by smcv** [comment]
> Hi, i am the person that reported the bug on the war thunder bug tracker.
> My setup itself is slightly different as i have a 3 monitor setup, with one monitor to the top of primary and one to the right of primary.

So if I'm understanding correctly, you have this layout, with DisplayPort-0 as the one you intended to be primary?

```
    |-------------|
    |             |
    | Disp.Port-1 |
    |             |
|-----------------|-----------------|
|                 |                 |
|  DisplayPort-0  | HDMI-A-0        |
|                 |                 |
|-----------------|-----------------|
```

Which one did War Thunder appear on? If it's using the common heuristic that the one closest to (0,0) is meant to be primary, then I'd assume DP1?

> I found that there was no difference between normal and runtime

When you say "normal" and "runtime", do you mean you are using the non-beta version of Steam, not running it as `steam -compat-force-slr off`, not forcing any specific compatibility tool for the configuration that you are calling "normal", and using Properties → Compatibility → Force the use of... → Steam Linux Runtime 1.0 (scout) for the configuration that you are calling "runtime"?

If yes, then those two are (meant to be) exactly equivalent, so I am not surprised that they give you the same result. If you explicitly use the legacy runtime (by one of the two mechanisms in https://github.com/ValveSoftware/steam-runtime/issues/719#issuecomment-2507894566), does that make any difference?

> with proton it ran as i expected

When you run a game with Proton, it's running a completely different executable (instead of running the game's native Linux version, you're running the Windows version of the game, with Proton emulating Windows) so it isn't surprising for it to have slightly different results. I would guess that Proton is using one mechanism to decide which of several monitors is primary, and the native Linux version of War Thunder is using a different mechanism.

**Comment by smcv** [comment]
OK, thanks. So, @share234, you have essentially the same results as @apemax: with the Steam Linux Runtime 1.0 container runtime, War Thunder is full-screen on the monitor closest to the top left, but with the legacy runtime, it is full-screen on your primary monitor as you expected.

This is useful information because you are only using one GPU, so we can stop worrying about whether apemax's multiple GPUs are a factor here.

My guess at this point would be that this is most likely to be a behaviour change in something like libXrandr: the legacy runtime will normally be using the libXrandr (and other libraries) from your host system (Debian testing/unstable for share234, Arch Linux for apemax, so something quite recent for both of you), whereas the container runtime will normally be using the older libXrandr from the Steam Runtime 2 'soldier' container (approximately Debian 10).

**Comment by smcv** [comment]
This looks like an engine bug, actually. [It's dlopening `libXrandr.so`](https://github.com/GaijinEntertainment/DagorEngine/blob/a340a2496feec4195a4326b39c078988cef3947a/prog/engine/drv/drv3d_commonCode/linux/x11.h#L145C5-L145C44), but that symlink is not guaranteed to exist (especially on non-developer systems), and in Steam Linux Runtime containers, it *doesn't* exist.

For @apemax, running the game in the legacy runtime on Arch Linux hides this bug, because Arch doesn't distinguish between runtime libraries and developer files (they don't split their library packaging like Debian does).

For @share234, it seems that running the game in the legacy runtime has also hidden this bug for whatever reason. I would guess that @share234 happens to have the development files `libxrandr-dev` installed, for the same word size (32- or 64-bit) as this particular game, for reasons that are unrelated to this game.

The game developer should fix this in their game engine, because it is not safe to dlopen a library on Linux without specifying its ABI major version: in practice this means the name to open is `libXrandr.so.2` for this particular library. Pseudocode:

```diff
-    randrLib = os_dll_load("libXrandr.so");
+    randrLib = os_dll_load("libXrandr.so.2");
```

If at some point in the future there is a newer, incompatible version of `libXrandr`, we'll get symlinks `libXrandr.so` and `libXrandr.so.3` pointing to it, but attempting to call functions in that library with the interface that they had in `libXrandr.so.2` is likely to just crash. libXrandr has presumably already had three incompatible versions (`.so.0`, `.so.1`, `.so.2`) so it is not unreasonable to expect that there will eventually be a fourth.
