### ISSUE TITLE
Native linux games crash immediately upon launch

### ISSUE THREAD

**Issue by chimeraFruit** [ValveSoftware/steam-runtime#724]
#### System information

* Steam client version: 1733265492
* Distribution (e.g. Ubuntu): Linux Mint 21.3
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [Steam Runtime System Information](https://gist.github.com/chimeraFruit/2cac4b0dd34f1658daec28170d15d1b5)
* GPU: NVIDIA GeForce RTX 2070 SUPER

#### Please describe your issue in as much detail as possible:

Native linux games crash immediately upon launch. Before I was able to fix this by going into the compatibility options and forcing Steam Linux Runtime 3.0 but now the option is gone from the menu, only Steam Linux Runtime 1.0 and Legacy Runtime 1.0 appear, neither of which work.

**Comment by kisak-valve** [comment]
Hello @chimeraFruit, `cat: /home/basil/.steam/root/ubuntu12_32/steam-runtime/version.txt: No such file or directory` at https://gist.github.com/chimeraFruit/2cac4b0dd34f1658daec28170d15d1b5#file-gistfile1-txt-L532-L533 is a pretty strong indicator that the LD_* style Steam runtime files are damaged or incomplete. I would move/remove the `steam-runtime` folder in `/home/basil/.steam/root/ubuntu12_32` so that Steam regenerates the folder the next time its run.

As a side note, your NVIDIA driver install is incomplete and missing the video driver's 32 bit userspace libraries, which is causing Steam to fallback to llvmpipe (mesa's faster CPU renderer) to run at all.

**Comment by smcv** [comment]
> Steam Linux Runtime 1.0 and Legacy Runtime 1.0

Both of these runtime options rely on having a correctly functioning `~/.steam/root/ubuntu12_32/steam-runtime`. As @kisak-valve said, it seems that yours was not completely unpacked by Steam, since the Steam Runtime diagnostics show many files missing or with incorrect permissions (or perhaps you were specifically avoiding/disabling it, which is unsupported).

There might be more information in Steam's log files in `~/.steam/steam/logs` (not the same thing as the Steam Runtime diagnostics), which you would have been asked for by the `steam-for-linux` issue reporting template (`tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`). Or, there might be more information available if you run `steam` from a terminal such as `gnome-terminal`.

> Before I was able to fix this by going into the compatibility options and forcing Steam Linux Runtime 3.0

This was actually a bug. Steam Linux Runtime 3.0 should only have been available for titles that were specifically marked by their developer as expecting the newer runtime, such as Counter-Strike 2 and Endless Sky. Older native Linux titles are assumed to require a Steam Runtime 1.0 'scout'-compatible environment.

**Comment by chimeraFruit** [comment]
> I would move/remove the `steam-runtime` folder in `/home/basil/.steam/root/ubuntu12_32` so that Steam regenerates the folder the next time it's started.

This fixed it! Thank you so much!!
