### ISSUE TITLE
Can't build on openSUSE

### ISSUE THREAD

**Issue by hemna** [ValveSoftware/steam-runtime#92]
I'm trying to get proton built on my Leap 42.3 box but it requires debian installed.  Steam runs fine on my box, but I wanted to build and run the proton beta for windows games, but can't build steam-runtime, nor proton.

**Comment by TTimo** [comment]
You may want to provide more details about the difficulties you are running into. Any linux system with a schroot package should work.

Also checkout the wip-docker branch, it may be easier for you to work with docker rather than schroot?

Closing pending further feedback. We can re-open if necessary.
